// Explanations for the driver source viewer, shared by the build guide and course chapter 14.
import type { Note } from "./codeview.ts";

export const DRIVER_NOTES: Note[] = [
  { title: "What the driver needs from WebUSB", from: "export interface UsbDevice",
    html: "Only nine methods of the browser's <code>USBDevice</code>. Declaring just these makes the driver work with anything that offers them: the browser, or Node's <code>usb</code> package (which is how <code>server.ts</code> and the hardware test run the same code)." },
  { title: "Which devices to offer in the picker", from: "export const USB_FILTERS",
    html: "Realtek's vendor ID 0x0bda with the two product IDs RTL-SDR dongles use. The browser's picker lists only matching devices." },
  { title: "Constants: blocks, registers, crystal, filter", from: "const USBB = 1",
    html: "Register blocks addressed through control transfers, a few register addresses, the 28.8 MHz crystal everything is timed from, how much data to ask for per request (128 Ki samples ≈ 55 ms at 2.4 MS/s), how many requests to keep queued, and the chip's anti-aliasing filter weights (course chapter 3)." },
  { title: "Asking the browser for a dongle, and retrying", from: "static async request()",
    html: "<code>navigator.usb.requestDevice()</code> shows the browser's own picker; it's the only step that needs a user click. <code>openWithRetry</code> handles a real-world quirk: a dongle that refuses its first commands gets reset, and on some systems it then reappears as a <em>new</em> device. Because the browser remembers the permission, <code>getDevices()</code> finds it again without asking." },
  { title: "Opening: claim it, then initialize", from: "static async open(dev",
    html: "Open, select configuration 1, claim interface 0, then run the chips' start-up sequence. Failures to open or claim become plain-language errors (Windows without WinUSB; another program using the dongle). If start-up stalls, the dongle is reset and the caller is asked to find it again (the retry above)." },
  { title: "The two primitive operations", from: "private async out(",
    html: "Every register access in the whole driver is one of these: a <b>vendor control transfer</b> with request 0, where <code>value</code> and <code>index</code> say what to touch. <code>out</code> writes bytes, <code>in</code> reads them." },
  { title: "Register helpers", from: "private writeReg(",
    html: "USB and system block registers: index = block × 256, plus 0x10 to write. Demodulator registers live in pages: value = address × 256 + 0x20, and the chip needs a dummy read after every write." },
  { title: "Talking to the tuner chip", from: "private readonly i2c",
    html: "The tuner hangs off the RTL2832U's I2C bus. I2C traffic is just another control transfer (block 6), but only while the <b>repeater</b> is switched on, so <code>withTuner()</code> wraps every tuner operation in on … off." },
  { title: "Start-up: find the tuner and configure the path", from: "private async init()",
    html: "Initialize the RTL2832U, probe I2C addresses 0x34 and 0x74 for an R82xx tuner (it answers 0x69), then configure the chip for the tuner's 3.57 MHz intermediate frequency and its inverted spectrum." },
  { title: "Bringing the RTL2832U up", from: "private async initBaseband()",
    html: "About 20 writes: power the demodulator, soft-reset it, load the resampler's filter, switch to SDR mode with automatic gain control off, enable DC and I/Q correction. Each line has a comment saying what it does." },
  { title: "Packing the filter weights", from: "private async setFir()",
    html: "Eight 8-bit and eight 12-bit numbers packed into 20 bytes, then written one register at a time." },
  { title: "The demod's own mixer", from: "private async setIf(",
    html: "The tuner delivers the signal at 3.57 MHz; the RTL2832U's digital mixer moves it down to 0 Hz (course chapter 5 explains mixing)." },
  { title: "Sample rate: one division", from: "async setSampleRate(",
    html: "The chip samples at 28.8 MHz and resamples to the rate you ask for. The ratio is a fixed-point number written into two registers." },
  { title: "Tuning, gain, crystal correction", from: "async setCenterFrequency(",
    html: "Tuning and gain are the tuner's job (<code>src/r820t.ts</code>: its PLL and gain ladder); these wrap the calls in the I2C repeater. <code>setPpm</code> corrects a crystal that's slightly off, for dongles without a precise one." },
  { title: "Streaming without losing samples", from: "async stream(onData",
    html: "Keep four bulk requests queued at all times and deliver results strictly in order: wait for the oldest, immediately queue a new one, then hand the data over. The timeline above shows why asking ahead matters." },
  { title: "Stopping and closing", from: "  stop()",
    html: "<code>stop()</code> lets the loop finish its in-flight requests. <code>close()</code> puts the tuner to sleep, powers down the ADC and releases the device, so another program can use it." },
];
