# JLPT N5 grammar, in the order of Tae Kim's guide (slug = guidetojapanese.org/learn/grammar/<slug>).
# (id, pattern, meaning, explanation, [(example, English)], slug)
# Example notation: 学生{がくせい} = kanji with reading; [は] = the part the quiz blanks out.
POINTS = [
("da-desu", "N だ / です", "is, am, are", "だ (plain) and です (polite) state that something is something. With friends you can drop だ altogether: 学生 alone means 'I'm a student'.",
 [("私{わたし}は学生{がくせい}[です]。", "I am a student."), ("今日{きょう}は雨{あめ}[だ]。", "It's rainy today.")], "stateofbeing"),
("janai", "N じゃない / じゃありません", "is not", "The negative of だ/です. じゃない is casual, じゃありません or ではありません polite. じゃ is the spoken form of では.",
 [("これは私{わたし}の本{ほん}[じゃない]。", "This isn't my book."), ("サムさんは学生{がくせい}[じゃありません]。", "Sam isn't a student.")], "stateofbeing"),
("datta-deshita", "N だった / でした", "was", "Past tense of だ/です. Negative past: じゃなかった (casual) or じゃありませんでした (polite).",
 [("きのうは休{やす}み[でした]。", "Yesterday was a day off."), ("子{こ}どものとき、学生{がくせい}[だった]。", "I was a student back then.")], "stateofbeing"),
("wa", "X は", "topic: as for X", "は (read wa) marks what the sentence is about. Everything after it is a comment on that topic; it also contrasts: 'X, at least'.",
 [("ゆきさん[は]学生{がくせい}です。", "Yuki is a student."), ("肉{にく}[は]食{た}べません。", "Meat, I don't eat.")], "particlesintro"),
("mo", "X も", "also, too", "も replaces は or が to mean 'also'. With a negative it means 'not … either'.",
 [("私{わたし}[も]学生{がくせい}です。", "I'm a student too."), ("ブリップ[も]行{い}きません。", "Blip isn't going either.")], "particlesintro"),
("ga", "X が", "subject: X (is the one that)", "が marks the subject and points at new or specific information: who, what, which one. Question words like だれ and 何 take が, not は.",
 [("だれ[が]来{き}ましたか。", "Who came?"), ("ゆきさん[が]来{き}ました。", "Yuki (is the one who) came.")], "particlesintro"),
("ka", "～か", "question marker", "か at the end turns a sentence into a question, no change in word order. In casual speech, a rising の or just rising tone does the job.",
 [("日本人{にほんじん}です[か]。", "Are you Japanese?"), ("何{なに}を食{た}べます[か]。", "What will you eat?")], "question"),
("no", "A の B", "A's B, B of A", "の links nouns; the first describes the second. It also replaces a noun that's understood: 私の = mine.",
 [("私{わたし}[の]ロボット", "my robot"), ("これはゆきさん[の]です。", "This is Yuki's.")], "nounparticles"),
("to-and", "A と B", "A and B (complete list)", "と joins nouns into a complete list. It's only for nouns, not for joining sentences.",
 [("パン[と]コーヒー", "bread and coffee"), ("ゆきさん[と]サムさんが来{き}ました。", "Yuki and Sam came.")], "nounparticles"),
("ya", "A や B", "A, B and so on", "や lists examples and implies there are more. Often ends with など (etc.).",
 [("りんご[や]バナナを買{か}いました。", "I bought apples, bananas and such."), ("本{ほん}[や]ノートなどがあります。", "There are books, notebooks and so on.")], "nounparticles"),
("to-with", "N と", "with (someone)", "と after a person means doing something together with them.",
 [("友{とも}だち[と]映画{えいが}を見{み}ました。", "I watched a movie with a friend."), ("サムさん[と]話{はな}します。", "I talk with Sam.")], "verbparticles"),
("wo", "N を V", "object marker", "を (read o) marks what the action is done to: eat what, read what.",
 [("パン[を]食{た}べます。", "I eat bread."), ("本{ほん}[を]読{よ}みました。", "I read a book.")], "verbparticles"),
("ni-time", "time に", "at (a specific time)", "に marks a specific time: a clock time, a day of the week, a date. Relative times like 今日 and 毎日 take no に.",
 [("七時{しちじ}[に]起{お}きます。", "I get up at seven."), ("日曜日{にちようび}[に]行{い}きます。", "I'll go on Sunday.")], "verbparticles"),
("ni-dest", "place に / へ", "to (a destination)", "に or へ (read e) marks where you're going. へ stresses direction, に the arrival; for N5 they're interchangeable with 行く, 来る, 帰る.",
 [("学校{がっこう}[に]行{い}きます。", "I go to school."), ("日本{にほん}[へ]帰{かえ}ります。", "I'm going back to Japan.")], "verbparticles"),
("ni-exist", "place に ある / いる", "is in, exists at", "に marks where something exists. ある is for things and plants, いる for people and animals.",
 [("机{つくえ}の上{うえ}[に]本{ほん}があります。", "There's a book on the desk."), ("公園{こうえん}[に]犬{いぬ}がいます。", "There's a dog in the park.")], "verbparticles"),
("de-place", "place で V", "at, in (where an action happens)", "で marks where an action takes place. Compare に, which marks where something simply exists.",
 [("図書館{としょかん}[で]勉強{べんきょう}します。", "I study at the library."), ("カフェ[で]会{あ}いましょう。", "Let's meet at the café.")], "verbparticles"),
("de-means", "N で", "by, with, in (means)", "で also marks the tool or means: by bus, with chopsticks, in Japanese.",
 [("バス[で]行{い}きます。", "I go by bus."), ("日本語{にほんご}[で]話{はな}してください。", "Please speak in Japanese.")], "verbparticles"),
("kara-made", "A から B まで", "from A to/until B", "から = from (a place or time), まで = until, as far as.",
 [("九時{くじ}[から]五時{ごじ}まで働{はたら}きます。", "I work from nine to five."), ("駅{えき}から家{いえ}[まで]歩{ある}きます。", "I walk from the station to my house.")], "verbparticles"),
("ne-yo", "～ね / ～よ", "…right? / …you know", "ね seeks agreement ('isn't it?'); よ tells the listener something new. よね = 'right?' when you're fairly sure.",
 [("いい天気{てんき}です[ね]。", "Nice weather, isn't it?"), ("このラーメン、おいしい[よ]。", "This ramen is good, you know.")], "adverbs"),
("kosoado", "これ・それ・あれ・どれ", "this, that, that over there, which", "こ = near me, そ = near you, あ = far from both, ど = which. この/その/あの/どの come before a noun; ここ/そこ/あそこ/どこ are places.",
 [("[これ]は何{なん}ですか。", "What is this?"), ("トイレは[どこ]ですか。", "Where is the restroom?")], "nounparticles"),
("i-adj", "い-adjectives", "adjectives ending in い", "Adjectives ending in い conjugate themselves: 高い, 高くない (not), 高かった (was), 高くなかった (wasn't). いい is irregular: よくない, よかった.",
 [("この本{ほん}は[おもしろい]です。", "This book is interesting."), ("きのうは[寒{さむ}かった]です。", "It was cold yesterday.")], "adjectives"),
("na-adj", "な-adjectives", "adjectives that take な", "Noun-like adjectives take な before a noun (きれいな花) and conjugate like nouns: きれいだ, きれいじゃない, きれいだった.",
 [("[静{しず}かな]町{まち}ですね。", "It's a quiet town."), ("この公園{こうえん}はきれい[じゃない]。", "This park isn't pretty.")], "adjectives"),
("suki-kirai", "N が好き / きらい", "like / dislike", "好き and きらい are な-adjectives: the thing you like takes が. 大好き = love, 上手/下手 = good/bad at.",
 [("ねこ[が]好{す}きです。", "I like cats."), ("サムさんは料理{りょうり}が[上手{じょうず}]です。", "Sam is good at cooking.")], "adjectives"),
("verb-groups", "ru-verbs and u-verbs", "the two verb groups", "Ru-verbs (食べる, 見る) drop る to conjugate; u-verbs (飲む, 行く) change their last sound. Only する and 来る are irregular.",
 [("ごはんを[食{た}べる]。", "I eat a meal."), ("水{みず}を[飲{の}む]。", "I drink water.")], "verbs"),
("masu", "V-ます", "polite verb form", "The ます form is the polite present/future. Ru-verbs: 食べ+ます; u-verbs: change u→i (飲む → 飲みます); する → します, 来る → 来ます.",
 [("毎朝{まいあさ}コーヒーを飲{の}[みます]。", "I drink coffee every morning."), ("あした東京{とうきょう}に行{い}[きます]。", "I'll go to Tokyo tomorrow.")], "polite"),
("masen", "V-ません / V-ない", "doesn't, won't", "Negative: ます → ません (polite); plain ない form: 食べない, 飲まない (u→a), しない, 来ない. ある becomes ない.",
 [("肉{にく}は食{た}べ[ません]。", "I don't eat meat."), ("今日{きょう}は行{い}か[ない]。", "I'm not going today.")], "negativeverbs"),
("mashita", "V-ました / V-た", "did", "Past: ます → ました, ません → ませんでした. Plain past た follows the て-form sound changes: 食べた, 飲んだ, 行った, した.",
 [("きのう映画{えいが}を見{み}[ました]。", "I watched a movie yesterday."), ("もう宿題{しゅくだい}を[した]。", "I already did my homework.")], "past_tense"),
("mashou", "V-ましょう / V-ませんか", "let's … / won't you …?", "ましょう suggests doing something together; ませんか is a softer invitation ('why don't we?').",
 [("いっしょに食{た}べ[ましょう]。", "Let's eat together."), ("映画{えいが}を見{み}[ませんか]。", "Would you like to watch a movie?")], "polite"),
("tai", "V-たい", "want to (do)", "Stem + たい = want to do. It conjugates like an い-adjective: 行きたくない, 行きたかった. Use it for yourself; for others say たがっている.",
 [("日本{にほん}に行{い}き[たい]です。", "I want to go to Japan."), ("今日{きょう}は何{なに}も食{た}べ[たくない]。", "I don't want to eat anything today.")], "desire"),
("hoshii", "N が欲しい", "want (a thing)", "欲しい is an い-adjective for wanting things. For actions use たい.",
 [("新{あたら}しいパソコンが[欲{ほ}しい]です。", "I want a new computer."), ("何{なに}[が]欲{ほ}しいですか。", "What do you want?")], "desire"),
("te-form", "V-て", "and (then)", "The て-form links actions in order: 起きて、食べて、出かけた. Sound changes for u-verbs: う/つ/る → って, む/ぶ/ぬ → んで, く → いて, ぐ → いで, す → して; 行く → 行って.",
 [("朝{あさ}起{お}き[て]、コーヒーを飲{の}みます。", "I get up and drink coffee."), ("駅{えき}まで歩{ある}い[て]行{い}きます。", "I walk to the station.")], "compound"),
("te-kudasai", "V-てください", "please do", "て-form + ください is a polite request. Negative: ないでください = please don't.",
 [("ここに名前{なまえ}を書{か}い[てください]。", "Please write your name here."), ("写真{しゃしん}をとら[ないでください]。", "Please don't take photos.")], "requests"),
("te-iru", "V-ている", "is doing / is in a state", "て + いる is an ongoing action (食べている = eating) or a resulting state (結婚している = is married, 住んでいる = lives).",
 [("今{いま}、本{ほん}を読{よ}ん[でいます]。", "I'm reading a book now."), ("ニューヨークに住{す}ん[でいます]。", "I live in New York.")], "teform"),
("te-mo-ii", "V-てもいい", "may, it's okay to", "て-form + もいい(です) gives or asks permission. ～てもいいですか = may I?",
 [("ここに座{すわ}っ[てもいい]ですか。", "May I sit here?"), ("写真{しゃしん}をとっ[てもいい]ですよ。", "You may take photos.")], "must"),
("te-wa-ikenai", "V-てはいけない", "must not", "て + はいけない / はだめ forbids something. Casual: ちゃだめ.",
 [("ここでタバコを吸{す}っ[てはいけません]。", "You must not smoke here."), ("夜{よる}おそく電話{でんわ}し[てはだめ]だよ。", "Don't call late at night.")], "must"),
("tari", "V-たり V-たりする", "do things like A and B", "A non-exhaustive list of actions: past た + り, ending with する.",
 [("週末{しゅうまつ}は本{ほん}を読{よ}ん[だり]、映画{えいが}を見{み}たりします。", "On weekends I read books, watch movies and such."), ("歌{うた}ったり踊{おど}ったり[した]。", "We sang, danced and so on.")], "compound"),
("mae-ni", "V-る前に", "before doing", "Dictionary form + 前に = before. With nouns: 食事の前に.",
 [("寝{ね}る[前{まえ}に]歯{は}をみがきます。", "I brush my teeth before sleeping."), ("食事{しょくじ}の[前{まえ}に]手{て}を洗{あら}います。", "I wash my hands before meals.")], "timeactions"),
("ta-ato-de", "V-た後で", "after doing", "Past た + 後で (あとで) = after. With nouns: 授業の後で.",
 [("宿題{しゅくだい}をした[後{あと}で]遊{あそ}びます。", "I'll play after doing homework."), ("仕事{しごと}の[後{あと}で]飲{の}みに行{い}こう。", "Let's go drinking after work.")], "timeactions"),
("te-kara", "V-てから", "after (and then)", "て + から = after doing A, (then) B. It stresses order more than 後で.",
 [("手{て}を洗{あら}っ[てから]食{た}べます。", "I eat after washing my hands."), ("家{いえ}に帰{かえ}っ[てから]電話{でんわ}します。", "I'll call once I get home.")], "compound"),
("kara-reason", "～から", "because, so", "から after a sentence gives the reason, and the result follows. Polite: 雨ですから.",
 [("雨{あめ}だ[から]、行{い}きません。", "It's raining, so I'm not going."), ("おいしい[から]、もう一{ひと}つ食{た}べます。", "It's good, so I'll have another.")], "compound"),
("ga-but", "～が / けど", "but", "が or けど after a sentence means 'but'. けど is casual; both also soften a lead-in: すみませんが… 'excuse me, but…'.",
 [("高{たか}いです[が]、おいしいです。", "It's expensive but delicious."), ("行{い}きたい[けど]、時間{じかん}がない。", "I want to go, but I have no time.")], "compound"),
("noun-modifier", "V + N", "a noun described by a verb", "Any plain-form sentence can sit right before a noun to describe it, like an English 'that/who' clause: 私が読んだ本 = the book I read.",
 [("きのう[見{み}た]映画{えいが}はおもしろかった。", "The movie I saw yesterday was interesting."), ("あそこで[話{はな}している]人{ひと}はだれ？", "Who's the person talking over there?")], "clause"),
("ni-naru", "～になる / ～くなる", "become", "Nouns and な-adjectives take になる; い-adjectives change い → く: 寒くなる (get cold).",
 [("先生{せんせい}[に]なりたい。", "I want to become a teacher."), ("だんだん寒{さむ}[く]なりました。", "It gradually got colder.")], "surunaru"),
("adverb-ku-ni", "い → く / な → に", "adverbs from adjectives", "い-adjectives become adverbs with く (早く = quickly), な-adjectives with に (静かに = quietly).",
 [("早{はや}[く]起{お}きました。", "I got up early."), ("静{しず}か[に]してください。", "Please be quiet.")], "adverbs"),
("existence", "ある / いる", "there is, to have", "ある for things and plants, いる for people and animals. ある also means 'to have': 時間がある.",
 [("部屋{へや}にテレビが[あります]。", "There's a TV in the room."), ("兄{あに}が二人{ふたり}[います]。", "I have two older brothers.")], "verbparticles"),
("counters", "number + counter", "counting things", "Japanese counts with counters: ～つ (general), ～人 (people), ～枚 (flat), ～本 (long), ～冊 (books), ～匹 (small animals). Counter + verb: りんごを三つ買った.",
 [("りんごを[三{みっ}つ]ください。", "Three apples, please."), ("学生{がくせい}が[五人{ごにん}]います。", "There are five students.")], "numbers"),
("question-words", "何・だれ・どこ・いつ・どう", "what, who, where, when, how", "Question words sit where the answer goes; no word order change. どうして / なぜ = why, いくら = how much, いくつ = how many.",
 [("[だれ]と行{い}きますか。", "Who are you going with?"), ("これは[いくら]ですか。", "How much is this?")], "question"),
("ka-mo-indef", "何か・だれも・どこへも", "something, nobody, nowhere", "Question word + か = some-: 何か, だれか, どこか. Question word + も with a negative = no-: だれも来ない (nobody came).",
 [("[何{なに}か]食{た}べたい。", "I want to eat something."), ("[だれも]いません。", "There's nobody here.")], "question"),
("deshou", "～でしょう / だろう", "probably, …right?", "でしょう (polite) and だろう (plain) guess or invite agreement. With rising tone: 'right?'.",
 [("あしたは雨{あめ}[でしょう]。", "It will probably rain tomorrow."), ("疲{つか}れた[でしょう]？", "You're tired, right?")], "certainty"),
("mou-mada", "もう / まだ", "already / not yet, still", "もう + past = already; もう + negative = not anymore. まだ + negative = not yet; まだ + positive = still.",
 [("[もう]食{た}べました。", "I've already eaten."), ("[まだ]来{き}ていません。", "They haven't come yet.")], "adverbs"),
("ni-iku", "V-stem に行く", "go to do", "Stem + に + 行く/来る/帰る = go (come, return) somewhere to do something.",
 [("パンを買{か}い[に]行{い}きます。", "I'm going to buy bread."), ("日本{にほん}へ勉強{べんきょう}し[に]来{き}ました。", "I came to Japan to study.")], "verbparticles"),
("hou-ga-ii", "V-たほうがいい", "you'd better", "Past た + ほうがいい gives advice. Negative advice: ないほうがいい.",
 [("早{はや}く寝{ね}た[ほうがいい]ですよ。", "You'd better go to bed early."), ("あまり飲{の}ま[ないほうがいい]。", "Better not drink too much.")], "comparison"),
("yori", "A は B より", "A is more … than B", "より = than. AのほうがBより… = A is more … than B. 一番 = the most.",
 [("東京{とうきょう}はニューヨーク[より]大{おお}きい。", "Tokyo is bigger than New York."), ("なつが[一番{いちばん}]好{す}きです。", "I like summer best.")], "comparison"),
("tsumori", "V-るつもり", "intend to", "Dictionary form + つもりだ = plan or intend to do. Negative: ないつもり.",
 [("来年{らいねん}日本{にほん}に行{い}く[つもり]です。", "I plan to go to Japan next year."), ("今日{きょう}は何{なに}も買{か}わない[つもり]だ。", "I don't intend to buy anything today.")], "desire"),
("nakute-wa", "V-なければならない", "must, have to", "なければならない / なければいけない = have to. Casual: なきゃ, なくちゃ.",
 [("もう帰{かえ}ら[なければなりません]。", "I have to go home now."), ("宿題{しゅくだい}をし[なきゃ]。", "Gotta do my homework.")], "must"),
("nakute-mo-ii", "V-なくてもいい", "don't have to", "Negative て + もいい = it's okay not to.",
 [("あしたは来{こ}[なくてもいい]です。", "You don't have to come tomorrow."), ("全部{ぜんぶ}食{た}べ[なくてもいい]よ。", "You don't have to eat it all.")], "must"),
("toki", "～とき", "when", "とき turns a clause into a time: 子どものとき (as a child), 寝るとき (when going to bed).",
 [("ひまな[とき]、何{なに}をしますか。", "What do you do when you're free?"), ("日本{にほん}に行{い}った[とき]、すしを食{た}べた。", "When I went to Japan, I ate sushi.")], "timeactions"),
("nagara", "V-stem ながら", "while doing", "Stem + ながら: doing two things at once, the main action at the end.",
 [("音楽{おんがく}を聞{き}き[ながら]勉強{べんきょう}します。", "I study while listening to music."), ("歩{ある}き[ながら]話{はな}しましょう。", "Let's talk while we walk.")], "timeactions"),
("dake", "～だけ", "only, just", "だけ = only, just that much.",
 [("一{ひと}つ[だけ]ください。", "Just one, please."), ("水{みず}[だけ]飲{の}みました。", "I only drank water.")], "amount"),
("shika-nai", "～しか～ない", "nothing but, only", "しか + negative = only, with a feeling that it's not enough.",
 [("百円{ひゃくえん}[しか]ありません。", "I only have 100 yen."), ("日本語{にほんご}は少{すこ}し[しか]話{はな}せない。", "I can only speak a little Japanese.")], "amount"),
("koto-ga-aru", "V-たことがある", "have done (experience)", "Past た + ことがある = have done it at some point.",
 [("すしを食{た}べた[ことがあります]か。", "Have you ever eaten sushi?"), ("富士山{ふじさん}に登{のぼ}った[ことがない]。", "I've never climbed Mt. Fuji.")], "genericnouns"),
("dict-koto-ga-dekiru", "V-ることができる", "can (do)", "Dictionary form + ことができる = can. The shorter potential form (N4) is more common in speech.",
 [("ピアノをひく[ことができます]。", "I can play the piano."), ("ここで泳{およ}ぐ[ことはできません]。", "You can't swim here.")], "genericnouns"),
("sugiru", "～すぎる", "too (much)", "Stem or adjective stem + すぎる = too much: 食べすぎる (overeat), 高すぎる (too expensive).",
 [("このくつは高{たか}[すぎ]ます。", "These shoes are too expensive."), ("きのう飲{の}み[すぎた]。", "I drank too much yesterday.")], "amount"),
("o-go", "お～ / ご～", "polite prefix", "お (native words) and ご (Chinese-origin words) add politeness: お茶, お金, ご飯, ご家族.",
 [("[お]茶{ちゃ}をどうぞ。", "Have some tea."), ("[ご]家族{かぞく}はお元気{げんき}ですか。", "Is your family well?")], "people"),
("ni-suru", "N にする", "decide on", "N にします = I'll have N (choosing, ordering).",
 [("コーヒー[にします]。", "I'll have coffee."), ("どれ[にする]？", "Which one will you go with?")], "surunaru"),
("douyatte", "どうやって / どうして", "how / why", "どうやって asks how (method); どうして or なぜ asks why. Answer why with から or ので.",
 [("[どうやって]来{き}ましたか。", "How did you get here?"), ("[どうして]日本語{にほんご}を勉強{べんきょう}しますか。", "Why do you study Japanese?")], "question"),
]
