# JLPT N4 grammar (format: see grammar_n5.py). Concepts follow Tae Kim's guide; explanations and examples are our own.
POINTS = [
("plain-form", "plain (dictionary) form", "casual speech", "Friends and family use plain forms: 行く, 行かない, 行った, 行かなかった; だ for です (often dropped). Polite ます/です is for strangers and work.",
 [("あした、何{なに}[する]？", "What are you doing tomorrow?"), ("きのう、映画{えいが}見{み}[た]？", "Did you watch a movie yesterday?")], "polite"),
("potential", "V-える / V-られる", "can (do)", "Potential form: u-verbs change u → e + る (飲む → 飲める), ru-verbs add られる (食べられる; casually 食べれる), する → できる, 来る → 来られる. The object often takes が.",
 [("日本語{にほんご}が話{はな}[せます]。", "I can speak Japanese."), ("辛{から}いものは食{た}べ[られない]。", "I can't eat spicy food.")], "potential"),
("volitional", "V-よう / V-おう", "let's (casual), shall I", "Volitional form: ru-verbs + よう (食べよう), u-verbs u → ou (行こう), しよう, 来よう. Casual 'let's'.",
 [("いっしょに帰{かえ}[ろう]。", "Let's go home together."), ("何{なに}を食{た}べ[よう]か。", "What shall we eat?")], "desire"),
("you-to-omou", "V-ようと思う", "I'm thinking of doing", "Volitional + と思っている = I'm planning / thinking of doing.",
 [("来年{らいねん}、日本{にほん}に行{い}こう[と思{おも}って]います。", "I'm thinking of going to Japan next year."), ("今日{きょう}は早{はや}く寝{ね}よう[と思{おも}う]。", "I think I'll go to bed early today.")], "desire"),
("to-omou", "～と思う", "I think that", "Plain form + と思う = I think. と marks what you think or say; だ is required after nouns and な-adjectives: 学生だと思う.",
 [("あしたは雨{あめ}だ[と思{おも}います]。", "I think it'll rain tomorrow."), ("この映画{えいが}はおもしろい[と思{おも}う]。", "I think this movie is interesting.")], "actionclause"),
("to-iu", "～と言う", "say that", "Plain form + と言う quotes speech. Exact words go in 「」 with と.",
 [("先生{せんせい}は来週{らいしゅう}テストがある[と言{い}いました]。", "The teacher said there's a test next week."), ("ゆきさんは「すぐ行{い}く」[と]言{い}った。", "Yuki said, 'I'll go right away.'")], "actionclause"),
("tte", "～って", "casual quote: (they) say, called", "って is the casual と言う / という: '…, they said', or 'something called…'.",
 [("サムさん、来{こ}ない[って]。", "Sam says he's not coming."), ("ブリップ[って]何{なん}ですか。", "What's this 'Blip'?")], "define"),
("to-iu-n", "N という N", "a N called …", "Xという Y = a Y called X: 『ヨム』というアプリ.",
 [("「ヨム」[という]アプリを使{つか}っています。", "I use an app called Yomu."), ("これは何{なん}[という]花{はな}ですか。", "What's this flower called?")], "define"),
("conditional-to", "～と", "when(ever), if (always)", "Dictionary form + と: whenever A happens, B follows naturally. Good for directions and natural results; not for requests or wishes.",
 [("春{はる}になる[と]、花{はな}がさきます。", "When spring comes, the flowers bloom."), ("右{みぎ}にまがる[と]、駅{えき}があります。", "Turn right and there's the station.")], "conditionals"),
("conditional-ba", "～ば", "if", "ば-form: u → e + ば (行けば), ru-verbs れば (食べれば), い-adjectives ければ (高ければ). States a condition and its result.",
 [("急{いそ}[げば]、間{ま}に合{あ}います。", "If you hurry, you'll make it."), ("安{やす}[ければ]買{か}います。", "If it's cheap, I'll buy it.")], "conditionals"),
("conditional-tara", "～たら", "if, when (after)", "Past た + ら: if A (happens), then B; also 'when A is done, B'. The most flexible conditional, fine for requests and wishes.",
 [("雨{あめ}が降{ふ}っ[たら]、行{い}きません。", "If it rains, I won't go."), ("駅{えき}に着{つ}い[たら]、電話{でんわ}してください。", "Please call when you get to the station.")], "conditionals"),
("conditional-nara", "～なら", "if (that's the case)", "なら picks up a topic or situation: 'if it's X (that you mean)'. Great for advice: 'if you're going to Kyoto, …'.",
 [("京都{きょうと}に行{い}く[なら]、秋{あき}がいいですよ。", "If you're going to Kyoto, autumn is best."), ("サムさん[なら]知{し}っていると思{おも}う。", "If anyone, Sam would know.")], "conditionals"),
("tara-dou", "～たらどう", "why don't you", "たら + どう(ですか) suggests something.",
 [("少{すこ}し休{やす}ん[だらどう]？", "Why don't you take a break?"), ("先生{せんせい}に聞{き}い[たらどうですか]。", "Why not ask the teacher?")], "desire"),
("te-miru", "V-てみる", "try doing", "て + みる = do it and see how it goes.",
 [("このケーキ、食{た}べ[てみて]。", "Try this cake."), ("日本語{にほんご}で話{はな}し[てみます]。", "I'll try speaking in Japanese.")], "try"),
("you-to-suru", "V-ようとする", "try to, be about to", "Volitional + とする = attempt (often failing), or be just about to.",
 [("起{お}きよう[とした]けど、起{お}きられなかった。", "I tried to get up but couldn't."), ("出{で}かけよう[とした]とき、電話{でんわ}が鳴{な}った。", "Just as I was about to leave, the phone rang.")], "try"),
("te-shimau", "V-てしまう", "end up doing, do completely", "てしまう: finish something fully, or (more often) do something with regret. Casual: ちゃう / じゃう.",
 [("ケーキを全部{ぜんぶ}食{た}べ[てしまった]。", "I ate the whole cake (oops)."), ("さいふを忘{わす}れ[ちゃった]。", "I forgot my wallet.")], "unintended"),
("te-oku", "V-ておく", "do in advance", "て + おく = do something ahead, for later; or leave it as is. Casual: とく.",
 [("旅行{りょこう}の前{まえ}にホテルを予約{よやく}し[ておきます]。", "I'll book the hotel before the trip."), ("窓{まど}を開{あ}け[ておいて]。", "Leave the window open.")], "teform"),
("te-aru", "V-てある", "has been done (on purpose)", "Transitive verb + てある: someone did it and the result is there. The thing takes が.",
 [("壁{かべ}に地図{ちず}がはっ[てあります]。", "A map has been put up on the wall."), ("ビールは冷{ひ}やし[てある]よ。", "The beer's been chilled.")], "teform"),
("te-iku-kuru", "V-ていく / V-てくる", "go/come doing; change over time", "ていく = going away or changing from now on; てくる = coming toward or changing up to now. Also 'go and do, then come back': 買ってくる.",
 [("コンビニで水{みず}を買{か}っ[てくる]ね。", "I'll go buy water at the convenience store (and come back)."), ("これから寒{さむ}くなっ[ていきます]。", "It will get colder from now on.")], "teform"),
("transitive", "開ける / 開く", "transitive and intransitive pairs", "Many verbs come in pairs: transitive (someone does it, を): ドアを開ける; intransitive (it happens, が): ドアが開く. Similar: 閉める/閉まる, つける/つく, 始める/始まる.",
 [("ドアを[開{あ}けて]ください。", "Please open the door."), ("ドアが[開{あ}きました]。", "The door opened.")], "verbparticles"),
("ageru", "あげる", "give (to others)", "あげる = I/we give to someone else. Polite down to animals/kids: やる. てあげる = do a favor for someone.",
 [("友{とも}だちに本{ほん}を[あげました]。", "I gave my friend a book."), ("妹{いもうと}に宿題{しゅくだい}を教{おし}え[てあげた]。", "I taught my sister her homework.")], "favors"),
("kureru", "くれる", "give (to me / us)", "くれる = someone gives to me or my group. てくれる = someone does me a favor.",
 [("母{はは}がセーターを[くれました]。", "My mom gave me a sweater."), ("サムさんが手伝{てつだ}っ[てくれた]。", "Sam helped me out.")], "favors"),
("morau", "もらう", "receive", "もらう = I receive (from に/から). てもらう = have someone do something for me.",
 [("父{ちち}に時計{とけい}を[もらいました]。", "I got a watch from my dad."), ("ゆきさんに日本語{にほんご}を教{おし}え[てもらった]。", "I had Yuki teach me Japanese.")], "favors"),
("te-kuremasenka", "～てくれませんか / ～てもらえませんか", "could you (please)", "Polite requests built on giving verbs: てくれませんか, more polite てもらえませんか, いただけませんか.",
 [("ちょっと手伝{てつだ}っ[てくれませんか]。", "Could you help me a little?"), ("もう一度{いちど}言{い}っ[てもらえませんか]。", "Could you say that again?")], "requests"),
("nasai", "V-なさい", "do (command, parent to child)", "Stem + なさい is a firm but polite order, typical of parents and teachers.",
 [("早{はや}く寝{ね}[なさい]。", "Go to bed now."), ("よく聞{き}き[なさい]。", "Listen carefully.")], "requests"),
("imperative", "命令形 (行け, 食べろ)", "blunt command", "Plain imperative: u → e (行け), ru-verbs ろ (食べろ), しろ, 来い. Rude except in signs, sports and quotes. Prohibition: dictionary form + な (行くな).",
 [("止{と}ま[れ]", "Stop (road sign)"), ("走{はし}る[な]！", "Don't run!")], "requests"),
("node", "～ので", "because, since", "ので gives a reason more softly and objectively than から. After nouns and な-adjectives: なので.",
 [("雨{あめ}な[ので]、出{で}かけません。", "Since it's raining, I won't go out."), ("頭{あたま}が痛{いた}い[ので]、帰{かえ}ります。", "I have a headache, so I'll go home.")], "compound"),
("noni", "～のに", "even though, despite", "のに = although, with surprise or complaint. Nouns and な-adjectives: なのに.",
 [("約束{やくそく}した[のに]、来{こ}なかった。", "Even though we promised, they didn't come."), ("勉強{べんきょう}した[のに]、テストは難{むずか}しかった。", "I studied, yet the test was hard.")], "compound"),
("noni-purpose", "V-るのに", "in order to, for", "Dictionary form + のに (+ 使う, いい, 便利, 時間がかかる) = for the purpose of.",
 [("このアプリは漢字{かんじ}を覚{おぼ}える[のに]便利{べんり}です。", "This app is handy for learning kanji."), ("駅{えき}まで行{い}く[のに]十分{じゅっぷん}かかる。", "It takes ten minutes to get to the station.")], "compound"),
("tame-ni", "V-るために", "in order to, for the sake of", "Dictionary form or N の + ために = for a goal (something you control) or for someone's benefit.",
 [("日本{にほん}で働{はたら}く[ために]、日本語{にほんご}を勉強{べんきょう}しています。", "I study Japanese in order to work in Japan."), ("家族{かぞく}の[ために]料理{りょうり}します。", "I cook for my family.")], "reasoning"),
("you-ni-purpose", "V-るように", "so that", "Dictionary or ない form + ように = so that (a state you can't directly control, often with potential verbs).",
 [("聞{き}こえる[ように]、大{おお}きい声{こえ}で話{はな}してください。", "Please speak loudly so we can hear."), ("忘{わす}れない[ように]メモします。", "I'll write it down so I don't forget.")], "reasoning"),
("you-ni-naru", "V-るようになる", "come to (be able to) do", "Dictionary/potential form + ようになる = a change in ability or habit.",
 [("ひらがなが読{よ}める[ようになりました]。", "I've become able to read hiragana."), ("毎朝{まいあさ}走{はし}る[ようになった]。", "I've started running every morning.")], "surunaru"),
("you-ni-suru", "V-るようにする", "make a point of doing", "Dictionary/ない form + ようにする = try to make it a habit.",
 [("毎日{まいにち}野菜{やさい}を食{た}べる[ようにしています]。", "I make sure to eat vegetables every day."), ("夜{よる}はコーヒーを飲{の}まない[ようにしている]。", "I try not to drink coffee at night.")], "surunaru"),
("koto-ni-suru", "V-ることにする", "decide to", "Dictionary form + ことにする = I decide to. ことにしている = it's my rule.",
 [("来年{らいねん}、日本{にほん}に留学{りゅうがく}する[ことにしました]。", "I've decided to study in Japan next year."), ("お酒{さけ}はやめる[ことにした]。", "I decided to quit drinking.")], "genericnouns"),
("koto-ni-naru", "V-ることになる", "it has been decided that", "ことになる = it's been decided (by others or circumstances). ことになっている = it's the rule.",
 [("来月{らいげつ}、大阪{おおさか}に転勤{てんきん}する[ことになりました]。", "It's been decided I'll transfer to Osaka next month."), ("ここではくつをぬぐ[ことになっている]。", "The rule here is to take off your shoes.")], "genericnouns"),
("nominalize", "V-るの / V-ること", "doing (as a noun)", "の or こと turns a verb into a noun: 泳ぐのが好き (I like swimming). こと is more formal; the senses (見る, 聞く) take の.",
 [("料理{りょうり}する[の]が好{す}きです。", "I like cooking."), ("趣味{しゅみ}は写真{しゃしん}をとる[こと]です。", "My hobby is taking photos.")], "genericnouns"),
("n-desu", "～んです / ～のだ", "explaining, the thing is", "のです / んです explains or asks for an explanation; it adds 'you see' or 'what's going on?'.",
 [("どうした[んですか]。", "What's the matter?"), ("頭{あたま}が痛{いた}い[んです]。", "It's that I have a headache.")], "particlesintro"),
("sou-looks", "～そう (looks)", "looks like, seems about to", "Stem / adjective stem + そう = looks (from appearance): おいしそう, 雨が降りそう. いい → よさそう, ない → なさそう.",
 [("このケーキ、おいし[そう]！", "This cake looks delicious!"), ("雨{あめ}が降{ふ}り[そう]です。", "It looks like it's about to rain.")], "similarity"),
("sou-hearsay", "～そうだ (hearsay)", "I heard that", "Plain form + そうだ = I heard / they say. Note the difference: 降るそうだ (I hear it'll rain) vs 降りそうだ (it looks like rain).",
 [("あしたは雨{あめ}が降{ふ}る[そうです]。", "I heard it'll rain tomorrow."), ("あの店{みせ}はおいしい[そうだ]。", "They say that place is good.")], "similarity"),
("you-da", "～ようだ / みたいだ", "seems, appears", "ようだ (formal) / みたいだ (casual) = it seems, based on what you see or infer. Also 'like': 夢のよう.",
 [("だれもいない[ようです]。", "It seems nobody is here."), ("ゆきさん、疲{つか}れている[みたい]。", "Yuki seems tired.")], "similarity"),
("rashii", "～らしい", "apparently; typical of", "らしい = apparently (from what I've heard or read). After a noun also 'typical of': 男らしい.",
 [("あの二人{ふたり}は結婚{けっこん}する[らしい]。", "Apparently those two are getting married."), ("今日{きょう}は春{はる}[らしい]天気{てんき}だ。", "Today is real spring weather.")], "similarity"),
("kamoshirenai", "～かもしれない", "might, maybe", "Plain form + かもしれない = might. Nouns and な-adjectives drop だ. Casual: かも.",
 [("あしたは雪{ゆき}[かもしれません]。", "It might snow tomorrow."), ("サムさんはもう帰{かえ}った[かも]。", "Sam might have gone home already.")], "certainty"),
("hazu", "～はずだ", "should (be), expected", "はずだ = I'm fairly sure based on reasons. はずがない = there's no way.",
 [("荷物{にもつ}はあした着{つ}く[はず]です。", "The package should arrive tomorrow."), ("そんな[はず]がない。", "That can't be.")], "certainty"),
("beki", "～べきだ", "should (duty)", "Dictionary form + べきだ = should, ought to (a moral judgment). する → すべき.",
 [("約束{やくそく}は守{まも}る[べき]だ。", "You should keep your promises."), ("もっと早{はや}く言{い}う[べき]だった。", "I should have said it sooner.")], "should"),
("passive", "V-られる (passive)", "is done (to)", "Passive: u → a + れる (読まれる), ru-verbs られる, される, 来られる. The doer takes に. Japanese also uses it for being bothered: 雨に降られた (I got rained on).",
 [("先生{せんせい}にほめ[られました]。", "I was praised by the teacher."), ("この本{ほん}は世界中{せかいじゅう}で読{よ}ま[れて]いる。", "This book is read all over the world.")], "causepass"),
("causative", "V-させる", "make / let someone do", "Causative: u → a + せる (行かせる), ru-verbs させる, させる (する), 来させる. Context decides 'make' or 'let'. させてください = please let me.",
 [("母{はは}は私{わたし}に野菜{やさい}を食{た}べ[させた]。", "My mom made me eat vegetables."), ("私{わたし}にやら[せて]ください。", "Please let me do it.")], "causepass"),
("causative-passive", "V-させられる", "be made to do", "Causative + passive = forced to do (unwillingly). u-verbs often shorten: 飲ませられる → 飲まされる.",
 [("子{こ}どものころ、ピアノを習{なら}わ[された]。", "As a kid I was made to take piano lessons."), ("先輩{せんぱい}にお酒{さけ}を飲{の}ま[された]。", "My senior made me drink.")], "causepass"),
("honorific", "尊敬語 (いらっしゃる, おっしゃる)", "honorific speech", "Raises the other person: special verbs いらっしゃる (be/go/come), おっしゃる (say), 召し上がる (eat), ご覧になる (see), or お + stem + になる.",
 [("社長{しゃちょう}は何{なん}と[おっしゃいました]か。", "What did the president say?"), ("どうぞ[召{め}し上{あ}がって]ください。", "Please, help yourself.")], "honorific"),
("humble", "謙譲語 (まいる, いたす)", "humble speech", "Lowers yourself: まいる (go/come), いたす (do), 申す (say), いただく (receive/eat), 拝見する (see), or お + stem + する.",
 [("山田{やまだ}と[申{もう}します]。", "My name is Yamada."), ("私{わたし}がお持{も}ち[します]。", "Let me carry that for you.")], "honorific"),
("ga-dekiru-place", "～ができる", "be able, be ready, get built", "できる also means 'be completed' or 'be built': ごはんができた (dinner's ready).",
 [("ごはんが[できた]よ。", "Dinner's ready!"), ("駅{えき}の前{まえ}に新{あたら}しい店{みせ}が[できました]。", "A new shop opened in front of the station.")], "potential"),
("shi", "～し、～し", "and also (reasons)", "し lists reasons or points: 'and what's more…'.",
 [("この店{みせ}は安{やす}い[し]、おいしいし、よく来{き}ます。", "This place is cheap and good, so I come often."), ("雨{あめ}だし、寒{さむ}い[し]、家{いえ}にいよう。", "It's raining and cold, let's stay home.")], "compound"),
("nai-de", "V-ないで", "without doing", "ない + で = without doing A, (do) B. Also 'instead of'.",
 [("朝{あさ}ごはんを食{た}べ[ないで]学校{がっこう}に行{い}った。", "I went to school without eating breakfast."), ("かさを持{も}た[ないで]出{で}かけた。", "I went out without an umbrella.")], "negativeverbs2"),
("zu-ni", "V-ずに", "without doing (written)", "ずに = ないで in writing and formal speech. する → せずに.",
 [("辞書{じしょ}を使{つか}わ[ずに]読{よ}みました。", "I read it without using a dictionary."), ("何{なに}も言{い}わ[ずに]帰{かえ}った。", "They left without saying anything.")], "negativeverbs2"),
("yasui-nikui", "V-やすい / V-にくい", "easy to / hard to", "Stem + やすい = easy to do; + にくい = hard to do. Both conjugate as い-adjectives.",
 [("このペンは書{か}き[やすい]です。", "This pen is easy to write with."), ("この漢字{かんじ}は覚{おぼ}え[にくい]。", "This kanji is hard to remember.")], "easyhard"),
("hajimeru-owaru", "V-始める / V-終わる", "start / finish doing", "Stem + 始める (begin), 終わる (finish), 続ける (keep doing), 出す (burst out).",
 [("雨{あめ}が降{ふ}り[始{はじ}めました]。", "It started to rain."), ("この本{ほん}、もう読{よ}み[終{お}わった]？", "Have you finished reading this book?")], "timeactions"),
("tokoro", "V-るところ / V-ているところ / V-たところ", "about to / in the middle of / just did", "ところ pins a moment: dictionary form = about to, ている = in the middle of, た = just did.",
 [("今{いま}、出{で}かける[ところ]です。", "I'm just about to head out."), ("今{いま}、帰{かえ}った[ところ]だ。", "I just got home.")], "genericnouns"),
("bakari", "V-たばかり", "just did (recently)", "Past た + ばかり = just did, it feels recent (could be days ago).",
 [("日本{にほん}に来{き}た[ばかり]です。", "I just came to Japan."), ("さっき食{た}べた[ばかり]なのに、もうおなかがすいた。", "I just ate, but I'm already hungry.")], "timeactions"),
("mama", "～まま", "as it is, unchanged", "まま = leaving a state unchanged: テレビをつけたまま寝た (fell asleep with the TV on).",
 [("くつをはいた[まま]入{はい}らないでください。", "Please don't come in with your shoes on."), ("窓{まど}を開{あ}けた[まま]出{で}かけた。", "I went out with the window left open.")], "nochange"),
("kata", "V-stem 方", "how to, way of", "Stem + 方 (かた) = the way of doing: 読み方 (how to read).",
 [("この漢字{かんじ}の読{よ}み[方{かた}]を教{おし}えてください。", "Please tell me how to read this kanji."), ("はしの使{つか}い[方{かた}]が上手{じょうず}ですね。", "You're good with chopsticks.")], "genericnouns"),
("ka-dou-ka", "～かどうか", "whether or not", "Embedded yes/no question: plain form + かどうか. With question words just か: いつ来るか.",
 [("おいしい[かどうか]わからない。", "I don't know if it's good."), ("何時{なんじ}に始{はじ}まる[か]知{し}っていますか。", "Do you know what time it starts?")], "question"),
("hoshii-te", "V-てほしい", "want someone to do", "て + ほしい = I want (someone) to do. The person takes に.",
 [("ゆきさんに来{き}[てほしい]。", "I want Yuki to come."), ("もっとゆっくり話{はな}し[てほしい]です。", "I'd like you to speak more slowly.")], "desire"),
("tagaru", "～たがる", "(someone else) wants to", "Use たがる for others' wants (you can't know their feelings directly): 行きたがっている.",
 [("子{こ}どもが外{そと}で遊{あそ}び[たがって]います。", "The kids want to play outside."), ("弟{おとうと}はゲームを買{か}い[たがって]いる。", "My little brother wants to buy a game.")], "signs"),
("garu", "～がる", "(others) show feelings", "Adjective stem + がる = shows signs of feeling: 寒がる, こわがる, ほしがる.",
 [("ねこが水{みず}をこわ[がって]います。", "The cat is scared of water."), ("サムさんはいつも寒{さむ}[がる]。", "Sam always acts cold.")], "signs"),
("hodo-nai", "A は B ほど～ない", "A is not as … as B", "ほど + negative = not as much as.",
 [("今日{きょう}はきのう[ほど]寒{さむ}くない。", "Today isn't as cold as yesterday."), ("日本語{にほんご}は思{おも}った[ほど]難{むずか}しくない。", "Japanese isn't as hard as I thought.")], "amount"),
("to-onaji", "～と同じ / ～と違う", "same as / different from", "AはBと同じ = A is the same as B; と違う = different from.",
 [("私{わたし}のかばんはゆきさんの[と同{おな}じ]です。", "My bag is the same as Yuki's."), ("日本{にほん}の朝{あさ}ごはんはアメリカの[と違{ちが}う]。", "Japanese breakfast is different from American.")], "comparison"),
("mitai-na", "N みたいな / のような", "like, such as", "Nみたいな N / Nのような N = something like N: 夢みたいな話.",
 [("夢{ゆめ}[みたいな]話{はなし}だね。", "Sounds like a dream."), ("ゆきさん[のような]人{ひと}になりたい。", "I want to be someone like Yuki.")], "similarity"),
("sa", "い-adj → さ", "-ness (noun from adjective)", "Adjective stem + さ = the degree of: 高さ (height), 大きさ (size), 便利さ.",
 [("この山{やま}の高{たか}[さ]はどのくらいですか。", "How tall is this mountain?"), ("大{おお}き[さ]が違{ちが}う。", "The size is different.")], "amount"),
("ka-na", "～かな", "I wonder", "かな (casual) / かしら (feminine) = I wonder. Adds a soft guess or request: 手伝ってくれるかな?",
 [("あしたは晴{は}れる[かな]。", "I wonder if it'll be sunny tomorrow."), ("これでいい[かな]？", "Is this okay, I wonder?")], "adverbs"),
("ga-suru", "～がする", "there is (a smell, sound, taste)", "においがする, 音がする, 味がする, 気がする (I have a feeling).",
 [("いいにおい[がします]ね。", "Something smells good."), ("だれか来{き}た気{き}[がする]。", "I feel like someone came.")], "surunaru"),
("ni-suru-decide", "N にする / い-adj くする", "make (it) / decide", "Nにする = make into / choose; adjective くする = make it more…: 部屋をきれいにする, 音を小さくする.",
 [("音{おと}を小{ちい}さ[く]してください。", "Please turn the volume down."), ("部屋{へや}をきれい[に]しました。", "I tidied up the room.")], "surunaru"),
("demo", "N でも", "… or something; even", "でも after a noun = 'or something' (お茶でも飲みませんか) or 'even'. Question word + でも = any-: だれでも, いつでも.",
 [("お茶{ちゃ}[でも]飲{の}みませんか。", "How about some tea or something?"), ("[いつでも]来{き}てください。", "Come any time.")], "even"),
("mo-amount", "number + も", "as many as", "も after an amount stresses that it's a lot: 三時間も (a whole three hours).",
 [("三時間{さんじかん}[も]待{ま}ちました。", "I waited a whole three hours."), ("ケーキを五{いつ}つ[も]食{た}べた。", "I ate as many as five cakes.")], "amount"),
("kurai", "～くらい / ぐらい", "about, approximately", "くらい / ぐらい = about (an amount), or 'to the extent that'.",
 [("駅{えき}まで十分{じゅっぷん}[ぐらい]です。", "It's about ten minutes to the station."), ("泣{な}きたい[くらい]うれしい。", "I'm so happy I could cry.")], "amount"),
("made-ni", "～までに", "by (a deadline)", "までに = by (no later than); まで = until (continuously).",
 [("金曜日{きんようび}[までに]出{だ}してください。", "Please submit it by Friday."), ("五時{ごじ}[まで]働{はたら}きます。", "I work until five.")], "verbparticles"),
("aida", "～間 / ～間に", "while, during", "間 (あいだ) = throughout a period; 間に = at some point during it.",
 [("夏休{なつやす}みの[間{あいだ}]、ずっと国{くに}にいました。", "I was home the whole summer vacation."), ("寝{ね}ている[間{あいだ}に]雪{ゆき}が降{ふ}った。", "It snowed while I was asleep.")], "timeactions"),
("uchi-ni", "～うちに", "while (still), before it changes", "うちに = while the state lasts: 熱いうちに食べて (eat it while it's hot); ないうちに = before.",
 [("熱{あつ}い[うちに]食{た}べてください。", "Eat it while it's hot."), ("暗{くら}くならない[うちに]帰{かえ}ろう。", "Let's go home before it gets dark.")], "timeactions"),
]
