# JLPT N3 grammar (format: see grammar_n5.py). Concepts follow Tae Kim's guide; explanations and examples are our own.
POINTS = [
("ba-yokatta", "～ばよかった", "I should have", "ば + よかった = regret: if only I had. Negative: なければよかった.",
 [("もっと早{はや}く出{で}れ[ばよかった]。", "I should have left earlier."), ("あんなこと言{い}わなけれ[ばよかった]。", "I wish I hadn't said that.")], "conditionals"),
("ba-hodo", "～ば～ほど", "the more … the more", "Repeat the verb/adjective: ば-form + dictionary form + ほど.",
 [("練習{れんしゅう}すれ[ば]するほど上手{じょうず}になる。", "The more you practice, the better you get."), ("考{かんが}えれば考{かんが}える[ほど]わからなくなる。", "The more I think, the less I understand.")], "amount"),
("tatoe-temo", "たとえ～ても", "even if", "て + も = even if; たとえ adds emphasis. Nouns: でも.",
 [("雨{あめ}が降{ふ}っ[ても]行{い}きます。", "Even if it rains, I'll go."), ("たとえ高{たか}く[ても]買{か}いたい。", "Even if it's expensive, I want to buy it.")], "conditionals"),
("te-mo-kamawanai", "～てもかまわない", "don't mind if", "てもかまわない = it's no problem if (more formal than てもいい).",
 [("ここに座{すわ}っ[てもかまいません]か。", "Do you mind if I sit here?"), ("遅{おそ}くなっ[てもかまわない]。", "It's fine if you're late.")], "must"),
("zaru-wo-enai", "V-ざるを得ない", "have no choice but to", "ない stem + ざるを得ない (える) = can't help but, forced by circumstances. する → せざるを得ない.",
 [("雨{あめ}なので、中止{ちゅうし}せ[ざるを得{え}ない]。", "Because of the rain, we have no choice but to cancel."), ("仕事{しごと}だから行{い}か[ざるを得{え}ない]。", "It's work, so I have to go.")], "must"),
("shika-nai-v", "V-るしかない", "the only thing to do is", "Dictionary form + しかない = there's no other option.",
 [("終電{しゅうでん}がないから、歩{ある}く[しかない]。", "The last train's gone, so we can only walk."), ("やる[しかない]！", "Nothing to do but go for it!")], "amount"),
("wake", "～わけだ", "no wonder, that means", "わけだ = so that's why / it follows that.",
 [("十年{じゅうねん}も住{す}んでいたなら、日本語{にほんご}が上手{じょうず}な[わけだ]。", "If you lived there ten years, no wonder your Japanese is good."), ("だから寒{さむ}い[わけだ]。窓{まど}が開{あ}いている。", "So that's why it's cold. The window's open.")], "reasoning"),
("wake-ga-nai", "～わけがない", "there's no way", "わけがない = it's impossible that.",
 [("そんなに安{やす}い[わけがない]。", "There's no way it's that cheap."), ("あのサムさんが忘{わす}れる[わけがない]。", "There's no way Sam would forget.")], "reasoning"),
("wake-dewanai", "～わけではない", "it doesn't mean that", "わけではない = not necessarily; softens a denial.",
 [("きらいな[わけではない]けど、あまり食{た}べない。", "It's not that I dislike it, I just don't eat it much."), ("全部{ぜんぶ}わかる[わけではない]。", "It's not that I understand everything.")], "reasoning"),
("wake-niwa-ikanai", "～わけにはいかない", "can't (for social reasons)", "Dictionary form + わけにはいかない = I can't, it wouldn't be right.",
 [("約束{やくそく}したから、行{い}かない[わけにはいかない]。", "I promised, so I can't not go."), ("仕事{しごと}中{ちゅう}にお酒{さけ}を飲{の}む[わけにはいかない]。", "I can't drink at work.")], "reasoning"),
("ni-chigainai", "～に違いない", "must be, surely", "に違いない = I'm certain (from evidence).",
 [("あの人{ひと}は先生{せんせい}[に違{ちが}いない]。", "That person must be a teacher."), ("ゆきさんは疲{つか}れている[に違{ちが}いない]。", "Yuki must be tired.")], "certainty"),
("kamoshirenai-darou", "～だろう / ～だろうと思う", "I suppose", "だろうと思う = I suppose, a guess with some reasoning.",
 [("試験{しけん}は難{むずか}しい[だろうと思{おも}う]。", "I suppose the exam will be hard."), ("彼{かれ}はもう着{つ}いた[だろう]。", "He's probably arrived already.")], "certainty"),
("ppoi", "～っぽい", "-ish, kind of like", "っぽい = has the feel of, tends to: 子どもっぽい (childish), 忘れっぽい (forgetful).",
 [("このかばん、安{やす}[っぽい]ね。", "This bag looks cheap."), ("最近{さいきん}、忘{わす}れ[っぽい]。", "I've been forgetful lately.")], "similarity"),
("gachi", "～がち", "tend to (bad)", "Stem / noun + がち = tends to (usually something undesirable): 遅れがち, 病気がち.",
 [("冬{ふゆ}は家{いえ}にこもり[がち]だ。", "In winter I tend to stay indoors."), ("あのバスは遅{おく}れ[がち]です。", "That bus tends to be late.")], "tendency"),
("gimi", "～気味", "a touch of, slightly", "Stem / noun + 気味 (ぎみ) = slightly, a bit: かぜ気味 (a bit of a cold).",
 [("かぜ[気味{ぎみ}]なので、早{はや}く寝{ね}ます。", "I have a slight cold, so I'll sleep early."), ("最近{さいきん}、太{ふと}り[気味{ぎみ}]だ。", "I've been putting on a bit of weight.")], "tendency"),
("darake", "～だらけ", "covered in, full of (bad)", "Noun + だらけ = full of something unwanted: まちがいだらけ.",
 [("この作文{さくぶん}はまちがい[だらけ]だ。", "This essay is full of mistakes."), ("くつがどろ[だらけ]になった。", "My shoes got all muddy.")], "covered"),
("tsuide-ni", "～ついでに", "while (doing), on the way", "ついでに = do B taking the chance while doing A.",
 [("買{か}い物{もの}の[ついでに]、本屋{ほんや}に寄{よ}った。", "While shopping, I stopped by the bookstore."), ("出{で}かける[ついでに]手紙{てがみ}を出{だ}してくれる？", "Could you mail this letter while you're out?")], "other"),
("tabi-ni", "～たびに", "every time", "Dictionary form / N の + たびに = every time.",
 [("この歌{うた}を聞{き}く[たびに]、夏{なつ}を思{おも}い出{だ}す。", "Every time I hear this song, I remember summer."), ("旅行{りょこう}の[たびに]写真{しゃしん}をとる。", "I take photos every trip.")], "timeactions"),
("totan", "V-たとたん", "the moment, as soon as", "Past た + とたん(に) = the instant A happened, B (unexpected) happened.",
 [("立{た}ち上{あ}がった[とたん]、めまいがした。", "The moment I stood up, I got dizzy."), ("ドアを開{あ}けた[とたん]、ねこが飛{と}び出{だ}した。", "As soon as I opened the door, the cat jumped out.")], "timeactions"),
("shidai", "V-stem 次第", "as soon as (then I'll)", "Stem + 次第 (しだい) = as soon as A, B (polite, for plans).",
 [("着{つ}き[次第{しだい}]、ご連絡{れんらく}します。", "I'll contact you as soon as I arrive."), ("準備{じゅんび}ができ[次第{しだい}]、始{はじ}めます。", "We'll start as soon as we're ready.")], "immedate"),
("uchi-ni-change", "V-ているうちに", "while (and before I knew it)", "ているうちに = while doing A, B happened gradually.",
 [("話{はな}している[うちに]、仲{なか}よくなった。", "While we talked, we became friends."), ("本{ほん}を読{よ}んでいる[うちに]寝{ね}てしまった。", "I fell asleep while reading.")], "timeactions"),
("ni-tsurete", "～につれて", "as (one changes, so does the other)", "Dictionary form / N + につれて = as A changes, B changes too.",
 [("年{とし}をとる[につれて]、時間{じかん}が早{はや}く感{かん}じる。", "As you get older, time feels faster."), ("日本語{にほんご}が上手{じょうず}になる[につれて]、楽{たの}しくなった。", "As my Japanese improved, it got more fun.")], "timeactions"),
("ni-yotte", "～によって", "by, depending on, due to", "によって = by (an agent, in passive), depending on, or because of.",
 [("人{ひと}[によって]考{かんが}え方{かた}が違{ちが}う。", "Ways of thinking differ from person to person."), ("この寺{てら}は有名{ゆうめい}な大工{だいく}[によって]建{た}てられた。", "This temple was built by a famous carpenter.")], "causepass"),
("ni-yoru-to", "～によると", "according to", "によると / によれば = according to (source), often with そうだ.",
 [("天気予報{てんきよほう}[によると]、あしたは晴{は}れるそうだ。", "According to the forecast, it'll be sunny tomorrow."), ("ニュース[によれば]、事故{じこ}があったらしい。", "According to the news, there was an accident.")], "similarity"),
("ni-tsuite", "～について", "about, concerning", "について = about (a topic). Before a noun: についての.",
 [("日本{にほん}の文化{ぶんか}[について]調{しら}べています。", "I'm researching Japanese culture."), ("この問題{もんだい}[について]どう思{おも}いますか。", "What do you think about this problem?")], "other"),
("ni-taishite", "～に対して", "toward; in contrast to", "に対して = toward someone/something, or in contrast.",
 [("お客{きゃく}さん[に対{たい}して]ていねいに話{はな}す。", "Speak politely to customers."), ("兄{あに}は背{せ}が高{たか}いの[に対{たい}して]、弟{おとうと}は低{ひく}い。", "The older brother is tall, while the younger is short.")], "other"),
("ni-totte", "～にとって", "for (from the viewpoint of)", "にとって = for someone, as they see it.",
 [("私{わたし}[にとって]、家族{かぞく}が一番{いちばん}大切{たいせつ}だ。", "For me, family matters most."), ("学生{がくせい}[にとって]、この本{ほん}は高{たか}すぎる。", "For students, this book is too expensive.")], "other"),
("toshite", "～として", "as (a role)", "として = in the role or capacity of.",
 [("通訳{つうやく}[として]働{はたら}いています。", "I work as an interpreter."), ("趣味{しゅみ}[として]写真{しゃしん}をとっている。", "I take photos as a hobby.")], "other"),
("ni-kuraberu", "～に比べて", "compared to", "に比べて (くらべて) = compared with.",
 [("去年{きょねん}[に比{くら}べて]、今年{ことし}は暑{あつ}い。", "Compared to last year, this year is hot."), ("東京{とうきょう}[に比{くら}べると]、ここは静{しず}かだ。", "Compared to Tokyo, it's quiet here.")], "comparison"),
("bakari-de-naku", "～ばかりでなく / だけでなく", "not only … but also", "だけでなく / ばかりでなく A も = not only but also.",
 [("英語{えいご}[だけでなく]、日本語{にほんご}も話{はな}せる。", "I can speak not only English but also Japanese."), ("値段{ねだん}が安{やす}い[ばかりでなく]、味{あじ}もいい。", "It's not only cheap but tasty too.")], "amount"),
("bakari-only", "～ばかり", "nothing but", "ばかり = nothing but, only (too much of one thing). て-form + ばかりいる = do nothing but.",
 [("弟{おとうと}はゲーム[ばかり]している。", "My little brother does nothing but play games."), ("肉{にく}[ばかり]食{た}べないで。", "Don't eat only meat.")], "amount"),
("sae", "～さえ", "even; if only", "さえ = even (surprising extreme). さえ～ば = if only: 時間さえあれば.",
 [("ひらがな[さえ]読{よ}めない。", "I can't even read hiragana."), ("時間{じかん}[さえ]あれば、行{い}けるのに。", "If only I had time, I could go.")], "even"),
("koso", "～こそ", "precisely, (this) very", "こそ emphasizes: 今年こそ = this year for sure; こちらこそ = it's I who (should thank you).",
 [("今年{ことし}[こそ]日本{にほん}に行{い}きたい。", "This year for sure, I want to go to Japan."), ("こちら[こそ]よろしくお願{ねが}いします。", "The pleasure is mine.")], "even"),
("nanka", "～なんか / ～なんて", "things like (dismissive)", "なんか / なんて = something like, with a light, dismissive or surprised tone.",
 [("私{わたし}[なんか]まだまだです。", "Someone like me still has a long way to go."), ("サムさんが料理{りょうり}する[なんて]、びっくり！", "Sam cooking? What a surprise!")], "slang"),
("tte-iu-ka", "～というか", "or rather", "というか / っていうか corrects or rephrases.",
 [("きれい[というか]、かわいい感{かん}じだね。", "It's more cute than pretty."), ("[っていうか]、もう遅{おそ}いよ。", "I mean, it's already late.")], "slang"),
("to-iu-koto-wa", "～ということは", "which means", "ということは = so that means.",
 [("電気{でんき}がついていない。[ということは]、留守{るす}だ。", "The lights are off. That means nobody's home."), ("満席{まんせき}[ということは]、次{つぎ}の電車{でんしゃ}を待{ま}つしかない。", "Full means we have to wait for the next train.")], "define"),
("koto-da", "～ことだ", "you should (advice)", "Dictionary form + ことだ = the best thing is to (advice).",
 [("上手{じょうず}になりたければ、毎日{まいにち}練習{れんしゅう}する[ことだ]。", "If you want to get good, practice every day."), ("無理{むり}をしない[ことだ]。", "Don't push yourself.")], "genericnouns"),
("mono-da", "～ものだ", "used to; that's how it is", "た + ものだ = used to (nostalgic); dictionary form + ものだ = that's the nature of things.",
 [("子{こ}どものころ、よくこの川{かわ}で泳{およ}いだ[ものだ]。", "As a kid I'd often swim in this river."), ("時間{じかん}がたつのは早{はや}い[ものだ]。", "Time sure flies.")], "genericnouns"),
("mono-nara", "～ものなら", "if (it were possible)", "Potential + ものなら = if I could (unlikely).",
 [("できる[ものなら]、もう一度{いちど}若{わか}くなりたい。", "If only I could, I'd be young again."), ("行{い}ける[ものなら]行{い}きたい。", "I'd go if I possibly could.")], "conditionals"),
("tsumori-de", "～たつもり", "thought I had", "た + つもり = I thought I did (but maybe not).",
 [("かぎをかけた[つもり]だった。", "I thought I'd locked it."), ("説明{せつめい}した[つもり]ですが、わかりましたか。", "I meant to explain it; did it make sense?")], "desire"),
("you-ni-iu", "～ように言う", "tell someone to", "Dictionary/ない form + ように言う (頼む, 注意する) = tell (ask, warn) someone to do.",
 [("医者{いしゃ}にお酒{さけ}を飲{の}まない[ように言{い}われた]。", "The doctor told me not to drink."), ("ゆきさんに来{く}る[ように]伝{つた}えてください。", "Please tell Yuki to come.")], "requests"),
("you-ni-wish", "～ますように", "I hope, may", "ますように = a wish or prayer.",
 [("合格{ごうかく}でき[ますように]。", "I hope I pass."), ("いい一年{いちねん}になり[ますように]。", "May it be a good year.")], "desire"),
("ou-to-omou-ga", "～ようとしない", "won't (refuses to)", "Volitional + としない = won't even try to.",
 [("弟{おとうと}は野菜{やさい}を食{た}べよう[としない]。", "My brother refuses to eat vegetables."), ("だれも手伝{てつだ}おう[としなかった]。", "Nobody would help.")], "try"),
("kakeru", "V-stem かける", "half-done, about to", "Stem + かけ(る) = started but not finished: 読みかけの本 (a half-read book).",
 [("食{た}べ[かけ]のパンがある。", "There's a half-eaten piece of bread."), ("何{なに}か言{い}い[かけて]やめた。", "They started to say something and stopped.")], "timeactions"),
("kiru", "V-stem きる", "do completely", "Stem + きる = do all the way: 使いきる (use up), 読みきる; きれない = can't finish.",
 [("一日{いちにち}で本{ほん}を読{よ}み[きった]。", "I read the whole book in one day."), ("こんなに食{た}べ[きれない]よ。", "I can't eat all this.")], "amount"),
("tsuzukeru", "V-stem 続ける", "keep doing", "Stem + 続ける = continue doing.",
 [("三時間{さんじかん}歩{ある}き[続{つづ}けた]。", "We kept walking for three hours."), ("日本語{にほんご}を勉強{べんきょう}し[続{つづ}けたい]。", "I want to keep studying Japanese.")], "timeactions"),
("dasu", "V-stem 出す", "suddenly start", "Stem + 出す = burst into, start suddenly: 泣き出す, 降り出す.",
 [("赤{あか}ちゃんが急{きゅう}に泣{な}き[出{だ}した]。", "The baby suddenly burst into tears."), ("雨{あめ}が降{ふ}り[出{だ}した]。", "It started raining.")], "timeactions"),
("naosu", "V-stem 直す", "redo", "Stem + 直す = do over, correct: 書き直す.",
 [("作文{さくぶん}を書{か}き[直{なお}した]。", "I rewrote the essay."), ("もう一度{いちど}考{かんが}え[直{なお}して]ください。", "Please reconsider.")], "other"),
("au", "V-stem 合う", "each other", "Stem + 合う = do to each other: 話し合う (discuss), 助け合う.",
 [("みんなで話{はな}し[合{あ}いましょう]。", "Let's talk it over together."), ("家族{かぞく}で助{たす}け[合{あ}う]。", "We help each other as a family.")], "other"),
("sasete-itadaku", "～させていただく", "allow me to (humble)", "Causative + ていただく = humbly do something (with permission).",
 [("本日{ほんじつ}は休{やす}ま[せていただきます]。", "We'll be closed today."), ("説明{せつめい}さ[せていただきます]。", "Allow me to explain.")], "honorific"),
("o-ni-naru", "お～になる / お～する", "honorific / humble patterns", "お + stem + になる raises the other person (お待ちになる); お + stem + する lowers yourself (お待ちする). お～ください = please (honorific).",
 [("社長{しゃちょう}はもうお帰{かえ}り[になりました]。", "The president has already gone home."), ("少々{しょうしょう}お待{ま}ち[ください]。", "Please wait a moment.")], "honorific"),
("teineigo", "ございます / でございます", "very polite is/have", "ございます = あります (very polite); でございます = です in service speech.",
 [("トイレはあちら[でございます]。", "The restroom is over there."), ("ご質問{しつもん}は[ございます]か。", "Do you have any questions?")], "honorific"),
("rareru-honorific", "V-られる (honorific)", "respectful verb", "The passive form also works as a light honorific: 先生が来られました (the teacher came).",
 [("先生{せんせい}は何時{なんじ}に来{こ}[られます]か。", "What time will the teacher come?"), ("社長{しゃちょう}が話{はな}さ[れた]。", "The president spoke.")], "honorific"),
("ppanashi", "～っぱなし", "leave on, keep (bad)", "Stem + っぱなし = left in a state (carelessly): 開けっぱなし.",
 [("電気{でんき}がつけ[っぱなし]だよ。", "You left the lights on."), ("一日中{いちにちじゅう}立{た}ち[っぱなし]で疲{つか}れた。", "I'm tired from standing all day.")], "nochange"),
("hazu-datta", "～はずだった", "was supposed to", "はずだった = it was supposed to (but didn't).",
 [("電車{でんしゃ}は九時{くじ}に着{つ}く[はずだった]。", "The train was supposed to arrive at nine."), ("こんな[はずじゃなかった]。", "This isn't how it was supposed to go.")], "certainty"),
("you-ni-mieru", "～ように見える", "looks as if", "ように見える = appears to be (visually).",
 [("ゆきさんは楽{たの}しそう[に見{み}える]。", "Yuki looks like she's having fun."), ("この絵{え}は写真{しゃしん}の[ように見{み}える]。", "This painting looks like a photo.")], "similarity"),
("ka-to-omou", "～かと思うと / かと思ったら", "just when I thought", "た + かと思ったら = no sooner had A happened than B (surprising).",
 [("晴{は}れた[かと思{おも}ったら]、また雨{あめ}だ。", "Just when it cleared up, it's raining again."), ("帰{かえ}ってきた[かと思{おも}うと]、すぐ出{で}かけた。", "No sooner did they get home than they went out.")], "immedate"),
("ni-kagiru", "～に限る", "nothing beats", "に限る = X is the best (for this).",
 [("暑{あつ}い日{ひ}はビール[に限{かぎ}る]。", "On a hot day, nothing beats a beer."), ("疲{つか}れたときは寝{ね}る[に限{かぎ}る]。", "When you're tired, sleep is best.")], "comparison"),
("okage-sei", "～おかげで / ～せいで", "thanks to / because of (blame)", "おかげで = thanks to (good result); せいで = due to (bad result, blame).",
 [("先生{せんせい}の[おかげで]合格{ごうかく}できた。", "Thanks to my teacher, I passed."), ("雨{あめ}の[せいで]試合{しあい}が中止{ちゅうし}になった。", "The game was canceled because of the rain.")], "reasoning"),
("kara-koso", "～からこそ", "precisely because", "からこそ = it's exactly because of this.",
 [("好{す}きだ[からこそ]、きびしく言{い}うんだ。", "It's precisely because I care that I'm strict."), ("大変{たいへん}だった[からこそ]、うれしい。", "Because it was hard, I'm all the happier.")], "reasoning"),
("mai", "V-まい", "will not, surely won't", "Dictionary form + まい = won't (resolution) / probably won't (written).",
 [("もう二度{にど}とうそはつく[まい]。", "I'll never lie again."), ("彼{かれ}は来{く}る[まい]。", "He probably won't come.")], "volitional2"),
("ta-mono-no", "～ものの", "although", "ものの = although (written). Something happened, but the result isn't as expected.",
 [("買{か}った[ものの]、まだ使{つか}っていない。", "I bought it, but I haven't used it yet."), ("約束{やくそく}した[ものの]、行{い}けそうにない。", "I promised, but it looks like I can't go.")], "other"),
("ni-shitewa", "～にしては", "for (considering)", "にしては = considering it's X, surprisingly…",
 [("初{はじ}めて[にしては]上手{じょうず}ですね。", "That's good for a first time."), ("十二月{じゅうにがつ}[にしては]暖{あたた}かい。", "It's warm for December.")], "comparison"),
("toori", "～とおり(に)", "as, just like", "とおり = exactly as: 言ったとおり, 説明のとおりに.",
 [("先生{せんせい}が言{い}った[とおりに]やってください。", "Do it exactly as the teacher said."), ("思{おも}った[とおり]、雨{あめ}が降{ふ}ってきた。", "Just as I thought, it started raining.")], "similarity"),
("tame-reason", "～ため(に) (reason)", "because of (formal)", "ため(に) after a past/noun can mean 'because of' in formal writing.",
 [("事故{じこ}の[ため]、電車{でんしゃ}が遅{おく}れています。", "The train is delayed due to an accident."), ("大雪{おおゆき}の[ため]、休校{きゅうこう}です。", "School is closed because of heavy snow.")], "reasoning"),
("ni-mo-kakawarazu", "～にもかかわらず", "despite", "にもかかわらず = in spite of (formal のに).",
 [("雨{あめ}[にもかかわらず]、多{おお}くの人{ひと}が来{き}た。", "Despite the rain, many people came."), ("注意{ちゅうい}した[にもかかわらず]、また遅刻{ちこく}した。", "Despite the warning, they were late again.")], "other"),
("kawari-ni", "～かわりに", "instead of; in exchange", "かわりに = instead of, or in return for.",
 [("母{はは}の[かわりに]、私{わたし}が行{い}きます。", "I'll go instead of my mom."), ("英語{えいご}を教{おし}える[かわりに]、日本語{にほんご}を教{おし}えてもらう。", "In exchange for teaching English, I get taught Japanese.")], "other"),
("sei-ka", "～せいか", "maybe because", "せいか = perhaps because (unsure cause).",
 [("寝{ね}不足{ぶそく}の[せいか]、頭{あたま}が痛{いた}い。", "Maybe from lack of sleep, I have a headache."), ("年{とし}の[せいか]、疲{つか}れやすい。", "Maybe it's age, but I tire easily.")], "reasoning"),
("ni-oite", "～において / ～における", "in, at (formal)", "において = で in formal writing: 会議において.",
 [("会議{かいぎ}は東京{とうきょう}[において]行{おこな}われる。", "The conference will be held in Tokyo."), ("日本{にほん}[における]英語{えいご}教育{きょういく}", "English education in Japan")], "formal"),
("de-aru", "～である", "is (written)", "である is the written, essay-style だ.",
 [("東京{とうきょう}は日本{にほん}の首都{しゅと}[である]。", "Tokyo is the capital of Japan."), ("これは大切{たいせつ}な問題{もんだい}[である]。", "This is an important problem.")], "formal"),
]
