# JLPT N3 units: Sam's trip through Japan with Yuki (Tokyo → Kyoto → Osaka → Hakone → home).
# Notation: see build.py. Kanji: (kanji, on, kun, meaning, [(word, reading, gloss)]).
# Grammar ids match data/grammar.json, so each point links to its full lesson.

UNITS = [
{
 "id": "n3-01", "level": "N3", "unit": 1,
 "title": {"ja": "もっと寝ればよかった", "en": "I should have slept more"},
 "scene": "The morning after Sam lands in Tokyo. Yuki meets him at Kaminarimon in Asakusa. Sam barely slept.",
 "lines": [
  "ゆき: おはよう=good morning|！|サム=Sam|、|顔{かお}=face|^が=(subject)|疲{つか}れている=tired|みたい=looks like|。|大丈夫{だいじょうぶ}=okay|？ >> Morning! Sam, you look tired. Are you okay?",
  "サム: 時差{じさ}ぼけ=jet lag|で=because of|、|ぜんぜん=at all|眠{ねむ}れなかった=couldn't sleep|んだ=(you see)|。 >> I couldn't sleep at all because of jet lag.",
  "サム: 飛行機{ひこうき}=airplane|^で=on|寝{ね}ればよかった=should have slept|。 >> I should have slept on the plane.",
  "ゆき: 十四時間{じゅうよじかん}=fourteen hours|も=as many as|映画{えいが}=movies|^を=(object)|見ていた{みていた}=were watching|んでしょう=right?|？|眠{ねむ}い=sleepy|わけだ=no wonder|よ=(you know)|。 >> You watched movies for fourteen hours, right? No wonder you're sleepy.",
  "サム: それに=besides|、|ちょっと=a little|風邪気味{かぜぎみ}=coming down with a cold|なんだ=(it's that)|。 >> Plus I think I'm coming down with a cold.",
  "ゆき: じゃあ=then|、|今日{きょう}=today|^は=topic|あまり=not much|歩{ある}かないで=without walking|、|ゆっくり=slowly|見よう{みよう}=let's look around|。 >> Then let's not walk too much today and take it slow.",
  "ブリップ: 見て{みて}=look|！|あの=that|大{おお}きい=big|赤{あか}い=red|ちょうちん=lantern|、|写真{しゃしん}=photos|^で=in|見た{みた}=saw|^の=(one)|^と=as|同{おな}じ=same|だ=is|！ >> Look! That big red lantern is the same as the one in the photos!",
  "サム: 子{こ}どもっぽい=childish|けど=but|、|ブリップ=Blip|^を=(object)|頭{あたま}=head|^の=(of)|上{うえ}=top|^に=on|乗{の}せよう=I'll put|かな=maybe|。 >> It's childish, but maybe I'll put Blip on my head.",
  "ゆき: 人{ひと}=people|^が=(subject)|多{おお}い=many|から=so|、|迷子{まいご}=lost|^に=(become)|ならないで=don't become|ね=okay|。 >> There are lots of people, so don't get lost.",
  "サム: 迷子{まいご}=lost|^に=(become)|なったら=if I get|、|ブリップ=Blip|^が=(subject)|道{みち}=the way|^を=(object)|教{おし}えてくれる=will show me|よ=(you know)|。 >> If I get lost, Blip will show me the way.",
 ],
 "grammar": [
  {"id": "ba-yokatta", "title": "～ばよかった: I should have",
   "explain": "ば-form + よかった looks back with regret: 'if only I had'. 寝る → 寝れば → 寝ればよかった. The negative regrets something you did: 言わなければよかった (I shouldn't have said it).",
   "examples": [("飛行機{ひこうき}=plane|^で=on|寝{ね}ればよかった=should have slept|。", "I should have slept on the plane."), ("あんなに=that much|食{た}べなければよかった=shouldn't have eaten|。", "I shouldn't have eaten so much.")],
   "quiz": [{"q": "もっと早く寝＿＿＿＿＿。", "hint": "I should have gone to bed earlier.", "choices": ["ればよかった", "たらいい", "てもいい"], "answer": 0, "why": "Regret about the past: ～ばよかった."},
            {"q": "あんなこと言わ＿＿＿よかった。", "hint": "I shouldn't have said that.", "choices": ["なければ", "ないで", "なくて"], "answer": 0, "why": "The ば-form of 言わない is 言わなければ."}]},
  {"id": "wake", "title": "～わけだ: no wonder, that's why",
   "explain": "Plain form + わけだ draws the conclusion from a reason you just heard: 14 hours of movies → 眠いわけだ (no wonder you're sleepy). After a noun or な-adjective use なわけだ.",
   "examples": [("映画{えいが}=movies|^を=(object)|見ていた{みていた}=were watching|^の=(it's that)|？|眠{ねむ}い=sleepy|わけだ=no wonder|。", "You were watching movies? No wonder you're sleepy.")],
   "quiz": [{"q": "十四時間も映画を見ていたの？眠い＿＿＿だ。", "hint": "You watched movies for 14 hours? No wonder you're sleepy.", "choices": ["わけ", "はず", "ため"], "answer": 0, "why": "わけだ: the result makes sense now. はずだ is what you expect beforehand."}]},
  {"id": "gimi", "title": "～気味 / ～っぽい: a touch of, -ish",
   "explain": "気味 (ぎみ) after a noun or verb stem = a slight, usually unwanted condition: 風邪気味 (a bit of a cold), 疲れ気味 (a bit tired). っぽい = -ish, a trait or look: 子どもっぽい (childish), 忘れっぽい (forgetful).",
   "examples": [("ちょっと=a little|風邪気味{かぜぎみ}=a touch of a cold|です=is|。", "I've got a touch of a cold."), ("子{こ}どもっぽい=childish|けど=but|、|楽{たの}しい=fun|。", "It's childish, but fun.")],
   "quiz": [{"q": "最近、ちょっと疲れ＿＿＿だ。", "hint": "Lately I'm a bit tired.", "choices": ["気味", "っぽい", "らしい"], "answer": 0, "why": "A slight unwanted condition: 気味."},
            {"q": "ブリップは忘れ＿＿＿。", "hint": "Blip is forgetful.", "choices": ["っぽい", "気味", "すぎ"], "answer": 0, "why": "A trait: 忘れっぽい."}]},
 ],
 "kanji": [
  ("顔", "ガン", "かお", "face", [("顔", "かお", "face"), ("笑顔", "えがお", "smile")]),
  ("疲", "ヒ", "つか.れる", "tired", [("疲れる", "つかれる", "to get tired")]),
  ("眠", "ミン", "ねむ.い,ねむ.る", "sleep", [("眠い", "ねむい", "sleepy"), ("眠る", "ねむる", "to sleep")]),
  ("寝", "シン", "ね.る", "lie down, sleep", [("寝る", "ねる", "to go to bed")]),
  ("頭", "トウ,ズ", "あたま", "head", [("頭", "あたま", "head"), ("頭痛", "ずつう", "headache")]),
 ],
 "build": [2, 4],
 "questions": [
  {"q": "サムさんはどうして眠れなかったのですか。", "en": "Why couldn't Sam sleep?", "choices": ["時差ぼけで", "ホテルがうるさくて", "映画がこわくて"], "answer": 0},
  {"q": "サムさんは飛行機で何をしていましたか。", "en": "What did Sam do on the plane?", "choices": ["映画を見ていた", "ずっと寝ていた", "漢字を勉強していた"], "answer": 0},
  {"q": "迷子になったら、だれが道を教えてくれますか。", "en": "If Sam gets lost, who will show him the way?", "choices": ["ブリップ", "ゆきさん", "駅の人"], "answer": 0},
 ],
 "talk": "Tell Blip something you should have done differently this week (～ばよかった), then react to a fact Blip tells you with ～わけだ.",
},
{
 "id": "n3-02", "level": "N3", "unit": 2,
 "title": {"ja": "納豆さえ食べられる", "en": "I can even eat natto"},
 "scene": "Tsukiji Outer Market. Yuki wants Sam to try everything; Sam has a list of foods he's afraid of.",
 "lines": [
  "ゆき: ここ=here|^は=topic|魚{さかな}=fish|ばかりでなく=not only|、|卵焼{たまごや}き=rolled omelet|^や=and|果物{くだもの}=fruit|^も=also|有名{ゆうめい}=famous|なんだ=(it's that)|。 >> This place is famous not only for fish but for rolled omelets and fruit too.",
  "サム: 朝{あさ}=morning|^から=from|こんなに=this many|人{ひと}=people|^が=(subject)|並{なら}んでいる=lining up|！ >> So many people lining up since morning!",
  "ゆき: 観光客{かんこうきゃく}=tourists|^に=(for)|とって=for|、|ここ=here|^は=topic|朝{あさ}ごはん=breakfast|^に=(for)|一番{いちばん}=the best|いい=good|場所{ばしょ}=place|だ=is|^と=(quote)|思う{おもう}=think|。 >> For tourists, I think this is the best place for breakfast.",
  "サム: ぼく=me|^に=(for)|とって=for|^は=topic|、|生{なま}=raw|^の=(of)|魚{さかな}=fish|^は=topic|まだ=still|ちょっと=a bit|こわい=scary|な=(feeling)|。 >> For me, raw fish is still a little scary.",
  "ゆき: じゃあ=then|、|これ=this|^を=(object)|食{た}べてみて=try eating|。|まぐろ=tuna|^の=(of)|お寿司{おすし}=sushi|だよ=it is|。 >> Then try this. It's tuna sushi.",
  "サム: ……|おいしい=delicious|！|口{くち}=mouth|^の=(of)|中{なか}=inside|^で=in|消{き}えた=vanished|！ >> ... Delicious! It melted in my mouth!",
  "ゆき: ほら=see|。|次{つぎ}=next|^は=topic|納豆{なっとう}=natto|^に=(at)|挑戦{ちょうせん}しよう=let's take on|。 >> See? Next, let's take on natto.",
  "サム: 納豆{なっとう}=natto|^は=topic|日本人{にほんじん}=Japanese people|^で=(as)|さえ=even|苦手{にがて}=dislike|な=(who)|人{ひと}=people|^が=(subject)|いる=there are|でしょう=right|？ >> Even some Japanese people don't like natto, right?",
  "ブリップ: ブリップ=Blip|^は=topic|ロボット=robot|だ=is|から=so|、|何{なに}も=nothing|食{た}べられない=can't eat|。|におい=smell|^さえ=even|わからない=can't tell|。 >> Blip is a robot, so it can't eat anything. It can't even smell.",
  "サム: いいな=lucky you|、|ブリップ=Blip|。|……|よし=okay|、|食{た}べてみる=I'll try it|！ >> Lucky you, Blip. ... Okay, I'll try it!",
 ],
 "grammar": [
  {"id": "bakari-de-naku", "title": "～ばかりでなく / だけでなく: not only … but also",
   "explain": "A ばかりでなく B も = not only A, B too. だけでなく means the same and is more common in speech.",
   "examples": [("魚{さかな}=fish|ばかりでなく=not only|、|果物{くだもの}=fruit|^も=also|有名{ゆうめい}=famous|だ=is|。", "Not only the fish, the fruit is famous too.")],
   "quiz": [{"q": "魚＿＿＿＿＿、卵焼きも有名だ。", "hint": "Not only the fish, the omelets are famous too.", "choices": ["だけでなく", "しかなく", "ばかりで"], "answer": 0, "why": "Not only A but B: AだけでなくBも."}]},
  {"id": "ni-totte", "title": "～にとって: for (from someone's point of view)",
   "explain": "X にとって = from X's standpoint. It goes with judgments: important, hard, the best. It isn't 'for' as in a gift (that's ～に or ～のために).",
   "examples": [("ぼく=me|^に=(for)|とって=for|、|生{なま}=raw|^の=(of)|魚{さかな}=fish|^は=topic|こわい=scary|。", "For me, raw fish is scary.")],
   "quiz": [{"q": "学生＿＿＿＿、この本は高すぎる。", "hint": "For students, this book is too expensive.", "choices": ["にとって", "について", "によって"], "answer": 0, "why": "From someone's viewpoint: にとって. について = about; によって = by, depending on."}]},
  {"id": "sae", "title": "～さえ: even",
   "explain": "さえ marks an extreme example: 日本人でさえ (even Japanese people). It replaces が/を and comes after で/に. With ～ば it means 'if only': 時間さえあれば (if only I have time).",
   "examples": [("日本人{にほんじん}=Japanese people|^で=(as)|さえ=even|苦手{にがて}=dislike|だ=is|。", "Even Japanese people dislike it."), ("時間{じかん}=time|^さえ=only|あれば=if there is|、|行{い}ける=can go|。", "If only I have time, I can go.")],
   "quiz": [{"q": "ブリップはにおい＿＿わからない。", "hint": "Blip can't even smell.", "choices": ["さえ", "しか", "ばかり"], "answer": 0, "why": "An extreme example (even): さえ."}]},
 ],
 "kanji": [
  ("消", "ショウ", "き.える,け.す", "vanish, erase", [("消える", "きえる", "to vanish"), ("消す", "けす", "to turn off")]),
  ("次", "ジ", "つぎ", "next", [("次", "つぎ", "next"), ("次回", "じかい", "next time")]),
  ("観", "カン", "", "view", [("観光客", "かんこうきゃく", "tourist")]),
  ("客", "キャク", "", "guest", [("観光客", "かんこうきゃく", "tourist"), ("お客さん", "おきゃくさん", "customer")]),
  ("苦", "ク", "くる.しい,にが.い", "bitter, suffering", [("苦手", "にがて", "bad at, dislike"), ("苦い", "にがい", "bitter")]),
 ],
 "build": [3, 6],
 "questions": [
  {"q": "この市場は魚のほかに何が有名ですか。", "en": "Besides fish, what is this market famous for?", "choices": ["卵焼きと果物", "ラーメン", "お茶"], "answer": 0},
  {"q": "サムさんにとって、何がまだこわいですか。", "en": "What is still scary for Sam?", "choices": ["生の魚", "人が多いこと", "納豆のにおい"], "answer": 0},
  {"q": "ブリップはどうして何も食べられませんか。", "en": "Why can't Blip eat anything?", "choices": ["ロボットだから", "おなかがいっぱいだから", "納豆がきらいだから"], "answer": 0},
 ],
 "talk": "Tell Blip a food that's hard for you (～にとって), and something that even a child can do but you can't (～さえ).",
},
{
 "id": "n3-03", "level": "N3", "unit": 3,
 "title": {"ja": "台風で新幹線が止まった", "en": "The typhoon stopped the bullet train"},
 "scene": "Tokyo Station. A typhoon is coming, and the departure board keeps turning red.",
 "lines": [
  "ゆき: ニュース=news|^に=(by)|よると=according to|、|台風{たいふう}=typhoon|^が=(subject)|午後{ごご}=afternoon|^に=in|東京{とうきょう}=Tokyo|^に=to|来る{くる}=comes|らしい=apparently|。 >> According to the news, the typhoon is supposed to reach Tokyo this afternoon.",
  "サム: 見て{みて}=look|。|京都{きょうと}=Kyoto|行{ゆ}き=bound for|^の=(of)|新幹線{しんかんせん}=bullet trains|^が=(subject)|全部{ぜんぶ}=all|止{と}まっている=are stopped|。 >> Look. All the bullet trains to Kyoto are stopped.",
  "駅員: 台風{たいふう}=typhoon|^の=(of)|ため=because of|、|本日{ほんじつ}=today|^の=(of)|運転{うんてん}=service|^は=topic|中止せざるを得ません{ちゅうしせざるをえません}=we have no choice but to cancel|。 >> Due to the typhoon, we have no choice but to cancel today's service.",
  "サム: えっ=what|、|残念{ざんねん}=too bad|！|京都{きょうと}=Kyoto|^の=(of)|ホテル=hotel|^は=topic|もう=already|予約{よやく}してある=is booked|^のに=even though|……|。 >> What? Too bad! The Kyoto hotel is already booked...",
  "ゆき: 仕方{しかた}がない=it can't be helped|ね=right|。|東京{とうきょう}=Tokyo|^に=in|もう=one more|一泊{いっぱく}する=stay a night|しかない=only option|よ=(you know)|。 >> It can't be helped. We'll just have to stay one more night in Tokyo.",
  "サム: じゃあ=then|、|予約{よやく}=reservation|^を=(object)|明日{あした}=tomorrow|^に=to|変{か}えてもらう=have it changed|しかない=only option|な=(I guess)|。 >> Then I guess all I can do is have the reservation moved to tomorrow.",
  "ゆき: 電話{でんわ}=phone call|^は=topic|私{わたし}=I|^が=(subject)|かける=will make|よ=(you know)|。|敬語{けいご}=keigo|^は=topic|まだ=still|難{むずか}しい=difficult|でしょう=right|？ >> I'll make the call. Keigo is still hard for you, right?",
  "ブリップ: 外{そと}=outside|^は=topic|風{かぜ}=wind|^が=(subject)|強{つよ}くて=strong and|、|ブリップ=Blip|^が=(subject)|飛{と}ばされそう=about to be blown away|！ >> The wind outside is so strong, Blip's about to be blown away!",
  "サム: 今夜{こんや}=tonight|^は=topic|ホテル=hotel|^で=at|ニュース=news|^を=(object)|見ながら{みながら}=while watching|、|ラーメン=ramen|^を=(object)|食{た}べよう=let's eat|。 >> Tonight let's eat ramen at the hotel while we watch the news.",
 ],
 "grammar": [
  {"id": "ni-yoru-to", "title": "～によると: according to",
   "explain": "Source + によると names where you heard it, and the sentence usually ends with hearsay: ～そうだ, ～らしい, ～ということだ.",
   "examples": [("ニュース=news|^に=(by)|よると=according to|、|台風{たいふう}=typhoon|^が=(subject)|来る{くる}=comes|そうだ=I hear|。", "According to the news, a typhoon is coming.")],
   "quiz": [{"q": "天気予報＿＿＿＿＿、明日は雪だそうだ。", "hint": "According to the forecast, it'll snow tomorrow.", "choices": ["によると", "にとって", "について"], "answer": 0, "why": "Naming the source: によると, paired with そうだ."}]},
  {"id": "zaru-wo-enai", "title": "V-ざるを得ない: have no choice but to",
   "explain": "ない-stem + ざるを得ない (ざるをえない) = circumstances force you. 行く → 行かざるを得ない; する is irregular: せざるを得ない. It's formal: announcements and the news love it.",
   "examples": [("運転{うんてん}=service|^を=(object)|中止せざるを得ない{ちゅうしせざるをえない}=have no choice but to cancel|。", "We have no choice but to cancel the service.")],
   "quiz": [{"q": "台風なので、運転を中止＿＿＿＿＿＿。", "hint": "Because of the typhoon, we have no choice but to cancel.", "choices": ["せざるを得ない", "しざるを得ない", "するざるを得ない"], "answer": 0, "why": "する is irregular: せざるを得ない."}]},
  {"id": "shika-nai-v", "title": "V-るしかない: the only thing to do is",
   "explain": "Dictionary form + しかない = there's no other option. More casual than ざるを得ない.",
   "examples": [("もう=one more|一泊{いっぱく}する=stay a night|しかない=it's the only way|。", "We'll just have to stay one more night.")],
   "quiz": [{"q": "終電がないから、歩く＿＿＿＿。", "hint": "The last train's gone, so we can only walk.", "choices": ["しかない", "だけない", "ばかりない"], "answer": 0, "why": "Nothing else to do: dictionary form + しかない."}]},
 ],
 "kanji": [
  ("変", "ヘン", "か.わる,か.える", "change, strange", [("変える", "かえる", "to change"), ("大変", "たいへん", "tough")]),
  ("難", "ナン", "むずか.しい", "difficult", [("難しい", "むずかしい", "difficult")]),
  ("飛", "ヒ", "と.ぶ", "fly", [("飛ぶ", "とぶ", "to fly"), ("飛行機", "ひこうき", "airplane")]),
  ("得", "トク", "え.る", "gain", [("得る", "える", "to obtain"), ("得意", "とくい", "good at")]),
  ("残", "ザン", "のこ.る", "remain", [("残念", "ざんねん", "too bad"), ("残る", "のこる", "to remain")]),
 ],
 "build": [4, 8],
 "questions": [
  {"q": "ニュースによると、台風はいつ東京に来ますか。", "en": "According to the news, when does the typhoon reach Tokyo?", "choices": ["午後", "夜中", "明日の朝"], "answer": 0},
  {"q": "今日、二人はどうしますか。", "en": "What will the two of them do today?", "choices": ["東京にもう一泊する", "バスで京都へ行く", "大阪へ飛ぶ"], "answer": 0},
  {"q": "だれがホテルに電話をかけますか。", "en": "Who will call the hotel?", "choices": ["ゆきさん", "サムさん", "駅員"], "answer": 0},
 ],
 "talk": "Tell Blip about a time you had no choice (～しかなかった / ～ざるを得なかった), and pass on a piece of news with ～によると.",
},
{
 "id": "n3-04", "level": "N3", "unit": 4,
 "title": {"ja": "秋葉原のラジオ屋", "en": "The radio shops of Akihabara"},
 "scene": "The typhoon has passed. Before leaving Tokyo, Sam drags Yuki to the tiny radio-parts stalls under the tracks in Akihabara.",
 "lines": [
  "サム: ここ=here|^が=(subject)|ずっと=for ages|来たかった{きたかった}=wanted to come|ラジオ=radio|^の=(of)|部品屋{ぶひんや}=parts shops|だ=is|！ >> These are the radio-parts shops I've always wanted to visit!",
  "ゆき: 線路{せんろ}=tracks|^の=(of)|下{した}=under|^に=at|こんなに=this many|店{みせ}=shops|^が=(subject)|ある=there are|^なんて=(surprise)|知{し}らなかった=didn't know|。 >> I had no idea there were so many shops under the tracks.",
  "サム: すみません=excuse me|、|この=this|アンテナ=antenna|^に=(about)|ついて=about|聞{き}きたい=want to ask|んですが=(but…)|。 >> Excuse me, I'd like to ask about this antenna.",
  "店員: はい=yes|。|これ=this|^は=topic|昔{むかし}=long ago|^から=since|ある=exists|型{かた}=model|で=and|、|今{いま}=now|^でも=even|よく=well|売{う}れている=sells|んですよ=(you see)|。 >> Yes. It's a model that's been around for ages, and it still sells well.",
  "サム: 一万円{いちまんえん}=10,000 yen|？|こんなに=this|安{やす}い=cheap|わけがない=there's no way|！|ニューヨーク=New York|^で=in|^は=topic|三倍{さんばい}=three times|する=costs|よ=(you know)|。 >> Ten thousand yen? No way it's this cheap! In New York it costs three times that.",
  "店員: 本当{ほんとう}=real|^の=(of)|値段{ねだん}=price|です=is|よ=(you know)|。|日本製{にほんせい}=made in Japan|です=is|から=so|、|安心{あんしん}してください=rest assured|。 >> That's the real price. It's made in Japan, so you can rest assured.",
  "ゆき: サム=Sam|、|買{か}う=buy|ついでに=while you're at it|、|お父{とう}さん=your dad|^に=for|おみやげ=souvenir|^も=also|探{さが}したら=how about looking|？ >> Sam, while you're buying that, why not look for a souvenir for your dad too?",
  "サム: いいね=good idea|。|父{ちち}=my dad|^も=also|無線{むせん}=ham radio|^が=(subject)|好{す}き=likes|だから=so|、|喜{よろこ}ぶ=will be glad|と思う{とおもう}=I think|。 >> Good idea. My dad loves ham radio too, so I think he'll be happy.",
  "ブリップ: ブリップ=Blip|^の=(of)|新{あたら}しい=new|充電器{じゅうでんき}=charger|^も=also|買って{かって}=buy|！|今{いま}=now|^の=(one)|^は=topic|古{ふる}い=old|^の=(it's that)|。 >> Buy Blip a new charger too! The one I have is old.",
  "サム: わかった=got it|。|ブリップ=Blip|^が=(subject)|いない=not here|と=if|、|道{みち}=the way|^が=(subject)|わからない=don't know|から=so|ね=right|。 >> Okay. Without Blip I wouldn't know my way, after all.",
 ],
 "grammar": [
  {"id": "ni-tsuite", "title": "～について: about",
   "explain": "Noun + について = about, concerning. Before another noun use についての: 日本についての本 (a book about Japan).",
   "examples": [("この=this|アンテナ=antenna|^に=(about)|ついて=about|聞{き}きたい=want to ask|。", "I want to ask about this antenna.")],
   "quiz": [{"q": "日本の歴史＿＿＿＿＿調べている。", "hint": "I'm researching Japanese history.", "choices": ["について", "にとって", "によると"], "answer": 0, "why": "About a topic: について."}]},
  {"id": "wake-ga-nai", "title": "～わけがない: there's no way",
   "explain": "Plain form + わけがない = it's impossible, I refuse to believe it. Stronger than はずがない. Nouns and な-adjectives take な: 本当なわけがない.",
   "examples": [("こんなに=this|安{やす}い=cheap|わけがない=there's no way|。", "There's no way it's this cheap.")],
   "quiz": [{"q": "まじめなゆきさんが遅れる＿＿＿＿＿。", "hint": "There's no way serious Yuki would be late.", "choices": ["わけがない", "わけだ", "わけではない"], "answer": 0, "why": "Impossible: わけがない. わけだ = no wonder; わけではない = it's not that."}]},
  {"id": "tsuide-ni", "title": "～ついでに: while you're at it",
   "explain": "Verb (dictionary or past) + ついでに, or Noun の + ついでに = use the chance of doing A to also do B: 買い物のついでに (while out shopping).",
   "examples": [("買{か}う=buy|ついでに=while at it|、|おみやげ=souvenir|^も=also|探{さが}そう=let's look for|。", "While we're buying it, let's look for a souvenir too.")],
   "quiz": [{"q": "散歩の＿＿＿＿＿、パンを買ってきた。", "hint": "I bought bread while I was out for a walk.", "choices": ["ついでに", "うちに", "たびに"], "answer": 0, "why": "Taking the chance to do B too: ついでに."}]},
 ],
 "kanji": [
  ("昔", "セキ,シャク", "むかし", "long ago", [("昔", "むかし", "long ago")]),
  ("探", "タン", "さが.す", "search", [("探す", "さがす", "to look for")]),
  ("喜", "キ", "よろこ.ぶ", "rejoice", [("喜ぶ", "よろこぶ", "to be glad")]),
  ("値", "チ", "ね,あたい", "price, value", [("値段", "ねだん", "price")]),
  ("路", "ロ", "じ", "road, route", [("線路", "せんろ", "railroad tracks"), ("道路", "どうろ", "road")]),
 ],
 "build": [2, 6],
 "questions": [
  {"q": "店はどこにありますか。", "en": "Where are the shops?", "choices": ["線路の下", "駅の上", "ホテルの中"], "answer": 0},
  {"q": "ニューヨークでは、このアンテナはいくらぐらいですか。", "en": "About how much is this antenna in New York?", "choices": ["三万円ぐらい", "一万円", "五千円"], "answer": 0},
  {"q": "サムさんはだれにおみやげを買いますか。", "en": "Who is Sam buying a souvenir for?", "choices": ["お父さん", "ゆきさん", "店員"], "answer": 0},
 ],
 "talk": "Ask Blip about something you want to buy (～について聞きたい), react to a price with ～わけがない, and add one more errand with ～ついでに.",
},
{
 "id": "n3-05", "level": "N3", "unit": 5,
 "title": {"ja": "お邪魔させていただきます", "en": "Thank you for having me"},
 "scene": "Osaka. Yuki's parents invite Sam to dinner at their home. Sam has practiced his keigo all week.",
 "lines": [
  "サム: はじめまして=nice to meet you|。|サム=Sam|^と=(as)|申{もう}します=am called (humble)|。|お邪魔{じゃま}させていただきます=thank you for having me|。 >> Nice to meet you. My name is Sam. Thank you for having me.",
  "お父さん: よく=kindly|いらっしゃいました=you came (honorific)|。|どうぞ=please|、|お上{あ}がりください=come in (honorific)|。 >> Welcome. Please, come in.",
  "サム: 失礼{しつれい}します=excuse me (coming in)|。|今日{きょう}=today|^は=topic|招待{しょうたい}してくださって=for inviting me|、|ありがとうございます=thank you very much|。 >> Excuse me. Thank you very much for inviting me today.",
  "お母さん: ニューヨーク=New York|^で=in|^は=topic|ゆき=Yuki|^が=(subject)|お世話{せわ}になりました=was looked after|。 >> Thank you for looking after Yuki in New York.",
  "サム: いいえ=not at all|、|ゆきさん=Yuki|^の=(of)|おかげで=thanks to|、|日本語{にほんご}=Japanese|^が=(subject)|話{はな}せるようになりました=became able to speak|。 >> Not at all. Thanks to Yuki, I've become able to speak Japanese.",
  "お父さん: サムさん=Sam|^は=topic|お酒{さけ}=sake|^を=(object)|お飲{の}みになります=drink (honorific)|か=?|。 >> Sam, do you drink sake?",
  "サム: はい=yes|、|少{すこ}し=a little|^なら=if it's|大丈夫{だいじょうぶ}です=I'm fine|。|いただきます=I'll have some (humble)|。 >> Yes, a little is fine. I'll have some.",
  "ゆき: お父{とう}さん=Dad|、|飲{の}ませすぎないで=don't make him drink too much|ね=okay|。|台風{たいふう}=typhoon|^の=(of)|せいで=because of|、|旅行{りょこう}=trip|^が=(subject)|大変{たいへん}だった=was rough|^の=(it's that)|。 >> Dad, don't make him drink too much. The typhoon made his trip rough.",
  "お母さん: さあ=now|、|たこ焼{や}き=takoyaki|^を=(object)|どうぞ=please|。|大阪{おおさか}=Osaka|^の=(of)|味{あじ}=flavor|^を=(object)|召し上がってください{めしあがってください}=please eat (honorific)|。 >> Now, please have some takoyaki. Taste Osaka!",
  "ブリップ: ブリップ=Blip|^も=also|ごあいさつさせていただきます=allow me to greet you|！|ブリップ=Blip|です=am|！ >> Allow me to greet you too! I'm Blip!",
  "お父さん: ロボット=robot|^まで=even|敬語{けいご}=keigo|^が=(subject)|できる=can do|^の=(question)|か=!|。 >> Even the robot can do keigo!",
 ],
 "grammar": [
  {"id": "sasete-itadaku", "title": "～させていただく: I'll (humbly) do",
   "explain": "Causative て-form + いただく = 'I receive your permission to do'. It's a very humble way to announce your own action: お邪魔させていただきます, 説明させていただきます. Overused in business, but at someone's home it shows respect.",
   "examples": [("お邪魔{じゃま}させていただきます=I'll humbly come in|。", "Thank you for having me (lit. I'll humbly intrude)."), ("説明{せつめい}させていただきます=allow me to explain|。", "Allow me to explain.")],
   "quiz": [{"q": "では、説明＿＿＿＿＿＿ます。", "hint": "Then allow me to explain.", "choices": ["させていただき", "していただき", "させてくださり"], "answer": 0, "why": "Your own action, with humble permission: させていただく. していただく would mean someone else does it for you."}]},
  {"id": "o-ni-naru", "title": "お～になる / お～する: raise them, lower yourself",
   "explain": "お + stem + になる raises the other person's action: お飲みになる (you drink), お帰りになる. お + stem + する lowers your own: お持ちします (I'll carry it). Some verbs have special forms: いらっしゃる, 召し上がる, 申す.",
   "examples": [("お酒{さけ}=sake|^を=(object)|お飲{の}みになります=drink (honorific)|か=?|。", "Do you drink sake?"), ("荷物{にもつ}=bag|^を=(object)|お持{も}ちします=I'll carry (humble)|。", "Let me carry your bag.")],
   "quiz": [{"q": "先生は何時にお帰り＿＿＿＿＿か。", "hint": "What time will the teacher go home?", "choices": ["になります", "します", "いたします"], "answer": 0, "why": "Someone else's action, raised: お～になる."},
            {"q": "荷物、お持ち＿＿＿。", "hint": "Let me carry your bag.", "choices": ["します", "になります", "ください"], "answer": 0, "why": "Your own action, lowered: お～する."}]},
  {"id": "okage-sei", "title": "～おかげで / ～せいで: thanks to / because of (blame)",
   "explain": "Same shape (plain form, or Noun の + おかげで / せいで), opposite feeling: おかげで for good results, せいで for bad ones.",
   "examples": [("ゆきさん=Yuki|^の=(of)|おかげで=thanks to|、|話{はな}せるようになった=became able to speak|。", "Thanks to Yuki, I can speak now."), ("台風{たいふう}=typhoon|^の=(of)|せいで=because of|、|大変{たいへん}だった=was rough|。", "Because of the typhoon, it was rough.")],
   "quiz": [{"q": "雨の＿＿＿、試合が中止になった。", "hint": "Because of the rain, the game was canceled.", "choices": ["せいで", "おかげで", "ついでに"], "answer": 0, "why": "A bad result: せいで."}]},
 ],
 "kanji": [
  ("申", "シン", "もう.す", "say (humble)", [("申す", "もうす", "to be called (humble)"), ("申し込む", "もうしこむ", "to apply")]),
  ("酒", "シュ", "さけ,さか", "sake, alcohol", [("お酒", "おさけ", "sake, alcohol"), ("日本酒", "にほんしゅ", "Japanese sake")]),
  ("夫", "フ", "おっと", "husband, man", [("大丈夫", "だいじょうぶ", "all right"), ("夫", "おっと", "husband")]),
  ("招", "ショウ", "まね.く", "invite", [("招く", "まねく", "to invite"), ("招待", "しょうたい", "invitation")]),
  ("礼", "レイ", "", "thanks, bow", [("失礼", "しつれい", "rude; excuse me"), ("お礼", "おれい", "thanks")]),
 ],
 "build": [4, 6],
 "questions": [
  {"q": "サムさんはだれのおかげで日本語が話せるようになりましたか。", "en": "Thanks to whom can Sam speak Japanese?", "choices": ["ゆきさん", "ブリップ", "お父さん"], "answer": 0},
  {"q": "お父さんはサムさんに何を聞きましたか。", "en": "What did the father ask Sam?", "choices": ["お酒を飲むかどうか", "仕事は何か", "いつ帰るか"], "answer": 0},
  {"q": "どうしてサムさんの旅行は大変でしたか。", "en": "Why was Sam's trip rough?", "choices": ["台風のせいで", "お金がなくて", "道に迷って"], "answer": 0},
 ],
 "talk": "Role-play: Blip is a friend's parent. Introduce yourself humbly (と申します), thank them (おかげで), and answer an honorific question (お～になりますか).",
},
{
 "id": "n3-06", "level": "N3", "unit": 6,
 "title": {"ja": "京都で迷子になった", "en": "Lost in Kyoto"},
 "scene": "Kyoto, finally. Sam wanders off alone up Fushimi Inari's thousand red gates. His phone is at 3%.",
 "lines": [
  "サム: 鳥居{とりい}=torii gates|^を=(object)|数{かぞ}えている=was counting|うちに=while|、|どこ=where|^に=at|いる=am|^か=(whether)|わからなくなった=lost track|。 >> While I was counting the torii gates, I lost track of where I was.",
  "サム: 地図{ちず}=map|^を=(object)|見よう{みよう}とした=tried to look at|とたん=the moment|、|スマホ=phone|^の=(of)|電池{でんち}=battery|^が=(subject)|切{き}れた=died|！ >> The moment I tried to check the map, my phone battery died!",
  "ブリップ: ブリップ=Blip|^の=(of)|電池{でんち}=battery|^も=also|あと=remaining|少{すこ}し=a little|……|。|山{やま}=mountain|^は=topic|暗{くら}くなる=gets dark|^の=(the)|^が=(subject)|早{はや}い=early|よ=(warning)|。 >> My battery is almost out too... It gets dark early on the mountain.",
  "サム: すみません=excuse me|、|駅{えき}=station|^へ=to|戻{もど}りたい=want to go back|んですが=(but…)|。 >> Excuse me, I'd like to get back to the station.",
  "おばあさん: この=this|道{みち}=path|^を=(object)|まっすぐ=straight|下{くだ}れば=if you go down|、|駅{えき}=station|^に=at|着{つ}く=arrive|に違いない{にちがいない}=surely|よ=(you know)|。 >> Go straight down this path and you're sure to reach the station.",
  "サム: ありがとうございます=thank you very much|！|あの=that|お茶屋{ちゃや}=tea shop|^で=at|充電{じゅうでん}させてもらえる=can let me charge|^か=(whether)|聞{き}いてみよう=I'll ask|。 >> Thank you! I'll ask if that tea shop will let me charge my phone.",
  "店の人: どうぞ=go ahead|。|充電{じゅうでん}=charging|^が=(subject)|終わり次第{おわりしだい}=as soon as it's done|、|お知{し}らせします=I'll let you know|。 >> Go ahead. I'll let you know as soon as it's charged.",
  "ゆき: もしもし=hello|、|サム=Sam|？|一時間{いちじかん}=an hour|も=as much as|連絡{れんらく}=contact|^が=(subject)|なくて=wasn't and|、|心配{しんぱい}した=was worried|よ=(you know)|！ >> Hello, Sam? I hadn't heard from you for an hour, I was worried!",
  "サム: ごめん=sorry|。|鳥居{とりい}=gates|^が=(subject)|きれいすぎて=too beautiful|、|気{き}がついたら=when I noticed|山{やま}=mountain|^の=(of)|上{うえ}=top|^に=at|いた=was|んだ=(you see)|。 >> Sorry. The gates were so beautiful that before I knew it I was at the top of the mountain.",
  "ゆき: サム=Sam|らしい=so like you|ね=huh|。|駅{えき}=station|^で=at|待{ま}っている=will wait|から=so|、|気{き}をつけて=be careful|。 >> That's so you. I'll wait at the station, so be careful.",
 ],
 "grammar": [
  {"id": "uchi-ni-change", "title": "V-ているうちに: while (and before you knew it)",
   "explain": "ている + うちに = during an ongoing action, something changed without you noticing: 数えているうちにわからなくなった. Compare N4 うちに: do it while you still can.",
   "examples": [("数{かぞ}えている=was counting|うちに=while|、|わからなくなった=lost track|。", "While I was counting, I lost track.")],
   "quiz": [{"q": "話している＿＿＿、だんだん眠くなった。", "hint": "While we were talking, I got sleepy.", "choices": ["うちに", "とたん", "ついでに"], "answer": 0, "why": "A change that crept in during an action: ているうちに."}]},
  {"id": "totan", "title": "V-たとたん: the moment …",
   "explain": "Past form + とたん(に) = right as A happened, B happened, usually a surprise you didn't choose.",
   "examples": [("見よう{みよう}とした=tried to look|とたん=the moment|、|電池{でんち}=battery|^が=(subject)|切{き}れた=died|。", "The moment I tried to look, the battery died.")],
   "quiz": [{"q": "外に出た＿＿＿、雨が降り出した。", "hint": "The moment I went out, it started to rain.", "choices": ["とたん", "うちに", "たびに"], "answer": 0, "why": "Right at that moment, unexpectedly: たとたん."}]},
  {"id": "ni-chigainai", "title": "～に違いない: must be, surely",
   "explain": "Plain form + に違いない = I'm convinced. Nouns and な-adjectives attach directly: 本当に違いない. Stronger and more written than だろう.",
   "examples": [("駅{えき}=station|^に=at|着{つ}く=arrive|に違いない{にちがいない}=surely|。", "You're sure to reach the station.")],
   "quiz": [{"q": "電気がついている。だれかいる＿＿＿＿＿。", "hint": "The light's on. Someone must be there.", "choices": ["に違いない", "わけがない", "ことにする"], "answer": 0, "why": "A confident guess: に違いない."}]},
 ],
 "kanji": [
  ("数", "スウ", "かず,かぞ.える", "number, count", [("数える", "かぞえる", "to count"), ("数", "かず", "number")]),
  ("暗", "アン", "くら.い", "dark", [("暗い", "くらい", "dark")]),
  ("戻", "レイ", "もど.る", "return", [("戻る", "もどる", "to go back")]),
  ("違", "イ", "ちが.う", "differ", [("違う", "ちがう", "to differ"), ("間違い", "まちがい", "mistake")]),
  ("連", "レン", "つ.れる", "link, take along", [("連絡", "れんらく", "contact"), ("連れる", "つれる", "to take along")]),
 ],
 "build": [3, 9],
 "questions": [
  {"q": "サムさんはどうして迷子になりましたか。", "en": "How did Sam get lost?", "choices": ["鳥居を数えているうちに", "電車をまちがえて", "地図を忘れて"], "answer": 0},
  {"q": "スマホの電池はいつ切れましたか。", "en": "When did the phone die?", "choices": ["地図を見ようとしたとき", "駅に着いたとき", "ゆきさんに電話したとき"], "answer": 0},
  {"q": "ゆきさんはどこで待っていますか。", "en": "Where is Yuki waiting?", "choices": ["駅", "お茶屋", "山の上"], "answer": 0},
 ],
 "talk": "Tell Blip about a time something happened the moment you did something (～たとたん), and make a confident guess about something with ～に違いない.",
},
{
 "id": "n3-07", "level": "N3", "unit": 7,
 "title": {"ja": "温泉で考えたこと", "en": "Thoughts at the hot spring"},
 "scene": "Hakone, on the way back to Tokyo. At dusk Sam and Yuki sit by an outdoor hot spring with Mt. Fuji in the distance.",
 "lines": [
  "ゆき: 日本{にほん}=Japan|^に=to|来てから{きてから}=since coming|、|サム=Sam|^の=(of)|日本語{にほんご}=Japanese|^は=topic|ずいぶん=quite a lot|変{か}わった=changed|ね=right|。 >> Your Japanese has changed a lot since you came to Japan.",
  "サム: 毎日{まいにち}=every day|聞{き}いている=listening|^と=when|、|耳{みみ}=ears|^が=(subject)|慣{な}れてきた=got used to it|んだ=(you see)|。 >> Listening every day, my ears have gotten used to it.",
  "サム: 話{はな}す=speak|機会{きかい}=chances|^が=(subject)|増{ふ}える=increase|^に=(with)|つれて=as|、|こわくなくなった=stopped being scared|。 >> As my chances to speak grew, I stopped being scared.",
  "ゆき: 子{こ}ども=child|^の=(of)|ころ=time|、|家族{かぞく}=family|^と=with|よく=often|この=this|温泉{おんせん}=hot spring|^に=to|来た{きた}ものだ=used to come|。 >> When I was a kid, I used to come to this hot spring with my family a lot.",
  "サム: だから=so that's why|、|ここ=here|^を=(object)|選{えら}んだ=chose|んだ=(you see)|ね=right|。 >> So that's why you chose this place.",
  "サム: 言葉{ことば}=words|^が=(subject)|わからなかった=didn't understand|から=because|こそ=precisely|、|何{なん}でも=everything|よく=closely|見る{みる}=look|ようになった=came to|^と=(quote)|思う{おもう}=think|。 >> I think it's precisely because I didn't understand the words that I started looking closely at everything.",
  "ゆき: いい=nice|こと=thing|言う{いう}=say|ね=huh|。|勉強{べんきょう}=studying|^は=topic|大変{たいへん}だった=was hard|けど=but|、|楽{たの}しかった=was fun|？ >> Nice thing to say. Studying was hard, but was it fun?",
  "サム: 難{むずか}しかった=was difficult|から=because|こそ=precisely|、|楽{たの}しかった=was fun|んだ=(you see)|。 >> It was fun precisely because it was hard.",
  "ブリップ: 湯気{ゆげ}=steam|^で=from|、|ブリップ=Blip|^の=(of)|画面{がめん}=screen|^が=(subject)|白{しろ}くなってきた=is getting white|……|。|温泉{おんせん}=hot springs|^は=topic|ロボット=robots|^に=(for)|とって=for|危{あぶ}ない=dangerous|！ >> The steam is fogging up my screen... Hot springs are dangerous for robots!",
  "サム: 季節{きせつ}=seasons|^が=(subject)|変{か}わる=change|^に=(with)|つれて=as|、|この=this|景色{けしき}=scenery|^も=also|変{か}わる=changes|んだろうな=I guess|。 >> I guess this view changes with the seasons too.",
 ],
 "grammar": [
  {"id": "ni-tsurete", "title": "～につれて: as (one thing changes, so does another)",
   "explain": "Dictionary form or noun + につれて = as A changes, B changes with it. Both sides are gradual changes.",
   "examples": [("季節{きせつ}=seasons|^が=(subject)|変{か}わる=change|^に=(with)|つれて=as|、|景色{けしき}=scenery|^も=also|変{か}わる=changes|。", "As the seasons change, the scenery changes too.")],
   "quiz": [{"q": "練習する＿＿＿＿、上手になってきた。", "hint": "As I practiced, I got better.", "choices": ["につれて", "について", "にとって"], "answer": 0, "why": "Two gradual changes together: につれて."}]},
  {"id": "mono-da", "title": "～ものだ: used to (nostalgia) / that's how it is",
   "explain": "Past + ものだ = something you used to do, said with nostalgia: よく来たものだ. Dictionary form + ものだ = the nature of things, or what one should do: 子どもは遊ぶものだ.",
   "examples": [("よく=often|この=this|温泉{おんせん}=hot spring|^に=to|来た{きた}ものだ=used to come|。", "I used to come to this hot spring a lot.")],
   "quiz": [{"q": "子どものころ、よく川で泳いだ＿＿＿＿。", "hint": "As a kid I used to swim in the river a lot.", "choices": ["ものだ", "ことだ", "わけだ"], "answer": 0, "why": "Nostalgic 'used to': past + ものだ."}]},
  {"id": "kara-koso", "title": "～からこそ: precisely because",
   "explain": "から + こそ puts all the weight on the reason: it's because of A, not despite it, that B. Often the reason looks like it should lead to the opposite.",
   "examples": [("難{むずか}しかった=was hard|から=because|こそ=precisely|、|楽{たの}しかった=was fun|。", "It was fun precisely because it was hard.")],
   "quiz": [{"q": "好きだ＿＿＿＿＿、毎日練習できる。", "hint": "It's precisely because I love it that I can practice every day.", "choices": ["からこそ", "のに", "けど"], "answer": 0, "why": "Stressing the reason: からこそ."}]},
 ],
 "kanji": [
  ("耳", "ジ", "みみ", "ear", [("耳", "みみ", "ear")]),
  ("慣", "カン", "な.れる", "get used to", [("慣れる", "なれる", "to get used to"), ("習慣", "しゅうかん", "habit")]),
  ("増", "ゾウ", "ふ.える,ま.す", "increase", [("増える", "ふえる", "to increase")]),
  ("選", "セン", "えら.ぶ", "choose", [("選ぶ", "えらぶ", "to choose"), ("選手", "せんしゅ", "athlete")]),
  ("景", "ケイ", "", "scenery", [("景色", "けしき", "scenery")]),
 ],
 "build": [2, 7],
 "questions": [
  {"q": "サムさんはどうしてこわくなくなりましたか。", "en": "Why did Sam stop being scared?", "choices": ["話す機会が増えたから", "敬語を覚えたから", "ブリップが話してくれたから"], "answer": 0},
  {"q": "ゆきさんは子どものころ、だれとこの温泉に来ましたか。", "en": "Who did Yuki come to this hot spring with as a child?", "choices": ["家族", "友達", "一人で"], "answer": 0},
  {"q": "どうして温泉はブリップにとって危ないのですか。", "en": "Why are hot springs dangerous for Blip?", "choices": ["湯気で画面が白くなるから", "お湯が熱すぎるから", "暗いから"], "answer": 0},
 ],
 "talk": "Tell Blip how something changed as you kept at it (～につれて), something you used to do as a kid (～たものだ), and why a hard thing was worth it (～からこそ).",
},
{
 "id": "n3-08", "level": "N3", "unit": 8,
 "title": {"ja": "また会えますように", "en": "Hope we meet again"},
 "scene": "Narita Airport, the last day. Sam's bag is full of radio parts and snacks. Yuki came to see him off.",
 "lines": [
  "ゆき: 忘れ物{わすれもの}=anything forgotten|^は=topic|ない=none|？|パスポート=passport|^は=topic|？ >> Forgetting anything? Passport?",
  "サム: ある=got it|よ=(you know)|。|ずっと=the whole time|案内{あんない}してくれて=for guiding me|ありがとう=thank you|。 >> Got it. Thank you for showing me around the whole time.",
  "ゆき: こちら=I|^こそ=(it's me who)|。|サム=Sam|^と=with|旅行{りょこう}する=travel|たびに=every time|、|新{あたら}しい=new|こと=things|^に=(to)|気{き}がつく=notice|^の=(it's that)|。 >> No, thank YOU. Every time I travel with you, I notice something new.",
  "サム: ぼく=me|^も=too|。|日本語{にほんご}=Japanese|^を=(object)|話{はな}す=speak|たびに=every time|、|自分{じぶん}=myself|^が=(subject)|少{すこ}し=a little|変{か}わる=change|気{き}がする=feel like|。 >> Me too. Every time I speak Japanese, I feel like I change a little.",
  "ゆき: 次{つぎ}=next time|^は=topic|冬{ふゆ}=winter|^に=in|来て{きて}=come|。|北海道{ほっかいどう}=Hokkaido|^の=(of)|雪{ゆき}=snow|^を=(object)|見せたい{みせたい}=want to show|。 >> Come in winter next time. I want to show you the snow in Hokkaido.",
  "サム: 雪{ゆき}=snow|^と=and|ゆきさん=Yuki|^の=(of)|名前{なまえ}=name|、|同{おな}じ=same|だ=is|ね=right|！|今{いま}=now|気{き}がついた=noticed|。 >> Snow (yuki) and your name are the same! I just noticed.",
  "ゆき: 遅{おそ}すぎる=way too late|よ=(you know)|！ >> Took you long enough!",
  "アナウンス: ニューヨーク=New York|行{ゆ}き=bound for|^の=(of)|お客様{きゃくさま}=passengers|^は=topic|、|五番{ごばん}=No. 5|ゲート=gate|^へ=to|お越{こ}しください=please proceed|。 >> Passengers for New York, please proceed to Gate 5.",
  "ブリップ: 飛行機{ひこうき}=plane|^で=on|^は=topic|、|今度{こんど}=this time|^こそ=for sure|寝て{ねて}=sleep|ね=okay|、|サム=Sam|。 >> On the plane, this time make sure you sleep, Sam.",
  "サム: うん=yeah|。|また=again|みんな=everyone|^に=(to)|会{あ}えます=can meet|ように=I hope|。 >> Yeah. I hope I can see everyone again.",
 ],
 "grammar": [
  {"id": "tabi-ni", "title": "～たびに: every time",
   "explain": "Dictionary form or Noun の + たびに = whenever A happens, B happens. B is usually a change or a feeling: 旅行のたびに (every trip).",
   "examples": [("日本語{にほんご}=Japanese|^を=(object)|話{はな}す=speak|たびに=every time|、|少{すこ}し=a little|変{か}わる=change|。", "Every time I speak Japanese, I change a little.")],
   "quiz": [{"q": "この歌を聞く＿＿＿、ニューヨークを思い出す。", "hint": "Every time I hear this song, I remember New York.", "choices": ["たびに", "うちに", "とたん"], "answer": 0, "why": "Whenever A, B: たびに."}]},
  {"id": "koso", "title": "～こそ: this one, for sure",
   "explain": "こそ spotlights one word as THE one: 今度こそ (this time for sure), こちらこそ (no, thank YOU). It replaces は/が/を.",
   "examples": [("今度{こんど}=this time|^こそ=for sure|寝て{ねて}=sleep|ね=okay|。", "This time, make sure you sleep."), ("こちら=me|^こそ=(it's me)|、|ありがとう=thank you|。", "No, thank YOU.")],
   "quiz": [{"q": "A：ありがとう。B：こちら＿＿、ありがとう。", "hint": "A: Thanks. B: No, thank YOU.", "choices": ["こそ", "さえ", "ばかり"], "answer": 0, "why": "こちらこそ: it's me who should say it."},
            {"q": "今年＿＿、日本へ行きたい。", "hint": "This year, for sure, I want to go to Japan.", "choices": ["こそ", "さえ", "しか"], "answer": 0, "why": "This one for sure: こそ."}]},
  {"id": "you-ni-wish", "title": "～ますように: I hope, may …",
   "explain": "ます-form + ように, said like a wish or prayer: また会えますように (I hope we meet again). People write these on wooden ema plaques at shrines. Negative: 雨が降りませんように.",
   "examples": [("また=again|会{あ}えます=can meet|ように=I hope|。", "I hope we can meet again.")],
   "quiz": [{"q": "明日、雨が降り＿＿＿ように。", "hint": "I hope it doesn't rain tomorrow.", "choices": ["ません", "ない", "なく"], "answer": 0, "why": "Wishes use the ます-form: 降りませんように."}]},
 ],
 "kanji": [
  ("忘", "ボウ", "わす.れる", "forget", [("忘れる", "わすれる", "to forget"), ("忘れ物", "わすれもの", "something left behind")]),
  ("遅", "チ", "おく.れる,おそ.い", "late, slow", [("遅い", "おそい", "late, slow"), ("遅れる", "おくれる", "to be late")]),
  ("越", "エツ", "こ.す,こ.える", "cross, go over", [("お越しください", "おこしください", "please come"), ("引っ越す", "ひっこす", "to move house")]),
  ("番", "バン", "", "number, turn", [("五番", "ごばん", "number five"), ("番号", "ばんごう", "number")]),
  ("様", "ヨウ", "さま", "Mr./Ms., manner", [("お客様", "おきゃくさま", "customer"), ("様子", "ようす", "situation")]),
 ],
 "build": [6, 9],
 "questions": [
  {"q": "ゆきさんは次、いつサムさんに来てほしいですか。", "en": "When does Yuki want Sam to come next?", "choices": ["冬", "夏", "春"], "answer": 0},
  {"q": "サムさんは何に気がつきましたか。", "en": "What did Sam notice?", "choices": ["雪とゆきさんの名前が同じこと", "パスポートがないこと", "ゲートが違うこと"], "answer": 0},
  {"q": "ブリップはサムさんに飛行機で何をしてほしいですか。", "en": "What does Blip want Sam to do on the plane?", "choices": ["寝ること", "映画を見ること", "勉強すること"], "answer": 0},
 ],
 "talk": "Say goodbye to Blip as if at the airport: thank it (こちらこそ), say what happens every time you study (～たびに), and make a wish (～ますように).",
},
]
