# More JLPT N3 units (9–12): back in New York after the trip, then winter in Sapporo. Notation: see build.py.
# Grammar ids match data/grammar.json, so each point links to its full lesson.

UNITS = [
{
 "id": "n3-09", "level": "N3", "unit": 9,
 "title": {"ja": "東京に比べて", "en": "Compared to Tokyo"},
 "scene": "September, back in New York. Sam and Yuki wait for a delayed train at Union Square.",
 "lines": [
  "サム: 東京{とうきょう}=Tokyo|^に=(with)|比{くら}べて=compared|、|ニューヨーク=New York|^の=(of)|地下鉄{ちかてつ}=subway|^は=topic|本当{ほんとう}に=really|うるさい=noisy|な=huh|。 >> Compared to Tokyo, the New York subway is really noisy.",
  "ゆき: 帰{かえ}ってきた=came back|ばかり=only just|^の=(of)|人{ひと}=people|^は=topic|みんな=all|そう=that|言{い}う=say|よ=you know|。 >> Everyone who just got back says that.",
  "サム: でも=but|、|東京{とうきょう}=Tokyo|^の=(of)|ほう=side|^が=(subject)|全部{ぜんぶ}=everything|いい=better|わけではない=it's not that|^んだ=(you see)|。 >> But it's not that everything is better in Tokyo.",
  "サム: ニューヨーク=New York|^は=topic|二十四時間{にじゅうよじかん}=24 hours|電車{でんしゃ}=trains|^が=(subject)|走{はし}っている=run|し=and|、|どこ=where|^で=in|^も=even|ピザ=pizza|^が=(subject)|買{か}える=can buy|。 >> In New York the trains run 24 hours, and you can buy pizza anywhere.",
  "ゆき: ピザ=pizza|なんか=something like|^で=with|喜{よろこ}ぶ=be happy|^の=(question)|？|子{こ}ども=child|みたい=like|。 >> You're happy about something like pizza? Like a kid.",
  "サム: ピザ=pizza|なんか=stuff like|^じゃない=isn't|よ=you know|！|ニューヨーク=New York|^の=(of)|文化{ぶんか}=culture|だ=is|よ=you know|。 >> It's not just pizza! It's New York culture.",
  "ブリップ: 日本{にほん}=Japan|^に=(with)|比{くら}べて=compared|、|ここ=here|^は=topic|ネズミ=rats|^が=(subject)|多{おお}い=many|です=are|ね=right|。 >> Compared to Japan, there are a lot of rats here.",
  "ゆき: ……|それ=that|^は=topic|否定{ひてい}できない=can't deny|わね=(I admit)|。 >> ...I can't deny that.",
  "サム: あ=oh|、|電車{でんしゃ}=train|^が=(subject)|来{き}た=came|。|遅{おく}れた=was late|けど=but|、|嫌{きら}い=dislike|な=(that I)|わけではない=it's not that|よ=you know|。 >> Oh, the train's here. It was late, but that doesn't mean I hate it.",
 ],
 "grammar": [
  {"id": "ni-kuraberu", "title": "～に比べて: compared to",
   "explain": "Noun + に比べて (くらべて) = compared with. The rest of the sentence says how the other thing differs. In writing: に比べ.",
   "examples": [("東京{とうきょう}=Tokyo|^に=(with)|比{くら}べて=compared|、|うるさい=noisy|。", "Compared to Tokyo, it's noisy.")],
   "quiz": [{"q": "去年＿＿＿＿、今年は雪が多い。", "hint": "Compared to last year, there's more snow this year.", "choices": ["に比べて", "について", "によって"], "answer": 0, "why": "Comparing: に比べて."}]},
  {"id": "wake-dewanai", "title": "～わけではない: it's not that, it doesn't mean",
   "explain": "Plain form + わけではない softens or denies a conclusion someone might draw: 嫌いなわけではない (it's not that I dislike it). 全部…わけではない = not all.",
   "examples": [("全部{ぜんぶ}=everything|いい=good|わけではない=it's not that|。", "It's not that everything is better."), ("嫌{きら}い=dislike|な=(that)|わけではない=it doesn't mean|。", "It doesn't mean I hate it.")],
   "quiz": [{"q": "高い店がいつもおいしい＿＿＿＿＿＿。", "hint": "Expensive restaurants aren't always delicious.", "choices": ["わけではない", "わけがない", "わけだ"], "answer": 0, "why": "Denying a general conclusion: わけではない."}]},
  {"id": "nanka", "title": "～なんか / ～なんて: something like (dismissive)",
   "explain": "Noun + なんか makes light of it (or of yourself): ピザなんか (something like pizza), 私なんか (someone like me). なんて does the same and also shows surprise: そんなことを言うなんて.",
   "examples": [("ピザ=pizza|なんか=something like|^で=with|喜{よろこ}ぶ=be happy|^の=(question)|？", "You're happy about something like pizza?")],
   "quiz": [{"q": "私＿＿＿にはできません。", "hint": "Someone like me can't do it.", "choices": ["なんか", "こそ", "さえ"], "answer": 0, "why": "Playing it down: なんか."}]},
 ],
 "kanji": [
  ("比", "ヒ", "くら.べる", "compare", [("比べる", "くらべる", "to compare")]),
  ("鉄", "テツ", "", "iron", [("地下鉄", "ちかてつ", "subway")]),
  ("化", "カ", "ば.ける", "change, -ization", [("文化", "ぶんか", "culture")]),
  ("否", "ヒ", "いな", "no, deny", [("否定", "ひてい", "denial")]),
  ("嫌", "ケン", "きら.う,いや", "dislike", [("嫌い", "きらい", "dislike"), ("嫌", "いや", "unpleasant")]),
 ],
 "build": [2, 8],
 "questions": [
  {"q": "サムさんによると、ニューヨークの地下鉄は東京に比べてどうですか。", "en": "According to Sam, how is the NY subway compared to Tokyo's?", "choices": ["うるさい", "きれい", "速い"], "answer": 0},
  {"q": "サムさんはニューヨークのどんなところがいいと言いましたか。", "en": "What does Sam like about New York?", "choices": ["電車が二十四時間走ること", "電車が遅れないこと", "ネズミがいないこと"], "answer": 0},
  {"q": "ブリップは何が多いと言いましたか。", "en": "What does Blip say there are a lot of?", "choices": ["ネズミ", "ピザ", "電車"], "answer": 0},
 ],
 "talk": "Compare your city with another one (～に比べて), add a 'that doesn't mean…' (～わけではない), and tease Blip about something small (～なんか).",
},
{
 "id": "n3-10", "level": "N3", "unit": 10,
 "title": {"ja": "読みかけの本", "en": "The half-read book"},
 "scene": "October. Sam is trying to finish his first Japanese novel, a gift from Yuki's mother in Osaka.",
 "lines": [
  "ゆき: その=that|本{ほん}=book|、|まだ=still|読{よ}みかけ=half-read|なの=is it|？|夏{なつ}=summer|^から=since|ずっと=all along|机{つくえ}=desk|^の=(of)|上{うえ}=on top|^に=on|ある=is|よ=you know|。 >> Is that book still half-read? It's been on your desk since summer.",
  "サム: 読み続けて{よみつづけて}=keep reading|いる=am|よ=you know|！|毎晩{まいばん}=every night|十{じゅう}ページ=ten pages|ずつ=each|。 >> I'm still reading it! Ten pages a night.",
  "サム: 最初{さいしょ}=at first|^は=topic|一{いち}ページ=one page|^に=(for)|三十分{さんじゅっぷん}=thirty minutes|^も=as much as|かかった=took|。|知{し}らない=unknown|言葉{ことば}=words|^が=(subject)|多{おお}すぎて=too many|。 >> At first one page took thirty minutes. Too many words I didn't know.",
  "ゆき: 途中{とちゅう}=midway|^で=at|やめかけた=almost quit|^こと=time|^も=also|あった=there was|でしょう=right|？ >> There were times you almost quit, weren't there?",
  "サム: うん=yeah|。|でも=but|、|ゆき=Yuki|^の=(of)|お母{かあ}さん=mother|^に=(to)|「|読み切ります{よみきります}=I'll read it all|」|^と=(quote)|約束{やくそく}した=promised|^から=so|。 >> Yeah. But I promised your mother I'd read it to the end.",
  "ブリップ: あと=remaining|二十{にじゅう}ページ=twenty pages|です=is|。|今夜{こんや}=tonight|^で=by|読み切れる{よみきれる}=can finish|はず=should|です=is|よ=you know|。 >> Twenty pages left. You should be able to finish it tonight.",
  "サム: よし=right|。|最後{さいご}=the end|^まで=until|読み続ける{よみつづける}=keep reading|ぞ=(determined)|！ >> Right. I'll keep reading to the end!",
  "ゆき: 読み終わったら{よみおわったら}=when you've finished|、|母{はは}=my mom|^に=to|手紙{てがみ}=letter|^を=(object)|書{か}いて=write|あげて=(for her)|ね=okay|。 >> When you've finished, write my mom a letter, okay?",
  "サム: もちろん=of course|。|日本語{にほんご}=Japanese|^で=in|書き始める{かきはじめる}=start writing|よ=you know|。|……|でも=but|、|手紙{てがみ}=the letter|^も=also|書{か}きかけ=half-written|^に=(as)|なりそう=likely to become|だ=is|な=huh|。 >> Of course. I'll start writing it in Japanese. ...Though the letter might end up half-written too.",
 ],
 "grammar": [
  {"id": "kakeru", "title": "V-stem かける / かけ: half-done, about to",
   "explain": "Verb stem + かける = start something and leave it halfway, or nearly do it: やめかけた (almost quit). As a noun: 読みかけの本 (a half-read book).",
   "examples": [("読{よ}みかけ=half-read|^の=(of)|本{ほん}=book|。", "A half-read book."), ("途中{とちゅう}=midway|^で=at|やめかけた=almost quit|。", "I almost quit halfway.")],
   "quiz": [{"q": "飲み＿＿＿のコーヒーが冷めてしまった。", "hint": "My half-drunk coffee went cold.", "choices": ["かけ", "きり", "だし"], "answer": 0, "why": "Half-done: stem + かけ."}]},
  {"id": "kiru", "title": "V-stem きる: do completely, to the end",
   "explain": "Verb stem + きる (切る) = do it all the way: 読み切る (read to the end), 使い切る (use it all up). Potential: 読み切れる. Negative: 食べきれない (can't finish eating).",
   "examples": [("最後{さいご}=the end|^まで=until|読み切ります{よみきります}=I'll read it all|。", "I'll read it to the end.")],
   "quiz": [{"q": "こんなにたくさん、一人では食べ＿＿＿ない。", "hint": "I can't eat all of this by myself.", "choices": ["きれ", "かけ", "だせ"], "answer": 0, "why": "Can't finish completely: stem + きれない."}]},
  {"id": "tsuzukeru", "title": "V-stem 続ける: keep doing",
   "explain": "Verb stem + 続ける (つづける) = continue doing, keep on: 読み続ける. It's a ru-verb: 続けている, 続けた.",
   "examples": [("毎晩{まいばん}=every night|読み続けて{よみつづけて}=keep reading|いる=am|。", "I keep reading every night.")],
   "quiz": [{"q": "雨が三日間降り＿＿＿＿いる。", "hint": "It has kept raining for three days.", "choices": ["続けて", "かけて", "きって"], "answer": 0, "why": "Keep on: stem + 続ける."}]},
 ],
 "kanji": [
  ("続", "ゾク", "つづ.く,つづ.ける", "continue", [("続ける", "つづける", "to continue"), ("続く", "つづく", "to go on")]),
  ("切", "セツ", "き.る", "cut", [("切る", "きる", "to cut"), ("大切", "たいせつ", "important")]),
  ("途", "ト", "", "route, way", [("途中", "とちゅう", "on the way, midway")]),
  ("約", "ヤク", "", "promise, about", [("約束", "やくそく", "promise")]),
  ("最", "サイ", "もっと.も", "most", [("最初", "さいしょ", "first"), ("最後", "さいご", "last")]),
 ],
 "build": [1, 6],
 "questions": [
  {"q": "サムさんは毎晩何ページずつ読んでいますか。", "en": "How many pages does Sam read each night?", "choices": ["十ページ", "三十ページ", "一ページ"], "answer": 0},
  {"q": "どうしてサムさんは本を最後まで読みたいのですか。", "en": "Why does Sam want to finish the book?", "choices": ["ゆきさんのお母さんと約束したから", "試験があるから", "本が高かったから"], "answer": 0},
  {"q": "本を読み終わったら、サムさんは何をしますか。", "en": "What will Sam do after finishing the book?", "choices": ["手紙を書く", "大阪に行く", "新しい本を買う"], "answer": 0},
 ],
 "talk": "Tell Blip about something you left half-done (～かけ), something you did all the way (～きる), and something you keep doing (～続ける).",
},
{
 "id": "n3-11", "level": "N3", "unit": 11,
 "title": {"ja": "雪だらけの札幌", "en": "Sapporo, covered in snow"},
 "scene": "February. Sam keeps his promise and visits Yuki in Hokkaido during the Sapporo Snow Festival.",
 "lines": [
  "ゆき: ようこそ=welcome|、|札幌{さっぽろ}=Sapporo|^へ=to|！|サム=Sam|、|もう=already|頭{あたま}=head|^が=(subject)|雪{ゆき}だらけ=covered in snow|だ=is|よ=you know|。 >> Welcome to Sapporo! Sam, your head is already covered in snow.",
  "サム: 空港{くうこう}=airport|^から=from|ちょっと=a little|歩{ある}いた=walked|だけ=only|なのに=even though|……|。 >> I only walked a little from the airport...",
  "サム: 天気予報{てんきよほう}=forecast|^では=according to|、|今日{きょう}=today|^は=topic|晴{は}れる=be sunny|はずだった=was supposed to|^のに=but|。 >> According to the forecast, it was supposed to be sunny today.",
  "ゆき: 北海道{ほっかいどう}=Hokkaido|^の=(of)|天気{てんき}=weather|^は=topic|予報{よほう}=forecast|^どおり=as|^に=(in)|ならない=doesn't turn out|^の=(it's that)|。 >> Hokkaido weather doesn't follow the forecast.",
  "ブリップ: 寒{さむ}い=cold|……|。|ブリップ=Blip|^の=(of)|電池{でんち}=battery|^が=(subject)|いつも=usual|^より=than|早{はや}く=quickly|減{へ}っている=is going down|。 >> So cold... Blip's battery is draining faster than usual.",
  "ゆき: 見{み}て=look|、|雪{ゆき}まつり=Snow Festival|^の=(of)|像{ぞう}=statues|！|雪{ゆき}=snow|^で=from|作{つく}った=made|^にしては=for something|、|本当{ほんとう}に=really|細{こま}かい=detailed|でしょう=right|？ >> Look, the Snow Festival statues! For things made of snow, they're really detailed, aren't they?",
  "サム: すごい=amazing|！|あれ=that|^は=topic|大阪城{おおさかじょう}=Osaka Castle|？|雪{ゆき}=snow|^にしては=for|大{おお}きすぎる=too big|よ=you know|！ >> Amazing! Is that Osaka Castle? It's way too big for something made of snow!",
  "ゆき: 自衛隊{じえいたい}=the Self-Defense Forces|^の=(of)|人{ひと}たち=people|^が=(subject)|一か月{いっかげつ}=a month|かけて=spending|作{つく}る=make|^んだって=I hear|。 >> I hear Self-Defense Forces volunteers spend a month building them.",
  "サム: 来{き}て=came|よかった=glad|。|約束{やくそく}どおり=as promised|、|冬{ふゆ}=winter|^に=in|来{き}た=came|よ=you know|。 >> I'm glad I came. As promised, I came in winter.",
 ],
 "grammar": [
  {"id": "darake", "title": "～だらけ: covered in, full of (usually bad)",
   "explain": "Noun + だらけ = covered with or full of something, usually unwanted: 雪だらけ, まちがいだらけ (full of mistakes), 傷だらけ.",
   "examples": [("頭{あたま}=head|^が=(subject)|雪{ゆき}だらけ=covered in snow|だ=is|。", "Your head is covered in snow.")],
   "quiz": [{"q": "この作文はまちがい＿＿＿だ。", "hint": "This essay is full of mistakes.", "choices": ["だらけ", "ばかりで", "っぽい"], "answer": 0, "why": "Full of (unwanted things): だらけ."}]},
  {"id": "ni-shitewa", "title": "～にしては: for (considering)",
   "explain": "Noun or plain form + にしては = considering X, it's surprising: 雪にしては細かい (detailed, for snow). It compares against what you'd expect of X.",
   "examples": [("雪{ゆき}=snow|^で=from|作{つく}った=made|^にしては=for something|、|細{こま}かい=detailed|。", "For something made of snow, it's detailed.")],
   "quiz": [{"q": "初めて作った＿＿＿＿、とてもおいしい。", "hint": "For a first try, it's very tasty.", "choices": ["にしては", "について", "によって"], "answer": 0, "why": "Better than you'd expect of X: にしては."}]},
  {"id": "hazu-datta", "title": "～はずだった: was supposed to (but didn't)",
   "explain": "はず + だった = it was expected, but it didn't happen: 晴れるはずだった (it was supposed to be sunny). Often followed by のに or けど.",
   "examples": [("晴{は}れる=be sunny|はずだった=was supposed to|^のに=but|。", "It was supposed to be sunny, but…")],
   "quiz": [{"q": "電車は七時に着く＿＿＿＿＿のに、まだ来ない。", "hint": "The train was supposed to arrive at seven, but it hasn't come.", "choices": ["はずだった", "ようだった", "そうだった"], "answer": 0, "why": "Expected but didn't happen: はずだった."}]},
 ],
 "kanji": [
  ("港", "コウ", "みなと", "harbor", [("空港", "くうこう", "airport")]),
  ("減", "ゲン", "へ.る", "decrease", [("減る", "へる", "to decrease")]),
  ("細", "サイ", "ほそ.い,こま.かい", "thin, detailed", [("細かい", "こまかい", "detailed"), ("細い", "ほそい", "thin")]),
  ("像", "ゾウ", "", "statue, image", [("像", "ぞう", "statue")]),
  ("報", "ホウ", "", "report", [("天気予報", "てんきよほう", "weather forecast"), ("情報", "じょうほう", "information")]),
 ],
 "build": [2, 8],
 "questions": [
  {"q": "天気予報では、今日はどうなるはずでしたか。", "en": "According to the forecast, what was today supposed to be like?", "choices": ["晴れる", "雪が降る", "雨が降る"], "answer": 0},
  {"q": "雪まつりの像はだれが作りますか。", "en": "Who builds the Snow Festival statues?", "choices": ["自衛隊の人たち", "サムさん", "子どもたち"], "answer": 0},
  {"q": "どうしてブリップの電池が早く減っていますか。", "en": "Why is Blip's battery draining fast?", "choices": ["寒いから", "古いから", "ずっと話しているから"], "answer": 0},
 ],
 "talk": "Describe something covered in or full of something (～だらけ), praise something 'for a beginner' (～にしては), and tell Blip about a plan that didn't work out (～はずだった).",
},
{
 "id": "n3-12", "level": "N3", "unit": 12,
 "title": {"ja": "ブリップのかわりに", "en": "In Blip's place"},
 "scene": "The last night in Sapporo. Blip's battery dies in the cold, and Sam has to find the way back to the hotel on his own.",
 "lines": [
  "ブリップ: 電池{でんち}=battery|^が=(subject)|……|もう=no more|……|。 >> My battery is... almost...",
  "サム: ブリップ=Blip|！|……|だめ=no good|だ=is|、|動{うご}かない=won't move|。|今夜{こんや}=tonight|^は=topic|ブリップ=Blip|^の=(of)|かわりに=instead of|ぼく=I|^が=(subject)|道{みち}=the way|^を=(object)|探{さが}す=will find|。 >> Blip! ...It's no use, it won't move. Tonight I'll find the way instead of Blip.",
  "ゆき: 大丈夫{だいじょうぶ}=okay|？|地図{ちず}=map|^は=topic|日本語{にほんご}=Japanese|だけ=only|だ=is|よ=you know|。 >> Will you be okay? The map is only in Japanese.",
  "サム: ここ=here|まで=this far|来{き}て=having come|、|ゆき=Yuki|^に=(on)|頼{たよ}る=rely|わけにはいかない=can't very well|よ=you know|。 >> Having come this far, I can't very well lean on you.",
  "サム: 駅{えき}=station|^の=(of)|地図{ちず}=map|^の=(of)|とおり=as shown|^に=(in)|行{い}けば=if I go|、|ホテル=hotel|^に=at|着{つ}く=arrive|はず=should|だ=is|。 >> If I follow the map at the station, I should get to the hotel.",
  "サム: 「|北{きた}=north|^へ=to|三百{さんびゃく}メートル=300 meters|、|左{ひだり}=left|^に=(to)|曲{ま}がる=turn|」|。|……|よし=right|、|書{か}いてある=is written|とおり=as|^に=(in)|歩{ある}こう=let's walk|。 >> \"300 meters north, turn left.\" ...Okay, let's walk exactly as it says.",
  "ゆき: すごい=amazing|！|ホテル=hotel|^に=at|着{つ}いた=arrived|ね=huh|。|一年前{いちねんまえ}=a year ago|^の=(of)|サム=Sam|^なら=if it were|、|ぜったい=definitely|迷子{まいご}=lost|^に=(become)|なっていた=would have been|よ=you know|。 >> Amazing! We made it to the hotel. The Sam of a year ago would definitely have gotten lost.",
  "サム: ブリップ=Blip|^の=(of)|かわりに=in place of|、|日本語{にほんご}=Japanese|^が=(subject)|ぼく=me|^を=(object)|助{たす}けてくれた=helped|^んだ=(you see)|。 >> In Blip's place, Japanese helped me.",
  "ブリップ: （充電中{じゅうでんちゅう}=charging）|……|サム=Sam|、|ひとり=alone|^で=by|できた=you did it|^ん=(that)|ですね=right|。|ブリップ=Blip|^は=topic|うれしい=happy|です=am|。 >> (charging) ...Sam, you did it on your own. Blip is happy.",
 ],
 "grammar": [
  {"id": "kawari-ni", "title": "～かわりに: instead of, in place of",
   "explain": "Noun の + かわりに (代わりに) = instead of, standing in for. After a verb it can also mean 'in exchange for': 教えるかわりに (in return for teaching).",
   "examples": [("ブリップ=Blip|^の=(of)|かわりに=instead of|、|ぼく=I|^が=(subject)|探{さが}す=will find|。", "I'll find it instead of Blip.")],
   "quiz": [{"q": "今日は先生の＿＿＿＿＿、田中さんが教えます。", "hint": "Today Tanaka teaches in place of the teacher.", "choices": ["かわりに", "とおりに", "ために"], "answer": 0, "why": "In someone's place: のかわりに."}]},
  {"id": "toori", "title": "～とおり(に): just as, exactly as",
   "explain": "Verb (dictionary or past) + とおりに, or Noun の + とおりに / Noun + どおりに = exactly as: 書いてあるとおりに歩く, 地図のとおりに, 約束どおり.",
   "examples": [("書{か}いてある=is written|とおり=as|^に=(in)|歩{ある}こう=let's walk|。", "Let's walk exactly as it says.")],
   "quiz": [{"q": "先生が言った＿＿＿＿、やってみてください。", "hint": "Try doing it exactly as the teacher said.", "choices": ["とおりに", "かわりに", "ように"], "answer": 0, "why": "Exactly as: とおりに."}]},
  {"id": "wake-niwa-ikanai", "title": "～わけにはいかない: can't very well",
   "explain": "Dictionary form + わけにはいかない = you can't do it, for social or moral reasons (not ability): 頼るわけにはいかない. Negative form + わけにはいかない = have to: 行かないわけにはいかない.",
   "examples": [("ゆき=Yuki|^に=(on)|頼{たよ}る=rely|わけにはいかない=can't very well|。", "I can't very well lean on Yuki.")],
   "quiz": [{"q": "明日は試験だから、遊びに行く＿＿＿＿＿＿＿。", "hint": "I have an exam tomorrow, so I can't very well go out.", "choices": ["わけにはいかない", "わけではない", "わけがない"], "answer": 0, "why": "Not allowed by your own sense of duty: わけにはいかない."}]},
 ],
 "kanji": [
  ("頼", "ライ", "たよ.る,たの.む", "rely, ask", [("頼る", "たよる", "to rely on"), ("頼む", "たのむ", "to ask")]),
  ("曲", "キョク", "ま.がる", "bend, song", [("曲がる", "まがる", "to turn"), ("曲", "きょく", "song")]),
  ("助", "ジョ", "たす.ける", "help", [("助ける", "たすける", "to help")]),
  ("迷", "メイ", "まよ.う", "lose the way", [("迷子", "まいご", "lost child"), ("迷う", "まよう", "to get lost")]),
  ("北", "ホク", "きた", "north", [("北", "きた", "north"), ("北海道", "ほっかいどう", "Hokkaido")]),
 ],
 "build": [3, 7],
 "questions": [
  {"q": "どうしてサムさんが道を探しましたか。", "en": "Why did Sam find the way himself?", "choices": ["ブリップの電池が切れたから", "ゆきさんが忘れたから", "地図が英語だったから"], "answer": 0},
  {"q": "サムさんはどうやってホテルに着きましたか。", "en": "How did Sam get to the hotel?", "choices": ["地図のとおりに歩いた", "タクシーに乗った", "ゆきさんについて行った"], "answer": 0},
  {"q": "ブリップのかわりに、何がサムさんを助けましたか。", "en": "What helped Sam in Blip's place?", "choices": ["日本語", "ゆきさん", "駅員"], "answer": 0},
 ],
 "talk": "Tell Blip about a time you did something in someone's place (～のかわりに), followed instructions exactly (～とおりに), and couldn't very well say no (～わけにはいかない).",
},
]
