# JLPT N4 units: the same cast a few months on. Yuki and Sam now talk casually (plain form) as friends.
# Notation: see build.py. Kanji: (kanji, on, kun, meaning, [(word, reading, gloss)]).

UNITS = [
{
 "id": "n4-01", "level": "N4", "unit": 1,
 "title": {"ja": "日本語が話せるようになった", "en": "I can speak Japanese now"},
 "scene": "A Saturday at the café again. Sam has been studying Japanese with Yomu for three months.",
 "lines": [
  "ゆき: サム=Sam|、|最近{さいきん}=lately|、|日本語{にほんご}=Japanese|^が=(object of ability)|上手{じょうず}になった=got good|ね=right?|。 >> Sam, your Japanese has gotten good lately, hasn't it?",
  "サム: ありがとう=thanks|。|毎日{まいにち}=every day|勉強{べんきょう}している=am studying|んだ=(explaining)|。 >> Thanks. I've been studying every day, you see.",
  "サム: ひらがな=hiragana|^と=and|カタカナ=katakana|^は=topic|もう=already|全部{ぜんぶ}=all|読める{よめる}=can read|よ=you know|。 >> I can already read all the hiragana and katakana.",
  "ゆき: 漢字{かんじ}=kanji|^は=and (as for)|？ >> And kanji?",
  "サム: 漢字{かんじ}=kanji|^は=topic|まだ=still|少{すこ}し=a little|しか=only|読めない{よめない}=can't read|。|でも=but|、|毎日{まいにち}=every day|十{じゅう}=ten|ずつ=each|覚えている{おぼえている}=am memorizing|。 >> I can still read only a few kanji. But I'm learning ten every day.",
  "ゆき: すごい=great|！|じゃあ=then|、|来年{らいねん}=next year|^は=topic|日本{にほん}=Japan|^で=in|話せる{はなせる}=can speak|と思う{とおもう}=I think|。 >> Great! Then I think you'll be able to talk in Japan next year.",
  "サム: 実{じつ}は=actually|、|夏休{なつやす}み=summer vacation|^に=in|日本{にほん}=Japan|^に=to|行{い}こう=let's go / I'll go|と思っている{とおもっている}=I'm thinking|んだ=(explaining)|。 >> Actually, I'm thinking of going to Japan over the summer.",
  "ゆき: 本当{ほんとう}=really|？|私{わたし}=I|^も=too|夏{なつ}=summer|^に=in|帰る{かえる}=go home|から=so|、|いっしょに=together|行{い}こう=let's go|よ=!|！ >> Really? I'm going home in summer too, so let's go together!",
  "ブリップ: ブリップ=Blip|^も=too|行{い}ける=can go|？ >> Can Blip go too?",
  "サム: ブリップ=Blip|^は=topic|かばん=bag|^に=in|入る{はいる}=fit in|から=because|、|大丈夫{だいじょうぶ}=fine|だ=is|と思う{とおもう}=I think|。 >> Blip fits in a bag, so I think it'll be fine.",
 ],
 "grammar": [
  {"id": "potential", "title": "～える / ～られる: can (potential form)",
   "explain": "U-verbs change the last u-sound to e + る: 読む → 読める, 話す → 話せる, 行く → 行ける. Ru-verbs add られる: 食べる → 食べられる (in speech often 食べれる). する → できる, 来る → 来られる. The thing you can do usually takes が.",
   "examples": [("ひらがな=hiragana|^が=(object)|読める{よめる}=can read|。", "I can read hiragana."), ("漢字{かんじ}=kanji|^は=topic|まだ=still|読めない{よめない}=can't read|。", "I can't read kanji yet.")],
   "quiz": [{"q": "日本語が話＿＿。", "hint": "I can speak Japanese.", "choices": ["せる", "される", "させる"], "answer": 0, "why": "話す → 話せる (す → せる)."},
            {"q": "ブリップも行＿＿？", "hint": "Can Blip go too?", "choices": ["ける", "かれる", "こう"], "answer": 0, "why": "行く → 行ける."}]},
  {"id": "to-omou", "title": "～と思う: I think",
   "explain": "Plain form + と思う = I think. After a noun or な-adjective add だ: 大丈夫だと思う. Volitional + と思っている = I'm thinking of doing: 行こうと思っている.",
   "examples": [("来年{らいねん}=next year|^は=topic|話せる{はなせる}=can speak|と思う{とおもう}=I think|。", "I think you'll be able to speak next year.")],
   "quiz": [{"q": "大丈夫＿＿と思う。", "hint": "I think it'll be fine.", "choices": ["だ", "な", "の"], "answer": 0, "why": "Nouns and な-adjectives need だ before と思う."},
            {"q": "日本に行こう＿＿思っている。", "hint": "I'm thinking of going to Japan.", "choices": ["と", "を", "が"], "answer": 0, "why": "と marks what you think."}]},
  {"id": "plain-speech", "title": "Plain speech between friends",
   "explain": "Friends drop です/ます: 勉強しています → 勉強している, 読めます → 読める, 行きましょう → 行こう. んだ (= のです) adds 'you see' when explaining.",
   "examples": [("毎日{まいにち}=every day|勉強{べんきょう}している=am studying|んだ=you see|。", "I've been studying every day, you see.")],
   "quiz": [{"q": "いっしょに行＿＿よ！", "hint": "Let's go together! (casual)", "choices": ["こう", "きます", "って"], "answer": 0, "why": "Casual 'let's': volitional 行こう."}]},
 ],
 "kanji": [
  ("話", "ワ", "はな.す", "talk", [("話す", "はなす", "to speak"), ("電話", "でんわ", "telephone")]),
  ("思", "シ", "おも.う", "think", [("思う", "おもう", "to think")]),
  ("漢", "カン", "", "China (Han)", [("漢字", "かんじ", "kanji")]),
  ("字", "ジ", "あざ", "character, letter", [("漢字", "かんじ", "kanji"), ("文字", "もじ", "letter")]),
  ("夏", "カ", "なつ", "summer", [("夏", "なつ", "summer"), ("夏休み", "なつやすみ", "summer vacation")]),
 ],
 "build": [2, 6],
 "questions": [
  {"q": "サムさんはひらがなが読めますか。", "en": "Can Sam read hiragana?", "choices": ["はい、全部読めます", "いいえ、読めません", "少ししか読めません"], "answer": 0},
  {"q": "サムさんは毎日、漢字をいくつ覚えていますか。", "en": "How many kanji does Sam learn each day?", "choices": ["十", "三", "百"], "answer": 0},
  {"q": "サムさんはいつ日本に行こうと思っていますか。", "en": "When is Sam thinking of going to Japan?", "choices": ["夏休みに", "来週", "冬に"], "answer": 0},
 ],
 "talk": "Tell Blip what you can and can't do in Japanese yet (～られる / ～られない), and one plan you're thinking about (～ようと思っている).",
},
{
 "id": "n4-02", "level": "N4", "unit": 2,
 "title": {"ja": "雨が降ったら", "en": "If it rains"},
 "scene": "Friday night. Yuki and Sam plan a Sunday picnic in Central Park, but the forecast isn't sure.",
 "lines": [
  "ゆき: 日曜日{にちようび}=Sunday|、|セントラルパーク=Central Park|^で=in|ピクニック=picnic|^を=(object)|しない=won't we do?|？ >> Want to have a picnic in Central Park on Sunday?",
  "サム: いいね=sounds good|。|でも=but|、|天気予報{てんきよほう}=weather forecast|^に=(by)|よると=according to|、|雨{あめ}=rain|^が=(subject)|降る{ふる}=fall|かもしれない=might|。 >> Sounds good. But according to the forecast, it might rain.",
  "ゆき: 雨{あめ}=rain|^が=(subject)|降ったら{ふったら}=if it rains|、|美術館{びじゅつかん}=museum|^に=to|行{い}こう=let's go|。 >> If it rains, let's go to a museum.",
  "サム: メトロポリタン美術館{めとろぽりたんびじゅつかん}=the Met|^なら=if it's|、|一日中{いちにちじゅう}=all day|いられる=can stay|ね=right|。 >> If it's the Met, we could stay all day.",
  "ゆき: 晴れれば{はれれば}=if it's sunny|、|公園{こうえん}=park|^で=in|おにぎり=rice balls|^を=(object)|食べよう{たべよう}=let's eat|。|私{わたし}=I|^が=(subject)|作る{つくる}=will make|よ=!|。 >> If it's sunny, let's eat rice balls in the park. I'll make them!",
  "サム: 本当{ほんとう}=really|？|ゆき=Yuki|^の=of|おにぎり=rice balls|、|食べてみたかった{たべてみたかった}=I wanted to try|んだ=you see|。 >> Really? I've wanted to try your rice balls.",
  "ブリップ: 天気{てんき}=weather|^を=(object)|見ると{みると}=when I look|、|日曜日{にちようび}=Sunday|^の=of|朝{あさ}=morning|^は=topic|くもり=cloudy|、|午後{ごご}=afternoon|^は=topic|晴れ{はれ}=sunny|。 >> Looking at the weather, Sunday morning is cloudy and the afternoon sunny.",
  "サム: じゃあ=then|、|午後{ごご}=afternoon|^から=from|行けば{いけば}=if we go|いい=good|ね=right|。 >> Then we should go from the afternoon.",
  "ゆき: そうだね=right|。|駅{えき}=station|^に=at|着いたら{ついたら}=when (you) arrive|、|電話{でんわ}=phone call|して=do|ね=okay?|。 >> Right. Call me when you get to the station, okay?",
 ],
 "grammar": [
  {"id": "tara", "title": "～たら: if / when (then)",
   "explain": "Past た + ら: if A happens, B; or once A is done, B. It works with requests and plans, so it's the everyday conditional: 雨が降ったら, 駅に着いたら電話して.",
   "examples": [("雨{あめ}=rain|^が=(subject)|降ったら{ふったら}=if it rains|、|美術館{びじゅつかん}=museum|^に=to|行{い}こう=let's go|。", "If it rains, let's go to a museum.")],
   "quiz": [{"q": "駅に着い＿＿、電話してね。", "hint": "Call me when you get to the station.", "choices": ["たら", "ば", "と"], "answer": 0, "why": "A request after the condition: たら."},
            {"q": "雨が降っ＿＿、美術館に行こう。", "hint": "If it rains, let's go to a museum.", "choices": ["たら", "て", "たり"], "answer": 0, "why": "降った + ら."}]},
  {"id": "ba", "title": "～ば: if (condition → result)",
   "explain": "U-verbs: u → e + ば (行く → 行けば). Ru-verbs: れば (晴れる → 晴れれば). い-adjectives: ければ (安ければ). ～ばいい = you should / it'd be good to.",
   "examples": [("午後{ごご}=afternoon|^から=from|行けば{いけば}=if we go|いい=good|。", "We should go from the afternoon.")],
   "quiz": [{"q": "晴れ＿＿、公園で食べよう。", "hint": "If it's sunny, let's eat in the park.", "choices": ["れば", "ると", "たり"], "answer": 0, "why": "晴れる → 晴れれば."}]},
  {"id": "nara-to", "title": "～なら and ～と",
   "explain": "なら picks up a topic: 'if it's X (you mean)': メトロポリタン美術館なら. と = whenever / when A, B naturally follows: 見ると (when I look), 右に曲がると駅がある.",
   "examples": [("美術館{びじゅつかん}=museum|^なら=if it's|、|一日中{いちにちじゅう}=all day|いられる=can stay|。", "If it's the museum, we can stay all day.")],
   "quiz": [{"q": "メトロポリタン美術館＿＿、一日中いられるね。", "hint": "If it's the Met, we can stay all day.", "choices": ["なら", "たら", "ので"], "answer": 0, "why": "なら takes up a topic someone mentioned."}]},
 ],
 "kanji": [
  ("降", "コウ", "ふ.る,お.りる", "descend, fall", [("降る", "ふる", "to fall (rain)")]),
  ("館", "カン", "やかた", "building, hall", [("美術館", "びじゅつかん", "art museum"), ("図書館", "としょかん", "library")]),
  ("晴", "セイ", "は.れる", "clear (weather)", [("晴れ", "はれ", "sunny")]),
  ("着", "チャク", "き.る,つ.く", "arrive, wear", [("着く", "つく", "to arrive")]),
  ("駅", "エキ", "", "station", [("駅", "えき", "station")]),
 ],
 "build": [2, 8],
 "questions": [
  {"q": "雨が降ったら、どこに行きますか。", "en": "If it rains, where will they go?", "choices": ["美術館", "公園", "駅"], "answer": 0},
  {"q": "おにぎりはだれが作りますか。", "en": "Who will make the rice balls?", "choices": ["ゆきさん", "サムさん", "ブリップ"], "answer": 0},
  {"q": "日曜日の午後の天気は何ですか。", "en": "What's the weather Sunday afternoon?", "choices": ["晴れ", "雨", "くもり"], "answer": 0},
 ],
 "talk": "Make a weekend plan with Blip using たら and ば: what you'll do if it's sunny and if it rains.",
},
{
 "id": "n4-03", "level": "N4", "unit": 3,
 "title": {"ja": "日本へ行くことにした", "en": "I've decided to go to Japan"},
 "scene": "Sam books his flight. Yuki helps him plan, and they talk about why he's going.",
 "lines": [
  "サム: 決めた{きめた}=decided|！|八月{はちがつ}=August|^に=in|日本{にほん}=Japan|^へ=to|行{い}く=go|ことにした=I decided to|。 >> Decided! I'm going to Japan in August.",
  "ゆき: やった=yay|！|何{なん}の=what for|ために=in order to|行{い}く=go|の=(question)|？ >> Yay! What are you going for?",
  "サム: 秋葉原{あきはばら}=Akihabara|^で=in|古{ふる}い=old|ラジオ=radios|^を=(object)|見{み}る=see|ために=in order to|。|それから=and also|、|日本{にほん}=Japan|^の=of|アマチュア無線{あまちゅあむせん}=ham radio|^の=of|友{とも}だち=friends|^に=(to)|会いたい{あいたい}=want to meet|んだ=you see|。 >> To see old radios in Akihabara. And I want to meet my ham radio friends in Japan.",
  "ゆき: 東京{とうきょう}=Tokyo|^から=from|京都{きょうと}=Kyoto|^まで=to|新幹線{しんかんせん}=bullet train|^で=by|行{い}く=go|つもり=intend|？ >> Do you plan to take the bullet train from Tokyo to Kyoto?",
  "サム: うん=yeah|。|乗{の}ってみたい=want to try riding|。|切符{きっぷ}=ticket|^は=topic|早{はや}く=early|買っておく{かっておく}=buy in advance|。 >> Yeah, I want to try riding it. I'll buy the ticket early.",
  "ゆき: 日本{にほん}=Japan|^で=in|困らない{こまらない}=not get stuck|ように=so that|、|大事{だいじ}な=important|ことば=words|^を=(object)|教えて{おしえて}=teach|あげる=(for you)|。 >> So you don't get stuck in Japan, I'll teach you some important words.",
  "サム: 助かる{たすかる}=that helps|！|毎日{まいにち}=every day|話{はな}す=speak|ように=make a point of|している=am doing|けど=but|、|まだ=still|速{はや}い=fast|日本語{にほんご}=Japanese|^は=topic|わからない=don't understand|。 >> That helps! I try to speak every day, but I still can't follow fast Japanese.",
  "ブリップ: ブリップ=Blip|^が=(subject)|通訳{つうやく}=interpreter|^を=(object)|する=do|ことになった=it's been decided|！ >> It's been decided: Blip will be the interpreter!",
  "ゆき: ブリップ=Blip|、|空港{くうこう}=airport|^で=at|電池{でんち}=battery|^が=(subject)|切{き}れない=won't run out|ように=so that|ね=okay?|。 >> Blip, make sure your battery doesn't run out at the airport, okay?",
 ],
 "grammar": [
  {"id": "koto-ni-suru", "title": "～ことにする / ～ことになる: decide / it's decided",
   "explain": "Dictionary form + ことにした = I decided (my choice). ことになった = it's been decided (by others or circumstances).",
   "examples": [("日本{にほん}=Japan|^へ=to|行{い}く=go|ことにした=I decided|。", "I decided to go to Japan.")],
   "quiz": [{"q": "八月に日本へ行く＿＿＿＿＿。", "hint": "I decided to go to Japan in August (my choice).", "choices": ["ことにした", "ことになった", "ことがある"], "answer": 0, "why": "Your own decision: ことにした."},
            {"q": "ブリップが通訳をする＿＿＿＿＿。", "hint": "It was decided that Blip will interpret.", "choices": ["ことになった", "ことにした", "ことができる"], "answer": 0, "why": "Decided by others: ことになった."}]},
  {"id": "tame-ni", "title": "～ために / ～ように: in order to / so that",
   "explain": "ために = for a goal you act on (見るために). ように = so that a state happens, often with potential or negative verbs (困らないように, 切れないように).",
   "examples": [("古{ふる}い=old|ラジオ=radios|^を=(object)|見{み}る=see|ために=in order to|行{い}く=go|。", "I'm going to see old radios."), ("困らない{こまらない}=not get stuck|ように=so that|教える{おしえる}=teach|。", "I'll teach you so you won't get stuck.")],
   "quiz": [{"q": "ラジオを見る＿＿＿秋葉原に行く。", "hint": "I'll go to Akihabara to see radios.", "choices": ["ために", "ように", "ので"], "answer": 0, "why": "A goal you act on: ために."},
            {"q": "電池が切れない＿＿＿ね。", "hint": "Make sure the battery doesn't run out.", "choices": ["ように", "ために", "から"], "answer": 0, "why": "A state you can't directly control: ように."}]},
  {"id": "te-oku", "title": "～ておく / ～てみる: do in advance / try",
   "explain": "て + おく = do something ahead of time (買っておく). て + みる = try it and see (乗ってみたい).",
   "examples": [("切符{きっぷ}=ticket|^を=(object)|買っておく{かっておく}=buy in advance|。", "I'll buy the ticket ahead of time.")],
   "quiz": [{"q": "新幹線に乗っ＿＿＿たい。", "hint": "I want to try riding the bullet train.", "choices": ["てみ", "てお", "てい"], "answer": 0, "why": "Try: てみる → てみたい."}]},
 ],
 "kanji": [
  ("決", "ケツ", "き.める", "decide", [("決める", "きめる", "to decide")]),
  ("京", "キョウ", "", "capital", [("東京", "とうきょう", "Tokyo"), ("京都", "きょうと", "Kyoto")]),
  ("切", "セツ", "き.る", "cut", [("切符", "きっぷ", "ticket"), ("大切", "たいせつ", "important")]),
  ("早", "ソウ", "はや.い", "early", [("早く", "はやく", "early, quickly")]),
  ("教", "キョウ", "おし.える", "teach", [("教える", "おしえる", "to teach")]),
 ],
 "build": [0, 4],
 "questions": [
  {"q": "サムさんはいつ日本へ行きますか。", "en": "When is Sam going to Japan?", "choices": ["八月", "四月", "十二月"], "answer": 0},
  {"q": "秋葉原で何を見ますか。", "en": "What will he see in Akihabara?", "choices": ["古いラジオ", "新しい車", "映画"], "answer": 0},
  {"q": "通訳をするのはだれですか。", "en": "Who will interpret?", "choices": ["ブリップ", "ゆきさん", "サムさんの友だち"], "answer": 0},
 ],
 "talk": "Tell Blip about a trip you've decided on (～ことにした), why (～ために), and one thing you'll do in advance (～ておく).",
},
{
 "id": "n4-04", "level": "N4", "unit": 4,
 "title": {"ja": "ブリップがこわれちゃった", "en": "Blip broke!"},
 "scene": "Sam's apartment. Blip fell off the desk and won't turn on.",
 "lines": [
  "サム: あっ=oh no|！|ブリップ=Blip|^が=(subject)|机{つくえ}=desk|^から=from|落ちて{おちて}=fell|しまった=(ended up, oops)|！ >> Oh no! Blip fell off the desk!",
  "ゆき: 大丈夫{だいじょうぶ}=okay|？|電気{でんき}=power|^が=(subject)|つかない=won't come on|の=(question)|？ >> Is it okay? Won't the power come on?",
  "サム: ボタン=button|^を=(object)|押しても{おしても}=even if I press|、|つかない=won't turn on|。|こわれちゃった=it's broken (oops)|かな=I wonder|。 >> Even if I press the button, it won't turn on. I wonder if it broke.",
  "ゆき: 電池{でんち}=battery|^を=(object)|入れ替えて{いれかえて}=swap|みたら=if you try|？ >> How about trying to swap the battery?",
  "サム: そうだね=good idea|。|新{あたら}しい=new|電池{でんち}=battery|^は=topic|引き出し{ひきだし}=drawer|^に=in|入れて{いれて}=put|ある=(has been done)|。 >> Good idea. There are new batteries put away in the drawer.",
  "サム: よし=okay|、|入れた{いれた}=put in|。|スイッチ=switch|^を=(object)|入{い}れる=turn on|と=when|…|。 >> Okay, they're in. When I turn on the switch…",
  "ブリップ: ピピッ=beep beep|！|あれ=huh|？|ブリップ=Blip|^は=topic|どうして=why|床{ゆか}=floor|^に=on|いる=am|の=(question)|？ >> Beep beep! Huh? Why is Blip on the floor?",
  "ゆき: よかった=phew|！|ドア=door|^が=(subject)|開いて{あいて}=was open|いて=and|、|風{かぜ}=wind|^で=by|落ちた{おちた}=fell|みたい=seems|。 >> Phew! It seems the door was open and you fell because of the wind.",
  "サム: 窓{まど}=window|^も=too|開けた{あけた}=opened|まま=left as is|だった=was|。|閉めて{しめて}=close|おく=(for now)|ね=okay|。 >> I'd left the window open too. I'll close it.",
 ],
 "grammar": [
  {"id": "te-shimau", "title": "～てしまう / ～ちゃう: oops, ended up",
   "explain": "てしまう shows something happened that you regret, or that it's completely done. Casual: ～ちゃう / ～じゃう: こわれちゃった (it broke, ugh).",
   "examples": [("机{つくえ}=desk|^から=from|落ちて{おちて}=fall|しまった=(oops)|。", "It fell off the desk (oh no).")],
   "quiz": [{"q": "ブリップがこわれ＿＿＿た。", "hint": "Blip broke (casual, oops).", "choices": ["ちゃっ", "てい", "てあっ"], "answer": 0, "why": "てしまった → ちゃった."}]},
  {"id": "transitive-pairs", "title": "開ける・開く: doing vs happening",
   "explain": "Transitive verbs take を (someone does it): 窓を開ける, 電池を入れる. Intransitive take が (it happens): ドアが開く, 電気がつく. Learn them in pairs: 開ける/開く, 閉める/閉まる, つける/つく, 入れる/入る, 落とす/落ちる.",
   "examples": [("ドア=door|^が=(subject)|開いて{あいて}=was open|いた=(state)|。", "The door was open."), ("窓{まど}=window|^を=(object)|閉める{しめる}=close|。", "I'll close the window.")],
   "quiz": [{"q": "電気＿つかない。", "hint": "The power won't come on.", "choices": ["が", "を", "で"], "answer": 0, "why": "つく is intransitive: が."},
            {"q": "窓＿開けたままだった。", "hint": "I'd left the window open.", "choices": ["を", "が", "に"], "answer": 0, "why": "開ける is transitive: を."}]},
  {"id": "te-aru", "title": "～てある / ～たまま: has been done / left as is",
   "explain": "Transitive verb + てある = someone did it on purpose and the result remains: 電池が入れてある. たまま = left in that state: 開けたまま.",
   "examples": [("電池{でんち}=batteries|^は=topic|引き出し{ひきだし}=drawer|^に=in|入れて{いれて}=put|ある=(done, still there)|。", "The batteries have been put in the drawer.")],
   "quiz": [{"q": "新しい電池は引き出しに入れて＿＿。", "hint": "New batteries are (put) in the drawer.", "choices": ["ある", "いる", "おく"], "answer": 0, "why": "Someone put them there and they're still there: てある."}]},
 ],
 "kanji": [
  ("落", "ラク", "お.ちる", "fall", [("落ちる", "おちる", "to fall")]),
  ("電", "デン", "", "electricity", [("電池", "でんち", "battery"), ("電気", "でんき", "electricity")]),
  ("開", "カイ", "あ.ける,ひら.く", "open", [("開ける", "あける", "to open")]),
  ("風", "フウ", "かぜ", "wind", [("風", "かぜ", "wind")]),
  ("窓", "ソウ", "まど", "window", [("窓", "まど", "window")]),
 ],
 "build": [0, 8],
 "questions": [
  {"q": "ブリップはどこから落ちましたか。", "en": "Where did Blip fall from?", "choices": ["机から", "窓から", "かばんから"], "answer": 0},
  {"q": "新しい電池はどこにありましたか。", "en": "Where were the new batteries?", "choices": ["引き出しに", "机の上に", "床に"], "answer": 0},
  {"q": "どうしてブリップは落ちましたか。", "en": "Why did Blip fall?", "choices": ["風で", "ゆきさんが押したから", "電池がなかったから"], "answer": 0},
 ],
 "talk": "Tell Blip about something that went wrong recently (～てしまった / ～ちゃった) and what you did about it.",
},
{
 "id": "n4-05", "level": "N4", "unit": 5,
 "title": {"ja": "おみやげをもらった", "en": "I got a souvenir"},
 "scene": "Yuki's mother visits New York from Osaka and brings presents.",
 "lines": [
  "ゆき: 母{はは}=my mother|^が=(subject)|大阪{おおさか}=Osaka|^から=from|来て{きて}=came|、|おみやげ=souvenirs|^を=(object)|くれた=gave me|。 >> My mom came from Osaka and gave me souvenirs.",
  "ゆき: これ=this|、|サム=Sam|^に=to|あげる=I'll give|。|母{はは}=my mother|^から=from|だ=is|よ=you know|。 >> This is for you, Sam. It's from my mom.",
  "サム: えっ=what|、|ぼく=me|^に=to|？|ありがとう=thank you|！|開けて{あけて}=open|も=even|いい=okay|？ >> For me? Thank you! Can I open it?",
  "ゆき: もちろん=of course|。|大阪{おおさか}=Osaka|^の=of|おかし=sweets|だ=is|よ=you know|。 >> Of course. They're sweets from Osaka.",
  "サム: お母{かあ}さん=your mother|^に=to|お礼{おれい}=thanks|^を=(object)|言いたい{いいたい}=want to say|。|日本語{にほんご}=Japanese|^で=in|手紙{てがみ}=letter|^を=(object)|書{か}く=write|^の=(the act of)|^を=(object)|手伝って{てつだって}=help|くれない=won't you (for me)?|？ >> I want to thank your mother. Could you help me write a letter in Japanese?",
  "ゆき: いい=sure|よ=!|。|母{はは}=my mother|^も=too|喜ぶ{よろこぶ}=will be happy|と思う{とおもう}=I think|。 >> Sure. I think my mom will be happy too.",
  "サム: 前{まえ}=before|^に=(time)|ゆき=Yuki|^に=by (from)|日本語{にほんご}=Japanese|^を=(object)|教えて{おしえて}=teach|もらった=received (the favor)|から=because|、|今度{こんど}=next time|^は=topic|ぼく=I|^が=(subject)|英語{えいご}=English|^を=(object)|教えて{おしえて}=teach|あげる=(for her)|。 >> Since you taught me Japanese before, this time I'll teach your mom English.",
  "ブリップ: ブリップ=Blip|^も=too|おかし=sweets|^を=(object)|もらえる=can receive|？ >> Can Blip get a sweet too?",
  "ゆき: ブリップ=Blip|^は=topic|食べられない{たべられない}=can't eat|でしょう=right?|！ >> Blip, you can't eat, can you!",
 ],
 "grammar": [
  {"id": "ageru-kureru", "title": "あげる・くれる: giving out, giving in",
   "explain": "あげる = I (or anyone) give to someone else, outward. くれる = someone gives to me or my group, inward. 母がくれた (my mom gave me), サムにあげる (I'll give to Sam).",
   "examples": [("母{はは}=my mother|^が=(subject)|おみやげ=souvenirs|^を=(object)|くれた=gave me|。", "My mom gave me souvenirs."), ("これ=this|、|サム=Sam|^に=to|あげる=give|。", "I'll give this to Sam.")],
   "quiz": [{"q": "母がおみやげを＿＿＿。", "hint": "My mom gave me souvenirs.", "choices": ["くれた", "あげた", "もらった"], "answer": 0, "why": "Toward me: くれる."},
            {"q": "これ、サムに＿＿＿。", "hint": "I'll give this to Sam.", "choices": ["あげる", "くれる", "もらう"], "answer": 0, "why": "From me outward: あげる."}]},
  {"id": "morau", "title": "もらう: receive",
   "explain": "もらう = I receive (the giver takes に or から). Look at it from the receiver's side: ゆきにもらった = I got it from Yuki.",
   "examples": [("ゆき=Yuki|^に=from|おかし=sweets|^を=(object)|もらった=received|。", "I got sweets from Yuki.")],
   "quiz": [{"q": "ゆき＿おかしをもらった。", "hint": "I got sweets from Yuki.", "choices": ["に", "を", "が"], "answer": 0, "why": "The giver takes に (or から) with もらう."}]},
  {"id": "te-favor", "title": "～てあげる・～てくれる・～てもらう: favors",
   "explain": "Put a giving verb after て and it becomes a favor: 教えてあげる (I'll teach you, as a favor), 手伝ってくれない？ (could you help me?), 教えてもらった (I had someone teach me).",
   "examples": [("手伝って{てつだって}=help|くれない=won't you (for me)|？", "Could you help me?"), ("日本語{にほんご}=Japanese|^を=(object)|教えて{おしえて}=teach|もらった=got (the favor)|。", "I had someone teach me Japanese.")],
   "quiz": [{"q": "手紙を書くのを手伝って＿＿＿？", "hint": "Could you help me write a letter?", "choices": ["くれない", "あげない", "もらう"], "answer": 0, "why": "Asking for a favor to me: てくれない?"}]},
 ],
 "kanji": [
  ("母", "ボ", "はは", "mother", [("母", "はは", "(my) mother"), ("お母さん", "おかあさん", "mother")]),
  ("手", "シュ", "て", "hand", [("手紙", "てがみ", "letter"), ("手伝う", "てつだう", "to help")]),
  ("紙", "シ", "かみ", "paper", [("手紙", "てがみ", "letter"), ("紙", "かみ", "paper")]),
  ("英", "エイ", "", "England, brilliant", [("英語", "えいご", "English")]),
  ("度", "ド", "たび", "degree, time", [("今度", "こんど", "next time")]),
 ],
 "build": [1, 6],
 "questions": [
  {"q": "おみやげは何でしたか。", "en": "What was the souvenir?", "choices": ["大阪のおかし", "手紙", "ラジオ"], "answer": 0},
  {"q": "サムさんはお母さんに何をしたいですか。", "en": "What does Sam want to do for Yuki's mother?", "choices": ["日本語で手紙を書きたい", "大阪へ行きたい", "おかしを作りたい"], "answer": 0},
  {"q": "今度、サムさんはだれに英語を教えますか。", "en": "Who will Sam teach English to?", "choices": ["ゆきさんのお母さん", "ブリップ", "ゆきさん"], "answer": 0},
 ],
 "talk": "Tell Blip about a present you gave or got recently: who gave what to whom (あげる・くれる・もらう).",
},
{
 "id": "n4-06", "level": "N4", "unit": 6,
 "title": {"ja": "雪が降るそうだ", "en": "I hear it's going to snow"},
 "scene": "December. A storm is coming to New York. Sam reads the news; Yuki looks out the window.",
 "lines": [
  "サム: ニュース=news|^に=(by)|よると=according to|、|今夜{こんや}=tonight|、|大雪{おおゆき}=heavy snow|^が=(subject)|降る{ふる}=falls|そうだ=I hear|。 >> According to the news, heavy snow is going to fall tonight.",
  "ゆき: 本当{ほんとう}=really|？|空{そら}=sky|^が=(subject)|暗くて{くらくて}=dark and|、|今{いま}=now|^に=(any moment)|も=even|降り{ふり}=fall|そう=looks like|だ=is|ね=right|。 >> Really? The sky is dark; it looks like it could start any minute.",
  "サム: 地下鉄{ちかてつ}=subway|^も=too|止まる{とまる}=stop|かもしれない=might|。 >> The subway might stop too.",
  "ゆき: あした=tomorrow|^の='s|授業{じゅぎょう}=classes|^は=topic|休み{やすみ}=canceled|らしい=apparently|。|先生{せんせい}=teacher|^から=from|メール=email|^が=(subject)|来た{きた}=came|。 >> Apparently tomorrow's classes are canceled. I got an email from my teacher.",
  "サム: じゃあ=then|、|今日{きょう}=today|^の=(of)|うちに=while (it lasts)|食べ物{たべもの}=food|^を=(object)|買って{かって}=buy|おこう=let's (in advance)|。 >> Then let's buy food while we can today.",
  "ゆき: スーパー=supermarket|^は=topic|人{ひと}=people|^が=(subject)|多{おお}そう=looks crowded|だ=is|けど=but|…|。 >> The supermarket looks crowded, but…",
  "ブリップ: 窓{まど}=window|^の=of|外{そと}=outside|^を=(object)|見{み}ると=when I look|、|もう=already|白{しろ}い=white|ような=like|…|あ=ah|、|雪{ゆき}=snow|だ=is|！ >> Looking out the window, it already looks kind of white… ah, it's snow!",
  "ゆき: きれい=pretty|！|ニューヨーク=New York|^の='s|雪{ゆき}=snow|^は=topic|東京{とうきょう}=Tokyo|より=than|多い{おおい}=more|みたい=seems|ね=right|。 >> Pretty! New York seems to get more snow than Tokyo.",
 ],
 "grammar": [
  {"id": "sou-two", "title": "降るそうだ vs 降りそうだ",
   "explain": "Plain form + そうだ = I heard (hearsay): 降るそうだ (I hear it'll snow). Stem + そう = looks like (my own eyes): 降りそうだ (looks like it's about to). Adjectives: 多そう (looks crowded), いい → よさそう.",
   "examples": [("大雪{おおゆき}=heavy snow|^が=(subject)|降る{ふる}=falls|そうだ=I hear|。", "I hear heavy snow will fall."), ("今{いま}にも=any moment|降り{ふり}=fall|そう=looks like|だ=is|。", "It looks like it'll fall any minute.")],
   "quiz": [{"q": "ニュースによると、雪が降る＿＿＿。", "hint": "According to the news, it'll snow.", "choices": ["そうだ", "そう", "ようだ"], "answer": 0, "why": "Hearsay from the news: plain form + そうだ."},
            {"q": "空が暗い。雨が降り＿＿だ。", "hint": "The sky is dark. Looks like rain.", "choices": ["そう", "そうだ", "らしい"], "answer": 0, "why": "What you see: stem + そう."}]},
  {"id": "rashii-mitai", "title": "らしい・みたい・ようだ: seems",
   "explain": "らしい = apparently (from what I've heard/read). みたい (casual) / ようだ (formal) = it seems, from what I see or infer.",
   "examples": [("授業{じゅぎょう}=classes|^は=topic|休み{やすみ}=canceled|らしい=apparently|。", "Apparently classes are canceled.")],
   "quiz": [{"q": "東京より雪が多い＿＿＿ね。", "hint": "It seems there's more snow than in Tokyo (casual).", "choices": ["みたい", "そう", "かな"], "answer": 0, "why": "Casual 'seems': みたい."}]},
  {"id": "kamoshirenai", "title": "～かもしれない: might",
   "explain": "Plain form + かもしれない = might, maybe. Nouns drop だ: 雪かもしれない. Casual: かも.",
   "examples": [("地下鉄{ちかてつ}=subway|^も=too|止まる{とまる}=stop|かもしれない=might|。", "The subway might stop too.")],
   "quiz": [{"q": "地下鉄も止まる＿＿＿＿＿＿。", "hint": "The subway might stop too.", "choices": ["かもしれない", "そうだ", "ことにする"], "answer": 0, "why": "Might: かもしれない."}]},
 ],
 "kanji": [
  ("雪", "セツ", "ゆき", "snow", [("雪", "ゆき", "snow"), ("大雪", "おおゆき", "heavy snow")]),
  ("夜", "ヤ", "よる", "night", [("今夜", "こんや", "tonight"), ("夜", "よる", "night")]),
  ("空", "クウ", "そら,から", "sky, empty", [("空", "そら", "sky"), ("空港", "くうこう", "airport")]),
  ("止", "シ", "と.まる", "stop", [("止まる", "とまる", "to stop")]),
  ("物", "ブツ,モツ", "もの", "thing", [("食べ物", "たべもの", "food"), ("買い物", "かいもの", "shopping")]),
 ],
 "build": [0, 2],
 "questions": [
  {"q": "今夜、何が降りますか。", "en": "What's falling tonight?", "choices": ["雪", "雨", "何も降らない"], "answer": 0},
  {"q": "あしたの授業はどうなりますか。", "en": "What about tomorrow's classes?", "choices": ["休み", "いつもどおり", "オンライン"], "answer": 0},
  {"q": "二人は今日、何をしますか。", "en": "What will the two do today?", "choices": ["食べ物を買う", "東京へ行く", "地下鉄に乗る"], "answer": 0},
 ],
 "talk": "Tell Blip the weather you've heard about (～そうだ) and what the sky looks like now (～そう).",
},
{
 "id": "n4-07", "level": "N4", "unit": 7,
 "title": {"ja": "先生にほめられた", "en": "My teacher praised me"},
 "scene": "Yuki comes back from her university presentation. Sam wants to hear how it went.",
 "lines": [
  "サム: 発表{はっぴょう}=presentation|^は=topic|どうだった=how was it|？ >> How was the presentation?",
  "ゆき: 先生{せんせい}=teacher|^に=by|ほめられた=was praised|！|「=“|わかりやすい=easy to understand|」=”|^って=(they said)|。 >> My teacher praised me! She said it was easy to understand.",
  "サム: すごい=great|！|何{なに}=what|^を=(object)|発表{はっぴょう}した=presented|の=(question)|？ >> Great! What did you present on?",
  "ゆき: ニューヨーク=New York|^の=of|地下鉄{ちかてつ}=subway|^について=about|。|でも=but|、|始まる{はじまる}=starts|前{まえ}=before|^に=(time)|、|となり=next to me|^の=of|人{ひと}=person|^に=by|足{あし}=foot|^を=(object)|ふまれて=got stepped on|、|痛{いた}かった=it hurt|。 >> About the New York subway. But before it started, the person next to me stepped on my foot and it hurt.",
  "サム: それは=that's|大変{たいへん}=awful|だった=was|ね=right|。 >> That's awful.",
  "ゆき: それに=on top of that|、|先生{せんせい}=teacher|^は=topic|学生{がくせい}=students|^に=(make)|二回{にかい}=twice|練習{れんしゅう}させた=made practice|から=so|、|ちょっと=a little|疲れた{つかれた}=got tired|。 >> And the teacher made the students rehearse twice, so I'm a bit tired.",
  "サム: ぼく=I|^も=too|子{こ}どものころ=as a kid|、|毎日{まいにち}=every day|ピアノ=piano|^を=(object)|練習{れんしゅう}させられた=was made to practice|よ=you know|。 >> When I was a kid, I was made to practice piano every day too.",
  "ブリップ: ブリップ=Blip|^は=topic|毎日{まいにち}=every day|サム=Sam|^に=by|そうじ=cleaning|^を=(object)|させられる=am made to do|！ >> Blip is made to do the cleaning by Sam every day!",
  "サム: それ=that|^は=topic|ブリップ=Blip|^が=(subject)|やりたい=wants to do|^って=(said)|言った{いった}=said|から=because|でしょう=right?|！ >> That's because you said you wanted to!",
 ],
 "grammar": [
  {"id": "passive", "title": "Passive ～られる: was done (to me)",
   "explain": "U-verbs: u → a + れる (ふむ → ふまれる). Ru-verbs: られる (ほめる → ほめられる). The doer takes に. Japanese also uses it when something annoying happens to you: 足をふまれた (someone stepped on my foot).",
   "examples": [("先生{せんせい}=teacher|^に=by|ほめられた=was praised|。", "I was praised by my teacher."), ("足{あし}=foot|^を=(object)|ふまれた=got stepped on|。", "Someone stepped on my foot.")],
   "quiz": [{"q": "先生＿ほめられた。", "hint": "I was praised by my teacher.", "choices": ["に", "を", "が"], "answer": 0, "why": "The doer in a passive takes に."},
            {"q": "となりの人に足をふま＿＿。", "hint": "The person next to me stepped on my foot.", "choices": ["れた", "せた", "った"], "answer": 0, "why": "ふむ → ふまれる (passive)."}]},
  {"id": "causative", "title": "Causative ～させる: make / let (someone) do",
   "explain": "U-verbs: u → a + せる (行く → 行かせる). Ru-verbs: させる. する → させる. Context decides make or let. させてください = please let me.",
   "examples": [("学生{がくせい}=students|^に=(make)|練習{れんしゅう}させた=made practice|。", "(The teacher) made the students practice.")],
   "quiz": [{"q": "先生は学生に二回練習＿＿＿。", "hint": "The teacher made the students practice twice.", "choices": ["させた", "された", "した"], "answer": 0, "why": "Make someone do: させる."}]},
  {"id": "causative-passive", "title": "～させられる: be made to do",
   "explain": "Causative + passive = made to do something (unwillingly): 練習させられた (I was made to practice).",
   "examples": [("ピアノ=piano|^を=(object)|練習{れんしゅう}させられた=was made to practice|。", "I was made to practice piano.")],
   "quiz": [{"q": "子どものころ、ピアノを練習＿＿＿＿＿。", "hint": "As a kid I was made to practice piano.", "choices": ["させられた", "させた", "された"], "answer": 0, "why": "Made to do (unwillingly): させられる."}]},
 ],
 "kanji": [
  ("発", "ハツ", "", "start, emit", [("発表", "はっぴょう", "presentation")]),
  ("始", "シ", "はじ.まる", "begin", [("始まる", "はじまる", "to begin")]),
  ("足", "ソク", "あし,た.りる", "foot, enough", [("足", "あし", "foot, leg")]),
  ("習", "シュウ", "なら.う", "learn", [("練習", "れんしゅう", "practice"), ("習う", "ならう", "to learn")]),
  ("回", "カイ", "まわ.る", "times, turn", [("二回", "にかい", "twice")]),
 ],
 "build": [1, 6],
 "questions": [
  {"q": "先生はゆきさんの発表について何と言いましたか。", "en": "What did the teacher say about Yuki's presentation?", "choices": ["わかりやすい", "長すぎる", "おもしろくない"], "answer": 0},
  {"q": "発表の前に何がありましたか。", "en": "What happened before the presentation?", "choices": ["足をふまれた", "雨が降った", "電車が止まった"], "answer": 0},
  {"q": "サムさんは子どものころ、何を練習させられましたか。", "en": "What was Sam made to practice as a kid?", "choices": ["ピアノ", "日本語", "サッカー"], "answer": 0},
 ],
 "talk": "Tell Blip about a time you were praised (～られた) and something you were made to do as a kid (～させられた).",
},
{
 "id": "n4-08", "level": "N4", "unit": 8,
 "title": {"ja": "お待ちしておりました", "en": "We've been expecting you"},
 "scene": "August, Tokyo. Sam checks into a small hotel in Asakusa. Polite Japanese everywhere.",
 "lines": [
  "ホテル: いらっしゃいませ=welcome|。|お待ちしておりました{おまちしておりました}=we've been expecting you|。 >> Welcome. We've been expecting you.",
  "サム: こんばんは=good evening|。|予約{よやく}した=reserved|サム・ミラー=Sam Miller|です=am|。 >> Good evening. I'm Sam Miller; I have a reservation.",
  "ホテル: ミラー=Miller|様{さま}=Mr. (very polite)|ですね=right|。|パスポート=passport|^を=(object)|拝見{はいけん}します=I'll (humbly) look|。 >> Mr. Miller, yes. May I see your passport?",
  "ホテル: お部屋{おへや}=your room|^は=topic|五階{ごかい}=fifth floor|で=and|ございます=is (very polite)|。|朝食{ちょうしょく}=breakfast|^は=topic|七時{しちじ}=seven o'clock|^から=from|召し上がれます{めしあがれます}=you can eat (honorific)|。 >> Your room is on the fifth floor. Breakfast is served from seven.",
  "サム: すみません=excuse me|、|近{ちか}く=nearby|^に=in|コンビニ=convenience store|^は=topic|ありますか=is there|。 >> Excuse me, is there a convenience store nearby?",
  "ホテル: はい=yes|、|ホテル=hotel|^を=(object)|出て{でて}=leave and|右{みぎ}=right|^に=to|曲がる{まがる}=turn|と=when|、|すぐ=right away|ございます=there is (very polite)|。 >> Yes, go out of the hotel and turn right; it's right there.",
  "サム: ありがとうございます=thank you very much|。|あと=also|、|友達{ともだち}=friend|^が=(subject)|明日{あした}=tomorrow|来る{くる}=comes|んですが=and so…|、|ロビー=lobby|^で=in|待って{まって}=wait|いても=even if|いい=okay|ですか=is it?|。 >> Thank you very much. Also, a friend is coming tomorrow; may they wait in the lobby?",
  "ホテル: もちろん=of course|でございます=is (very polite)|。|ごゆっくり=please relax|お過ごしください{おすごしください}=please spend (your time)|。 >> Of course. Please enjoy your stay.",
  "ブリップ: 小{ちい}さい=small|声{こえ}=voice|^で=in|、|サム=Sam|、|みんな=everyone|とても=very|ていねい=polite|だ=is|ね=right|。 >> (whispering) Sam, everyone's so polite.",
 ],
 "grammar": [
  {"id": "honorific", "title": "尊敬語: raising the guest",
   "explain": "Staff raise the customer with honorific verbs: 召し上がる (eat), いらっしゃる (be/come), おっしゃる (say), or お + stem + ください: お過ごしください. 様 is a very polite さん.",
   "examples": [("朝食{ちょうしょく}=breakfast|^は=topic|七時{しちじ}=7:00|^から=from|召し上がれます{めしあがれます}=you can eat|。", "You can have breakfast from seven.")],
   "quiz": [{"q": "朝食は七時から＿＿＿＿＿＿。", "hint": "You can have breakfast from seven (honorific).", "choices": ["召し上がれます", "いただけます", "食べさせます"], "answer": 0, "why": "The guest eats: honorific 召し上がる."}]},
  {"id": "humble", "title": "謙譲語: lowering yourself",
   "explain": "Staff lower their own actions: お待ちしております (we've been waiting), 拝見します (I'll look), いたします (I'll do), 申します (my name is). おる = humble いる.",
   "examples": [("お待ちしておりました=we've been expecting you|。", "We've been expecting you."), ("パスポート=passport|^を=(object)|拝見{はいけん}します=I'll look|。", "May I see your passport?")],
   "quiz": [{"q": "パスポートを＿＿＿＿します。", "hint": "I'll (humbly) look at your passport.", "choices": ["拝見", "ご覧", "見せ"], "answer": 0, "why": "Your own action, humble: 拝見する."}]},
  {"id": "gozaimasu", "title": "ございます: very polite 'is / there is'",
   "explain": "ございます = あります, でございます = です, used in shops and hotels.",
   "examples": [("お部屋{おへや}=your room|^は=topic|五階{ごかい}=5th floor|で=(is)|ございます=(very polite)|。", "Your room is on the fifth floor.")],
   "quiz": [{"q": "コンビニはすぐ＿＿＿＿＿。", "hint": "There's a convenience store right there (very polite).", "choices": ["ございます", "いらっしゃいます", "まいります"], "answer": 0, "why": "Very polite 'there is' for things: ございます."}]},
 ],
 "kanji": [
  ("予", "ヨ", "", "beforehand", [("予約", "よやく", "reservation"), ("予定", "よてい", "plan")]),
  ("約", "ヤク", "", "promise, about", [("予約", "よやく", "reservation"), ("約束", "やくそく", "promise")]),
  ("部", "ブ", "", "part, section", [("部屋", "へや", "room")]),
  ("屋", "オク", "や", "roof, shop", [("部屋", "へや", "room"), ("本屋", "ほんや", "bookstore")]),
  ("階", "カイ", "", "floor, story", [("五階", "ごかい", "fifth floor")]),
 ],
 "build": [1, 4],
 "questions": [
  {"q": "サムさんの部屋は何階ですか。", "en": "What floor is Sam's room on?", "choices": ["五階", "七階", "一階"], "answer": 0},
  {"q": "朝食は何時からですか。", "en": "What time does breakfast start?", "choices": ["七時", "五時", "九時"], "answer": 0},
  {"q": "コンビニはどこにありますか。", "en": "Where's the convenience store?", "choices": ["ホテルを出て右", "駅の中", "五階"], "answer": 0},
 ],
 "talk": "Role-play: Blip is the hotel clerk. Check in politely, ask where something is, and ask if your friend may wait in the lobby.",
},
]
