# More JLPT N4 units (9–12): side stories from the spring before the Japan trip. Notation: see build.py.
# Grammar ids match data/grammar.json, so each point links to its full lesson.

UNITS = [
{
 "id": "n4-09", "level": "N4", "unit": 9,
 "title": {"ja": "電車が止まったので", "en": "Because the train stopped"},
 "scene": "A rainy spring evening. Sam is on his way to dinner with Yuki in Brooklyn when the L train stops.",
 "lines": [
  "サム: もしもし=hello|、|ゆき=Yuki|？|ごめん=sorry|、|電車{でんしゃ}=train|^が=(subject)|止{と}まった=stopped|^ので=so|、|遅{おく}れる=I'll be late|。 >> Hello, Yuki? Sorry, the train stopped, so I'll be late.",
  "ゆき: え=what|、|また=again|？|昨日{きのう}=yesterday|^も=also|止{と}まった=stopped|^のに=even though|。 >> What, again? It already stopped yesterday!",
  "サム: 駅員{えきいん}=station staff|^に=(to)|聞{き}いてみた=tried asking|けど=but|、|いつ=when|動{うご}く=will move|^か=(whether)|わからない=don't know|んだって=they say|。 >> I tried asking the staff, but they say they don't know when it'll move.",
  "ゆき: バス=bus|^で=by|来{き}てみたら=why not try coming|？|地図{ちず}=map|^で=on|調{しら}べてみる=I'll look it up|ね=okay|。 >> Why not try coming by bus? I'll look it up on the map.",
  "ゆき: B48=B48|^の=(of)|バス=bus|^が=(subject)|五分{ごふん}=five minutes|^で=in|来る{くる}=comes|よ=you know|。 >> The B48 bus comes in five minutes.",
  "サム: ありがとう=thanks|。|雨{あめ}=rain|^が=(subject)|強{つよ}い=strong|^ので=so|、|バス停{ばすてい}=bus stop|^まで=to|走{はし}る=will run|よ=(you know)|。 >> Thanks. It's raining hard, so I'll run to the bus stop.",
  "ブリップ: かさ=umbrella|^を=(object)|持{も}ってきた=brought|^のに=even though|、|サム=Sam|^は=topic|使{つか}わない=doesn't use|^の=(question)|？ >> We brought an umbrella, so why aren't you using it, Sam?",
  "サム: あ=oh|、|忘{わす}れてた=forgot|。|使{つか}ってみる=I'll try using it|よ=(you know)|……|。 >> Oh, I forgot. I'll use it...",
  "ゆき: レストラン=restaurant|^は=topic|予約{よやく}してある=is booked|^ので=so|、|大丈夫{だいじょうぶ}=it's fine|。|ゆっくり=take your time|来{き}て=come|ね=okay|。 >> The restaurant is booked, so it's fine. Take your time.",
 ],
 "grammar": [
  {"id": "node", "title": "～ので: because (softer)",
   "explain": "Plain form + ので gives a reason more softly than から, so it suits apologies and excuses. Nouns and な-adjectives take な: 日曜日なので.",
   "examples": [("電車{でんしゃ}=train|^が=(subject)|止{と}まった=stopped|^ので=so|、|遅{おく}れる=I'll be late|。", "The train stopped, so I'll be late.")],
   "quiz": [{"q": "雨が強い＿＿、タクシーで行きます。", "hint": "It's raining hard, so I'll take a taxi.", "choices": ["ので", "のに", "まで"], "answer": 0, "why": "A soft reason: ので."},
            {"q": "今日は日曜日＿＿＿、休みです。", "hint": "Today is Sunday, so I'm off.", "choices": ["なので", "だので", "ので"], "answer": 0, "why": "Noun + なので."}]},
  {"id": "noni", "title": "～のに: even though (and I'm not happy about it)",
   "explain": "Plain form + のに = even though, with surprise or a complaint. Ending a sentence with のに sounds like 'and yet…!'. Nouns and な-adjectives: なのに.",
   "examples": [("かさ=umbrella|^を=(object)|持{も}ってきた=brought|^のに=even though|、|使{つか}わない=don't use|。", "You brought an umbrella, but you don't use it.")],
   "quiz": [{"q": "たくさん勉強した＿＿、試験に落ちた。", "hint": "I studied a lot, but I failed the exam.", "choices": ["のに", "ので", "から"], "answer": 0, "why": "An unexpected, unwelcome result: のに."}]},
  {"id": "te-miru", "title": "V-てみる: try doing",
   "explain": "て-form + みる = do it and see how it goes. ～てみたら？ = why not try it?",
   "examples": [("駅員{えきいん}=staff|^に=(to)|聞{き}いてみた=tried asking|。", "I tried asking the staff."), ("バス=bus|^で=by|来{き}てみたら=why not try coming|？", "Why not try coming by bus?")],
   "quiz": [{"q": "このラーメン、食べ＿＿＿？", "hint": "Want to try this ramen?", "choices": ["てみる", "ておく", "てある"], "answer": 0, "why": "Try it and see: てみる."}]},
 ],
 "kanji": [
  ("動", "ドウ", "うご.く", "move", [("動く", "うごく", "to move"), ("自動", "じどう", "automatic")]),
  ("強", "キョウ", "つよ.い", "strong", [("強い", "つよい", "strong"), ("勉強", "べんきょう", "study")]),
  ("走", "ソウ", "はし.る", "run", [("走る", "はしる", "to run")]),
  ("持", "ジ", "も.つ", "hold", [("持つ", "もつ", "to hold"), ("持ってくる", "もってくる", "to bring")]),
  ("使", "シ", "つか.う", "use", [("使う", "つかう", "to use")]),
 ],
 "build": [0, 5],
 "questions": [
  {"q": "どうしてサムさんは遅れますか。", "en": "Why will Sam be late?", "choices": ["電車が止まったので", "雨が強いので", "道がわからないので"], "answer": 0},
  {"q": "ゆきさんはサムさんに何をしてみたらと言いましたか。", "en": "What did Yuki suggest Sam try?", "choices": ["バスで来ること", "タクシーで来ること", "歩いて来ること"], "answer": 0},
  {"q": "サムさんはかさを持っていましたか。", "en": "Did Sam have an umbrella?", "choices": ["はい、でも使わなかった", "いいえ、なかった", "はい、ずっと使っていた"], "answer": 0},
 ],
 "talk": "Call Blip to say you'll be late and why (～ので), complain about something with ～のに, and suggest Blip try something (～てみたら？).",
},
{
 "id": "n4-10", "level": "N4", "unit": 10,
 "title": {"ja": "ラジオを作っているところ", "en": "In the middle of building a radio"},
 "scene": "Saturday afternoon. Yuki drops by while Sam is building a radio kit that just arrived from Japan.",
 "lines": [
  "ゆき: こんにちは=hello|。|何{なに}=what|^を=(object)|している=are doing|^の=(question)|？ >> Hi. What are you doing?",
  "サム: 今{いま}=right now|、|ラジオ=radio|^を=(object)|作{つく}っているところ=in the middle of making|。|昨日{きのう}=yesterday|届{とど}いたばかり=only just arrived|^の=(that)|キット=kit|なんだ=it's|。 >> I'm in the middle of building a radio. It's a kit that only arrived yesterday.",
  "ゆき: 説明書{せつめいしょ}=instructions|^は=topic|英語{えいご}=English|？ >> Are the instructions in English?",
  "サム: ううん=no|、|日本語{にほんご}=Japanese|。|字{じ}=letters|^が=(subject)|小{ちい}さくて=small and|、|読{よ}みにくい=hard to read|よ=you know|。 >> No, Japanese. The letters are tiny and hard to read.",
  "ゆき: 見{み}せて=show me|。|……|あ=ah|、|ここ=here|^に=(at)|「|はんだ付け{はんだづけ}=soldering|^を=(object)|する=do|」|^と=(quote)|書{か}いてある=is written|よ=you know|。 >> Let me see. ...Ah, here it says \"solder this.\"",
  "サム: ちょうど=just now|そこ=that part|^を=(object)|やったところ=just did|だ=is|よ=you know|。|この=this|はんだごて=soldering iron|^は=topic|軽{かる}くて=light and|使{つか}いやすい=easy to use|。 >> I just did that part. This soldering iron is light and easy to use.",
  "ブリップ: ブリップ=Blip|^も=also|手伝{てつだ}う=will help|！|……|あつっ=ow, hot|！ >> Blip will help too! ...Ow, hot!",
  "サム: ブリップ=Blip|、|それ=that|^は=topic|使{つか}ったばかり=just used|だ=is|から=so|、|まだ=still|熱{あつ}い=hot|よ=you know|！ >> Blip, I just used that, so it's still hot!",
  "ゆき: できたら=when it's done|、|日本{にほん}=Japan|^の=(of)|ラジオ=radio|^を=(object)|聞{き}こう=let's listen|ね=okay|。 >> When it's done, let's listen to Japanese radio.",
 ],
 "grammar": [
  {"id": "tokoro", "title": "V-るところ / ているところ / たところ: about to / in the middle of / just did",
   "explain": "ところ (a place) also marks a moment. Dictionary form + ところ = about to; ている + ところ = right in the middle of it; た + ところ = just finished.",
   "examples": [("ラジオ=radio|^を=(object)|作{つく}っているところ=in the middle of making|だ=is|。", "I'm in the middle of building a radio."), ("ちょうど=just now|やったところ=just did|だ=is|。", "I just did it.")],
   "quiz": [{"q": "今から出かける＿＿＿です。", "hint": "I'm just about to go out.", "choices": ["ところ", "ばかり", "まま"], "answer": 0, "why": "About to: dictionary form + ところ."},
            {"q": "今、ごはんを食べて＿＿ところです。", "hint": "I'm in the middle of eating.", "choices": ["いる", "いた", "いく"], "answer": 0, "why": "In the middle of: ているところ."}]},
  {"id": "bakari", "title": "V-たばかり: only just did",
   "explain": "た-form + ばかり = it only just happened, as the speaker feels it (it can be days ago). たところ is stricter: this very moment.",
   "examples": [("昨日{きのう}=yesterday|届{とど}いたばかり=only just arrived|^の=(that)|キット=kit|。", "A kit that only arrived yesterday.")],
   "quiz": [{"q": "日本に来た＿＿＿なので、まだ日本語が下手です。", "hint": "I've only just come to Japan, so my Japanese is still poor.", "choices": ["ばかり", "ところ", "まま"], "answer": 0, "why": "Only just (it feels recent): たばかり."}]},
  {"id": "yasui-nikui", "title": "V-やすい / V-にくい: easy to / hard to",
   "explain": "Verb stem + やすい = easy to do; + にくい = hard to do. Both change like い-adjectives: 読みにくくて.",
   "examples": [("字{じ}=letters|^が=(subject)|小{ちい}さくて=small and|読{よ}みにくい=hard to read|。", "The letters are small and hard to read."), ("軽{かる}くて=light and|使{つか}いやすい=easy to use|。", "It's light and easy to use.")],
   "quiz": [{"q": "このペンは書き＿＿＿。", "hint": "This pen is easy to write with.", "choices": ["やすい", "にくい", "すぎ"], "answer": 0, "why": "Easy to: stem + やすい."}]},
 ],
 "kanji": [
  ("作", "サク", "つく.る", "make", [("作る", "つくる", "to make")]),
  ("昨", "サク", "", "previous", [("昨日", "きのう", "yesterday")]),
  ("英", "エイ", "", "England, excellent", [("英語", "えいご", "English")]),
  ("軽", "ケイ", "かる.い", "light (weight)", [("軽い", "かるい", "light")]),
  ("手", "シュ", "て", "hand", [("手", "て", "hand"), ("手伝う", "てつだう", "to help")]),
 ],
 "build": [3, 7],
 "questions": [
  {"q": "サムさんは今、何をしていますか。", "en": "What is Sam doing right now?", "choices": ["ラジオを作っています", "ラジオを聞いています", "説明書を書いています"], "answer": 0},
  {"q": "説明書はどうして読みにくいですか。", "en": "Why are the instructions hard to read?", "choices": ["字が小さいから", "英語だから", "長いから"], "answer": 0},
  {"q": "どうしてはんだごてはまだ熱いですか。", "en": "Why is the soldering iron still hot?", "choices": ["使ったばかりだから", "こわれたから", "新しいから"], "answer": 0},
 ],
 "talk": "Tell Blip what you're in the middle of (～ているところ), something you only just did (～たばかり), and one thing that's easy or hard to do (～やすい / ～にくい).",
},
{
 "id": "n4-11", "level": "N4", "unit": 11,
 "title": {"ja": "毎朝読むようにしている", "en": "I make a point of reading every morning"},
 "scene": "Sunday morning at the café. Yuki catches Sam reading the news on his phone. In Japanese.",
 "lines": [
  "ゆき: サム=Sam|、|日本語{にほんご}=Japanese|^の=(of)|ニュース=news|^が=(subject)|読{よ}めるようになった=became able to read|^の=(question)|？ >> Sam, you can read Japanese news now?",
  "サム: 全部{ぜんぶ}=all of it|^は=topic|まだ=still|無理{むり}=impossible|。|でも=but|、|毎朝{まいあさ}=every morning|一{ひと}つ=one|読{よ}むようにしている=make a point of reading|んだ=(you see)|。 >> Not all of it yet. But I make a point of reading one article every morning.",
  "ゆき: えらい=impressive|ね=huh|。|漢字{かんじ}=kanji|^は=topic|大変{たいへん}じゃない=isn't it tough|？ >> Impressive. Isn't the kanji tough?",
  "サム: 最近{さいきん}=lately|^は=topic|、|知{し}らない=unknown|漢字{かんじ}=kanji|^も=even|意味{いみ}=meaning|^が=(subject)|わかるようになった=came to understand|。 >> Lately I've started to get the meaning even of kanji I don't know.",
  "ゆき: 部首{ぶしゅ}=radicals|^を=(object)|覚{おぼ}えた=learned|から=because|でしょう=right|。|それなら=if so|、|もっと=more|読{よ}めるはず=should be able to read|だ=is|よ=you know|。 >> It's because you learned the radicals, right? Then you should be able to read even more.",
  "サム: あと=also|、|寝{ね}る=sleep|前{まえ}=before|^に=at|スマホ=phone|^を=(object)|見{み}ないようにしている=try not to look at|。 >> Also, I try not to look at my phone before bed.",
  "ブリップ: でも=but|、|昨日{きのう}=yesterday|^の=(of)|夜{よる}=night|、|サム=Sam|^は=topic|二時{にじ}=two o'clock|^まで=until|ゲーム=games|^を=(object)|していた=was doing|よ=you know|。 >> But last night Sam was playing games until two.",
  "サム: ブリップ=Blip|！|……|今夜{こんや}=tonight|^は=topic|早{はや}く=early|寝{ね}るようにする=will make sure to sleep|よ=(promise)|。 >> Blip! ...Tonight I'll make sure to go to bed early.",
  "ゆき: 試験{しけん}=the exam|^は=topic|七月{しちがつ}=July|^の=(of)|はず=should be|だ=is|から=so|、|がんばって=do your best|ね=okay|。 >> The exam should be in July, so do your best.",
 ],
 "grammar": [
  {"id": "you-ni-naru", "title": "V-るようになる: come to (be able to)",
   "explain": "Dictionary or potential form + ようになる = a change that happened over time: 読めるようになった (I've become able to read). For stopping: なくなる.",
   "examples": [("ニュース=news|^が=(subject)|読{よ}めるようになった=became able to read|。", "I've become able to read the news.")],
   "quiz": [{"q": "毎日練習して、泳げる＿＿＿なりました。", "hint": "I practiced every day and became able to swim.", "choices": ["ように", "ために", "ことに"], "answer": 0, "why": "A change over time: ようになる."}]},
  {"id": "you-ni-suru", "title": "V-るようにする: make a point of",
   "explain": "Dictionary form + ようにする = make an effort to do it. ないようにする = try not to. ようにしている = a habit you keep up.",
   "examples": [("毎朝{まいあさ}=every morning|読{よ}むようにしている=make a point of reading|。", "I make a point of reading every morning."), ("スマホ=phone|^を=(object)|見{み}ないようにしている=try not to look at|。", "I try not to look at my phone.")],
   "quiz": [{"q": "健康のために、毎日歩く＿＿＿しています。", "hint": "For my health, I make a point of walking every day.", "choices": ["ように", "ことに", "ために"], "answer": 0, "why": "A habit you work at: ようにしている."}]},
  {"id": "hazu", "title": "～はずだ: should be, is expected to",
   "explain": "Plain form + はず = it should be so, judging from what you know (not a wild guess). Nouns take の: 七月のはず; な-adjectives take な. はずがない = it can't be.",
   "examples": [("もっと=more|読{よ}めるはず=should be able to read|だ=is|。", "You should be able to read more.")],
   "quiz": [{"q": "田中さんは今日来る＿＿です。メールが来ました。", "hint": "Tanaka should come today. I got an email.", "choices": ["はず", "べき", "そう"], "answer": 0, "why": "Expected, from what you know: はず."}]},
 ],
 "kanji": [
  ("意", "イ", "", "mind, meaning", [("意味", "いみ", "meaning")]),
  ("味", "ミ", "あじ", "taste", [("意味", "いみ", "meaning"), ("味", "あじ", "flavor")]),
  ("試", "シ", "ため.す", "try, test", [("試験", "しけん", "exam")]),
  ("験", "ケン", "", "test", [("試験", "しけん", "exam"), ("経験", "けいけん", "experience")]),
  ("知", "チ", "し.る", "know", [("知る", "しる", "to know")]),
 ],
 "build": [5, 7],
 "questions": [
  {"q": "サムさんは毎朝何をするようにしていますか。", "en": "What does Sam make a point of doing every morning?", "choices": ["ニュースを一つ読む", "漢字を十書く", "早く起きる"], "answer": 0},
  {"q": "サムさんは寝る前に何をしないようにしていますか。", "en": "What does Sam try not to do before bed?", "choices": ["スマホを見る", "コーヒーを飲む", "ゲームを買う"], "answer": 0},
  {"q": "試験はいつのはずですか。", "en": "When should the exam be?", "choices": ["七月", "八月", "来週"], "answer": 0},
 ],
 "talk": "Tell Blip something you've become able to do (～ようになった), a habit you keep (～ようにしている), and something that should happen soon (～はずだ).",
},
{
 "id": "n4-12", "level": "N4", "unit": 12,
 "title": {"ja": "来てほしいんだけど", "en": "I'd like you to come"},
 "scene": "Sam's ham radio club meets on Thursday night. He wants Yuki there to say hello to Japan on the air.",
 "lines": [
  "サム: ゆき=Yuki|、|木曜日{もくようび}=Thursday|^に=on|無線{むせん}=ham radio|クラブ=club|^に=to|来{き}てほしい=want you to come|んだけど=(asking)|。 >> Yuki, I'd like you to come to my ham radio club on Thursday.",
  "ゆき: 何時{なんじ}=what time|？|行{い}けるかどうか=whether I can go|、|予定{よてい}=schedule|^を=(object)|見{み}てみる=I'll check|。 >> What time? I'll check my schedule to see whether I can make it.",
  "サム: 七時{しちじ}=seven|^から=from|だ=is|けど=but|、|六時半{ろくじはん}=six thirty|^までに=by|来{き}てくれる=could you come|？|日本{にほん}=Japan|^と=with|話{はな}す=talk|んだ=(you see)|。 >> It starts at seven, but could you come by six thirty? We're going to talk to Japan.",
  "ゆき: 日本{にほん}=Japan|^と=with|？|本当{ほんとう}に=really|つながるかどうか=whether it connects|わからない=don't know|でしょう=right|？ >> With Japan? You don't know whether it'll really connect, right?",
  "サム: うん=yeah|、|天気{てんき}=weather|^で=by|変{か}わる=it changes|。|でも=but|、|つながったら=if it connects|、|日本語{にほんご}=Japanese|^で=in|あいさつ=hello|^を=(object)|してほしい=want you to do|んだ=(you see)|。 >> Yeah, it depends on the weather. But if it connects, I'd like you to say hello in Japanese.",
  "ゆき: いい=okay|よ=sure|。|仕事{しごと}=work|^は=topic|六時{ろくじ}=six|^までに=by|終{お}わる=finishes|はず=should|だ=is|から=so|。 >> Sure. My work should be over by six.",
  "ブリップ: ブリップ=Blip|^も=also|マイク=microphone|^で=on|話{はな}してもいい=may talk|？ >> Can Blip talk on the microphone too?",
  "サム: だめ=no|。|免許{めんきょ}=license|^が=(subject)|ない=don't have|^と=if|、|話{はな}してはいけない=mustn't talk|んだ=(you see)|。 >> No. Without a license you're not allowed to talk on the air.",
  "ゆき: じゃあ=then|、|ブリップ=Blip|^には=(as for)|聞{き}いていてほしい=want you to listen|な=I'd like|。 >> Then, Blip, I'd like you to just listen.",
 ],
 "grammar": [
  {"id": "hoshii-te", "title": "V-てほしい: I want you to",
   "explain": "て-form + ほしい = I want someone else to do it. The person takes に: ゆきに来てほしい. ～てほしいんだけど softens it into a request.",
   "examples": [("クラブ=club|^に=to|来{き}てほしい=want you to come|。", "I want you to come to the club.")],
   "quiz": [{"q": "母に料理を教えて＿＿＿。", "hint": "I want my mom to teach me to cook.", "choices": ["ほしい", "たい", "みる"], "answer": 0, "why": "Someone else acts: てほしい. たい is for yourself."}]},
  {"id": "ka-dou-ka", "title": "～かどうか: whether or not",
   "explain": "Plain form + かどうか = whether or not, inside a bigger sentence: 行けるかどうかわからない. With a question word, use just か: 何時か.",
   "examples": [("行{い}けるかどうか=whether I can go|、|見{み}てみる=I'll check|。", "I'll check whether I can go.")],
   "quiz": [{"q": "明日晴れる＿＿＿＿、わかりません。", "hint": "I don't know whether it'll be sunny tomorrow.", "choices": ["かどうか", "のに", "ので"], "answer": 0, "why": "Whether or not: かどうか."}]},
  {"id": "made-ni", "title": "～までに: by (a deadline)",
   "explain": "まで = until (keeps going); までに = by, no later than. 六時までに来て (come by six) vs 六時まで待つ (wait until six).",
   "examples": [("六時半{ろくじはん}=six thirty|^までに=by|来{き}てくれる=could you come|？", "Could you come by six thirty?")],
   "quiz": [{"q": "金曜日＿＿＿レポートを出してください。", "hint": "Please hand in the report by Friday.", "choices": ["までに", "まで", "から"], "answer": 0, "why": "A deadline: までに."}]},
 ],
 "kanji": [
  ("終", "シュウ", "お.わる", "end", [("終わる", "おわる", "to end")]),
  ("事", "ジ", "こと", "thing, matter", [("仕事", "しごと", "work"), ("事", "こと", "thing")]),
  ("当", "トウ", "あ.たる", "hit, right", [("本当", "ほんとう", "true")]),
  ("曜", "ヨウ", "", "weekday", [("木曜日", "もくようび", "Thursday")]),
  ("変", "ヘン", "か.わる", "change", [("変わる", "かわる", "to change")]),
 ],
 "build": [1, 5],
 "questions": [
  {"q": "クラブは何時からですか。", "en": "What time does the club start?", "choices": ["七時", "六時半", "六時"], "answer": 0},
  {"q": "サムさんはゆきさんに何をしてほしいですか。", "en": "What does Sam want Yuki to do?", "choices": ["日本語であいさつする", "マイクを買う", "ブリップと話す"], "answer": 0},
  {"q": "どうしてブリップはマイクで話してはいけませんか。", "en": "Why can't Blip talk on the microphone?", "choices": ["免許がないから", "声が小さいから", "日本語ができないから"], "answer": 0},
 ],
 "talk": "Ask Blip to do two things for you (～てほしい), say you're not sure whether you can come (～かどうか), and set a deadline (～までに).",
},
]
