# JLPT N5 units: Yuki (a Japanese student in New York), Sam (an American radio engineer) and Blip (Sam's robot).
# Notation: see build.py. Kanji: (kanji, on, kun, meaning, [(word, reading, gloss)]).
SAN = "さん=Mr./Ms. (polite title)"
DESU = "です=is / am / are (polite)"

UNITS = [
{
 "id": "n5-01", "level": "N5", "unit": 1,
 "title": {"ja": "はじめまして", "en": "Nice to meet you"},
 "scene": "A café near Washington Square, New York. Sam sits down next to Yuki.",
 "lines": [
  f"サム: はじめまして=nice to meet you (first time)|。|サム=Sam|{DESU}|。 >> Nice to meet you. I'm Sam.",
  f"ゆき: はじめまして=nice to meet you|。|ゆき=Yuki|{DESU}|。|よろしく=please treat me kindly|おねがいします=please (polite request)|。 >> Nice to meet you. I'm Yuki. Pleased to meet you.",
  f"サム: ゆき=Yuki|{SAN}|^は=topic: as for …|学生{{がくせい}}=student|{DESU}|^か=question marker (?)|。 >> Are you a student, Yuki?",
  f"ゆき: はい=yes|、|学生{{がくせい}}=student|{DESU}|。|ニューヨーク=New York|大学{{だいがく}}=university|^の='s / of|学生{{がくせい}}=student|{DESU}|。 >> Yes, I'm a student. A student at New York University.",
  f"サム: 日本人{{にほんじん}}=Japanese (person)|{DESU}|^か=question marker|。 >> Are you Japanese?",
  f"ゆき: はい=yes|、|日本人{{にほんじん}}=Japanese (person)|{DESU}|。|サム=Sam|{SAN}|^は=and you? (as for Sam…)|？ >> Yes, I'm Japanese. And you, Sam?",
  f"サム: 私{{わたし}}=I, me|^は=topic|アメリカ=America|人{{じん}}=person (nationality)|{DESU}|。|学生{{がくせい}}=student|じゃありません=am not (polite)|。 >> I'm American. I'm not a student.",
  "ゆき: そうですか=I see / is that so|。|お=(polite prefix)|しごと=job, work|^は=topic|？ >> I see. And your job?",
  f"サム: エンジニア=engineer|{DESU}|。|ラジオ=radio|^の=of|エンジニア=engineer|{DESU}|。 >> I'm an engineer. A radio engineer.",
  "ゆき: へえ=oh, wow|、|ラジオ=radio|！ >> Oh wow, radio!",
  "ブリップ: ピピッ=(beep beep)|！|はじめまして=nice to meet you|！ >> Beep beep! Nice to meet you!",
  f"ゆき: あれ=huh? (surprise)|？|これ=this|^は=topic|何{{なん}}=what|{DESU}|^か=question|。 >> Huh? What is this?",
  f"サム: ブリップ=Blip|{DESU}|。|私{{わたし}}=I|^の=my ('s)|ロボット=robot|{DESU}|。 >> It's Blip. My robot.",
  f"ゆき: よろしく=nice to meet you|、|ブリップ=Blip|{SAN}|！ >> Nice to meet you, Blip!",
 ],
 "grammar": [
  {"id": "wa-desu", "title": "X は Y です: X is Y",
   "explain": "は (written ha, read wa) marks the topic: what the sentence is about. です at the end makes it a polite statement, like 'is / am / are'. Japanese drops 'I' when it's obvious: 学生です alone means 'I'm a student'.",
   "examples": [(f"私{{わたし}}=I|^は=topic|学生{{がくせい}}=student|{DESU}|。", "I am a student.")],
   "quiz": [{"q": "ゆきさん＿学生です。", "hint": "Yuki is a student.", "choices": ["は", "の", "か"], "answer": 0, "why": "は marks the topic: as for Yuki, (she) is a student."},
            {"q": "サムさんはエンジニア＿＿。", "hint": "Sam is an engineer.", "choices": ["です", "か", "の"], "answer": 0, "why": "です ends a polite statement."}]},
  {"id": "ka", "title": "～ですか: asking a question",
   "explain": "Put か at the end and a sentence becomes a question: no change in word order. Answer with はい (yes) or いいえ (no).",
   "examples": [(f"日本人{{にほんじん}}=Japanese|{DESU}|^か=?|。", "Are you Japanese?")],
   "quiz": [{"q": "学生です＿。", "hint": "Are you a student?", "choices": ["か", "は", "の"], "answer": 0, "why": "か at the end turns it into a question."}]},
  {"id": "ja-arimasen", "title": "～じゃありません: is not",
   "explain": "To say 'is not', swap です for じゃありません (spoken) or ではありません (formal). You'll also hear じゃないです.",
   "examples": [("学生{がくせい}=student|じゃありません=am not|。", "I'm not a student.")],
   "quiz": [{"q": "サムさんは学生＿＿＿＿。", "hint": "Sam is not a student.", "choices": ["じゃありません", "です", "ですか"], "answer": 0, "why": "じゃありません is the polite negative of です."}]},
  {"id": "no", "title": "A の B: A's B, B of A",
   "explain": "の links two nouns; the first describes the second. 私のロボット = my robot, ラジオのエンジニア = radio engineer.",
   "examples": [(f"私{{わたし}}=I|^の='s|ロボット=robot|{DESU}|。", "It's my robot.")],
   "quiz": [{"q": "ラジオ＿エンジニアです。", "hint": "I'm a radio engineer.", "choices": ["の", "は", "か"], "answer": 0, "why": "の connects ラジオ (radio) to エンジニア (engineer)."}]},
 ],
 "kanji": [
  ("私", "シ", "わたし,わたくし", "I, private", [("私", "わたし", "I")]),
  ("学", "ガク", "まな.ぶ", "study, learning", [("学生", "がくせい", "student"), ("大学", "だいがく", "university")]),
  ("生", "セイ,ショウ", "い.きる,う.まれる", "life, birth", [("学生", "がくせい", "student"), ("先生", "せんせい", "teacher")]),
  ("大", "ダイ,タイ", "おお.きい", "big", [("大学", "だいがく", "university"), ("大きい", "おおきい", "big")]),
  ("日", "ニチ,ジツ", "ひ,か", "day, sun", [("日本", "にほん", "Japan"), ("毎日", "まいにち", "every day")]),
  ("本", "ホン", "もと", "book, origin", [("日本", "にほん", "Japan"), ("本", "ほん", "book")]),
  ("人", "ジン,ニン", "ひと", "person", [("日本人", "にほんじん", "Japanese person"), ("人", "ひと", "person")]),
  ("何", "カ", "なに,なん", "what", [("何", "なん", "what")]),
 ],
 "build": [6, 12],
 "questions": [
  {"q": "サムさんは何人ですか。", "en": "What nationality is Sam?", "choices": ["アメリカ人", "日本人", "ロボット"], "answer": 0},
  {"q": "ゆきさんは何ですか。", "en": "What is Yuki?", "choices": ["学生", "エンジニア", "先生"], "answer": 0},
  {"q": "ブリップは何ですか。", "en": "What is Blip?", "choices": ["サムさんのロボット", "ゆきさんの本", "ラジオ"], "answer": 0},
 ],
 "talk": "Introduce yourself to Blip in Japanese: your name, whether you're a student, and your job or nationality.",
},
{
 "id": "n5-02", "level": "N5", "unit": 2,
 "title": {"ja": "これは何ですか", "en": "What is this?"},
 "scene": "Yuki visits Sam's apartment in Queens. Every shelf is full of radios.",
 "lines": [
  "ゆき: わあ=wow|、|すごい=amazing|！ >> Wow, amazing!",
  f"ゆき: これ=this (near me)|^は=topic|何{{なん}}=what|{DESU}|^か=?|。 >> What is this?",
  f"サム: それ=that (near you)|^は=topic|SDR=SDR (software-defined radio)|{DESU}|。|ソフトウェア=software|^の=of|ラジオ=radio|{DESU}|。 >> That's an SDR. A software radio.",
  f"ゆき: あれ=that (over there)|^も=also, too|ラジオ=radio|{DESU}|^か=?|。 >> Is that over there a radio too?",
  f"サム: いいえ=no|、|あれ=that (over there)|^は=topic|ラジオ=radio|じゃありません=is not|。|アンテナ=antenna|{DESU}|。 >> No, that's not a radio. It's an antenna.",
  f"ゆき: この=this … (+ noun)|本{{ほん}}=book|^は=topic|サム=Sam|{SAN}|^の='s (one)|{DESU}|^か=?|。 >> Is this book yours, Sam?",
  f"サム: はい=yes|、|私{{わたし}}=I|^の=my|本{{ほん}}=book|{DESU}|。|ラジオ=radio|^の=about|本{{ほん}}=book|{DESU}|。 >> Yes, it's my book. A book about radio.",
  "ゆき: その=that … (+ noun, near you)|時計{とけい}=clock, watch|^は=and …?|？ >> And that watch?",
  f"サム: これ=this|^は=topic|日本{{にほん}}=Japan|^の='s|時計{{とけい}}=watch|{DESU}|。|母{{はは}}=my mother|^の='s (one)|{DESU}|。 >> This is a Japanese watch. It's my mother's.",
  f"ブリップ: あの=that … (+ noun, over there)|かさ=umbrella|^は=topic|ゆき=Yuki|{SAN}|^の='s (one)|{DESU}|^か=?|。 >> Is that umbrella over there yours, Yuki?",
  f"ゆき: はい=yes|、|私{{わたし}}=I|^の=my|かさ=umbrella|{DESU}|。|ありがとう=thank you|。 >> Yes, it's my umbrella. Thank you.",
  f"ゆき: ブリップ=Blip|{SAN}|^も=also|ラジオ=radio|{DESU}|^か=?|。 >> Blip, are you a radio too?",
  f"ブリップ: はい=yes|！|ブリップ=Blip|^も=also|ラジオ=radio|{DESU}|。|ピピッ=(beep beep)|！ >> Yes! Blip is a radio too. Beep beep!",
 ],
 "grammar": [
  {"id": "ko-so-a", "title": "これ・それ・あれ: this, that, that over there",
   "explain": "Japanese points with three words: これ (near me), それ (near you), あれ (far from both of us). The question word is どれ (which one).",
   "examples": [(f"それ=that|^は=topic|アンテナ=antenna|{DESU}|。", "That (near you) is an antenna.")],
   "quiz": [{"q": "（far from both）＿＿はラジオじゃありません。", "hint": "That over there is not a radio.", "choices": ["あれ", "これ", "それ"], "answer": 0, "why": "あれ points at something far from both speakers."}]},
  {"id": "kono", "title": "この・その・あの + noun",
   "explain": "Before a noun, use この / その / あの instead: この本 (this book), その時計 (that watch), あの かさ (that umbrella over there). これ stands alone; この always needs a noun.",
   "examples": [(f"この=this|本{{ほん}}=book|^は=topic|私{{わたし}}=I|^の=mine|{DESU}|。", "This book is mine.")],
   "quiz": [{"q": "＿＿時計は母のです。", "hint": "This watch is my mother's.", "choices": ["この", "これ", "あれ"], "answer": 0, "why": "Before a noun (時計), use この."}]},
  {"id": "no-pronoun", "title": "～の: whose (the noun can disappear)",
   "explain": "サムさんのです means 'it's Sam's': the thing itself is understood. だれの (whose) asks who owns it.",
   "examples": [(f"これ=this|^は=topic|母{{はは}}=mother|^の='s|{DESU}|。", "This is my mother's.")],
   "quiz": [{"q": "このかさはゆきさん＿です。", "hint": "This umbrella is Yuki's.", "choices": ["の", "は", "も"], "answer": 0, "why": "の = 's; the umbrella is understood."}]},
  {"id": "mo", "title": "～も: also, too",
   "explain": "も replaces は (or が) to mean 'also': ブリップもラジオです = Blip is a radio too.",
   "examples": [(f"私{{わたし}}=I|^も=also|学生{{がくせい}}=student|{DESU}|。", "I'm a student too.")],
   "quiz": [{"q": "あれ＿ラジオですか。", "hint": "Is that a radio too?", "choices": ["も", "の", "か"], "answer": 0, "why": "も = also."}]},
 ],
 "kanji": [
  ("時", "ジ", "とき", "time, hour", [("時計", "とけい", "watch, clock"), ("何時", "なんじ", "what time")]),
  ("母", "ボ", "はは", "mother", [("母", "はは", "(my) mother")]),
  ("本", "ホン", "もと", "book, origin", [("本", "ほん", "book")]),
  ("今", "コン,キン", "いま", "now", [("今", "いま", "now")]),
 ],
 "build": [4, 8],
 "questions": [
  {"q": "SDRは何ですか。", "en": "What is an SDR?", "choices": ["ソフトウェアのラジオ", "アンテナ", "時計"], "answer": 0},
  {"q": "時計はだれのですか。", "en": "Whose is the watch?", "choices": ["サムさんのお母さんの", "ゆきさんの", "ブリップの"], "answer": 0},
  {"q": "かさはだれのですか。", "en": "Whose is the umbrella?", "choices": ["ゆきさんの", "サムさんの", "母の"], "answer": 0},
 ],
 "talk": "Point at three things around you and ask Blip これは何ですか。Then say whose they are with ～のです.",
},
{
 "id": "n5-03", "level": "N5", "unit": 3,
 "title": {"ja": "毎朝", "en": "Every morning"},
 "scene": "Yuki and Sam compare their mornings over video chat.",
 "lines": [
  f"ゆき: サム=Sam|{SAN}|^は=topic|毎朝{{まいあさ}}=every morning|何時{{なんじ}}=what time|^に=at (time)|起きます{{おきます}}=get up|^か=?|。 >> Sam, what time do you get up every morning?",
  "サム: 六時{ろくじ}=six o'clock|^に=at|起きます{おきます}=get up|。 >> I get up at six.",
  f"ゆき: はやい=early|{DESU}|ね=right? (shared feeling)|！|朝{{あさ}}ごはん=breakfast|^を=(object)|食べます{{たべます}}=eat|^か=?|。 >> That's early! Do you eat breakfast?",
  "サム: はい=yes|、|パン=bread|^を=(object)|食べます{たべます}=eat|。|コーヒー=coffee|^を=(object)|飲みます{のみます}=drink|。 >> Yes, I eat bread. I drink coffee.",
  "ゆき: 私{わたし}=I|^は=topic|朝{あさ}ごはん=breakfast|^を=(object)|食べません{たべません}=don't eat|。 >> I don't eat breakfast.",
  f"サム: ええっ=what?!|、|どうして=why|{DESU}|^か=?|。 >> What? Why?",
  "ゆき: 時間{じかん}=time|^が=(subject)|ありません=there isn't|。 >> I don't have time.",
  "サム: そうですか=I see|。|毎朝{まいあさ}=every morning|どこ=where|^へ=to (direction)|行きます{いきます}=go|^か=?|。 >> I see. Where do you go every morning?",
  "ゆき: 大学{だいがく}=university|^へ=to|行きます{いきます}=go|。|図書館{としょかん}=library|^で=at (place of action)|本{ほん}=book|^を=(object)|読みます{よみます}=read|。 >> I go to the university. I read books at the library.",
  "サム: 私{わたし}=I|^は=topic|家{いえ}=home, house|^で=at|仕事{しごと}=work|^を=(object)|します=do|。 >> I work at home.",
  "ブリップ: ブリップ=Blip|^は=topic|毎朝{まいあさ}=every morning|ラジオ=radio|^を=(object)|聞きます{ききます}=listen|！ >> Blip listens to the radio every morning!",
  "ゆき: 何{なに}=what|^を=(object)|聞きます{ききます}=listen to|^か=?|。 >> What do you listen to?",
  f"ブリップ: 天気{{てんき}}=weather|よほう=forecast|{DESU}|。|ピピッ=(beep)|。 >> The weather forecast. Beep.",
 ],
 "grammar": [
  {"id": "masu", "title": "～ます / ～ません: polite verbs (present)",
   "explain": "Polite verbs end in ます (do / will do) or ません (don't / won't). Japanese has one present form for both habits and the future: 食べます = I eat / I will eat.",
   "examples": [("パン=bread|^を=(object)|食べます{たべます}=eat|。", "I eat bread."), ("朝{あさ}ごはん=breakfast|^を=(object)|食べません{たべません}=don't eat|。", "I don't eat breakfast.")],
   "quiz": [{"q": "コーヒーを飲み＿＿。", "hint": "I don't drink coffee.", "choices": ["ません", "ます", "ですか"], "answer": 0, "why": "ません is the polite negative of ます."}]},
  {"id": "wo", "title": "～を: the object of the action",
   "explain": "を (written wo, read o) marks what the action is done to: パンを食べます (eat bread), 本を読みます (read a book).",
   "examples": [("本{ほん}=book|^を=(object)|読みます{よみます}=read|。", "I read a book.")],
   "quiz": [{"q": "ラジオ＿聞きます。", "hint": "I listen to the radio.", "choices": ["を", "に", "へ"], "answer": 0, "why": "を marks the thing listened to."}]},
  {"id": "ni-he", "title": "～に (time) and ～へ (direction)",
   "explain": "に after a specific time: 六時に (at six). へ (read e) after a destination: 大学へ行きます. You'll also hear 大学に行きます: に works for destinations too.",
   "examples": [("六時{ろくじ}=six o'clock|^に=at|起きます{おきます}=get up|。", "I get up at six.")],
   "quiz": [{"q": "七時＿起きます。", "hint": "I get up at seven.", "choices": ["に", "を", "で"], "answer": 0, "why": "に marks a point in time."},
            {"q": "大学＿行きます。", "hint": "I go to the university.", "choices": ["へ", "を", "で"], "answer": 0, "why": "へ marks the direction / destination."}]},
  {"id": "de-place", "title": "～で: where an action happens",
   "explain": "で marks the place where you do something: 図書館で本を読みます (I read at the library). Compare に/へ, which mark where you go.",
   "examples": [("家{いえ}=home|^で=at|仕事{しごと}=work|^を=(object)|します=do|。", "I work at home.")],
   "quiz": [{"q": "図書館＿本を読みます。", "hint": "I read books at the library.", "choices": ["で", "へ", "を"], "answer": 0, "why": "Reading happens at the library: で."}]},
 ],
 "kanji": [
  ("毎", "マイ", "", "every", [("毎朝", "まいあさ", "every morning"), ("毎日", "まいにち", "every day")]),
  ("時", "ジ", "とき", "time, o'clock", [("六時", "ろくじ", "six o'clock"), ("時間", "じかん", "time")]),
  ("食", "ショク", "た.べる", "eat, food", [("食べます", "たべます", "eat")]),
  ("行", "コウ,ギョウ", "い.く", "go", [("行きます", "いきます", "go")]),
  ("読", "ドク", "よ.む", "read", [("読みます", "よみます", "read")]),
  ("聞", "ブン", "き.く", "hear, listen, ask", [("聞きます", "ききます", "listen")]),
  ("六", "ロク", "む", "six", [("六時", "ろくじ", "six o'clock")]),
  ("間", "カン", "あいだ,ま", "interval, between", [("時間", "じかん", "time")]),
 ],
 "build": [1, 8],
 "questions": [
  {"q": "サムさんは何時に起きますか。", "en": "What time does Sam get up?", "choices": ["六時", "七時", "八時"], "answer": 0},
  {"q": "ゆきさんは朝ごはんを食べますか。", "en": "Does Yuki eat breakfast?", "choices": ["いいえ、食べません", "はい、パンを食べます", "はい、コーヒーを飲みます"], "answer": 0},
  {"q": "ゆきさんはどこで本を読みますか。", "en": "Where does Yuki read?", "choices": ["図書館で", "家で", "大学へ"], "answer": 0},
 ],
 "talk": "Tell Blip about your morning: what time you get up (～時に起きます), what you eat and drink, and where you go.",
},
{
 "id": "n5-04", "level": "N5", "unit": 4,
 "title": {"ja": "きのう、公園へ行きました", "en": "Yesterday I went to the park"},
 "scene": "Monday. Sam asks Yuki about her weekend.",
 "lines": [
  "サム: ゆき=Yuki|さん=Ms.|、|きのう=yesterday|何{なに}=what|^を=(object)|しましたか=did (you) do?|。 >> Yuki, what did you do yesterday?",
  "ゆき: 友{とも}だち=friend|^と=with|セントラルパーク=Central Park|^へ=to|行きました{いきました}=went|。 >> I went to Central Park with a friend.",
  "サム: 何{なん}=what|^で=by (means)|行きましたか{いきましたか}=did (you) go?|。 >> How did you get there?",
  "ゆき: 自転車{じてんしゃ}=bicycle|^で=by|行きました{いきました}=went|。 >> By bike.",
  "サム: いいですね=that's nice|。|天気{てんき}=weather|^は=topic|どうでしたか=how was (it)?|。 >> Nice. How was the weather?",
  "ゆき: とても=very|いい=good|天気{てんき}=weather|でした=was|。 >> The weather was really good.",
  "サム: 公園{こうえん}=park|^で=at|何{なに}=what|^を=(object)|しましたか=did (you) do?|。 >> What did you do in the park?",
  "ゆき: 写真{しゃしん}=photo|^を=(object)|とりました=took|。|それから=after that|、|アイスクリーム=ice cream|^を=(object)|食べました{たべました}=ate|。 >> I took photos. Then I ate ice cream.",
  "サム: 私{わたし}=I|^は=topic|どこへも=(to) nowhere (with a negative)|行きませんでした{いきませんでした}=didn't go|。 >> I didn't go anywhere.",
  "ゆき: えっ=huh?|、|どうしてですか=why?|。 >> Huh, why?",
  "サム: ブリップ=Blip|^と=with|アンテナ=antenna|^を=(object)|作りました{つくりました}=made|。 >> I built an antenna with Blip.",
  "ブリップ: 新しい{あたらしい}=new|アンテナ=antenna|です=is|！|ピピッ=(beep)|！ >> A new antenna! Beep!",
  "ゆき: すごいですね=that's amazing|！ >> That's amazing!",
 ],
 "grammar": [
  {"id": "mashita", "title": "～ました / ～ませんでした: past tense",
   "explain": "For the past, ます becomes ました (did) and ません becomes ませんでした (didn't). 行きます → 行きました → 行きませんでした.",
   "examples": [("公園{こうえん}=park|^へ=to|行きました{いきました}=went|。", "I went to the park.")],
   "quiz": [{"q": "きのう、アイスクリームを食べ＿＿＿。", "hint": "I ate ice cream yesterday.", "choices": ["ました", "ます", "ません"], "answer": 0, "why": "Past: ました."},
            {"q": "どこへも行き＿＿＿＿＿。", "hint": "I didn't go anywhere.", "choices": ["ませんでした", "ました", "ます"], "answer": 0, "why": "Past negative: ませんでした."}]},
  {"id": "deshita", "title": "～でした: was (nouns and な-adjectives)",
   "explain": "です in the past is でした: いい天気でした (it was nice weather). どうでしたか asks 'how was it?'.",
   "examples": [("いい=good|天気{てんき}=weather|でした=was|。", "It was nice weather.")],
   "quiz": [{"q": "きのうはいい天気＿＿＿。", "hint": "Yesterday the weather was nice.", "choices": ["でした", "です", "ました"], "answer": 0, "why": "です → でした."}]},
  {"id": "to", "title": "～と: with (someone)",
   "explain": "と after a person means 'together with': 友だちと行きました. Between nouns it also means 'and': パンとコーヒー.",
   "examples": [("友{とも}だち=friend|^と=with|行きました{いきました}=went|。", "I went with a friend.")],
   "quiz": [{"q": "ブリップ＿アンテナを作りました。", "hint": "I built an antenna with Blip.", "choices": ["と", "で", "を"], "answer": 0, "why": "と = together with."}]},
  {"id": "de-means", "title": "～で: by (means, tool)",
   "explain": "で after a vehicle or tool means 'by / with': 自転車で (by bike), 電車で (by train), はしで (with chopsticks). 何で asks 'by what means?'.",
   "examples": [("自転車{じてんしゃ}=bicycle|^で=by|行きました{いきました}=went|。", "I went by bike.")],
   "quiz": [{"q": "電車＿行きます。", "hint": "I go by train.", "choices": ["で", "と", "へ"], "answer": 0, "why": "で marks the means of transport."}]},
 ],
 "kanji": [
  ("友", "ユウ", "とも", "friend", [("友だち", "ともだち", "friend")]),
  ("天", "テン", "あま", "heaven, sky", [("天気", "てんき", "weather")]),
  ("気", "キ,ケ", "", "spirit, air", [("天気", "てんき", "weather"), ("元気", "げんき", "well, healthy")]),
  ("車", "シャ", "くるま", "car, vehicle", [("自転車", "じてんしゃ", "bicycle"), ("車", "くるま", "car")]),
  ("新", "シン", "あたら.しい", "new", [("新しい", "あたらしい", "new")]),
 ],
 "build": [1, 3],
 "questions": [
  {"q": "ゆきさんはだれと公園へ行きましたか。", "en": "Who did Yuki go to the park with?", "choices": ["友だち", "サムさん", "ブリップ"], "answer": 0},
  {"q": "ゆきさんは何で行きましたか。", "en": "How did she get there?", "choices": ["自転車で", "電車で", "車で"], "answer": 0},
  {"q": "サムさんはきのう何をしましたか。", "en": "What did Sam do yesterday?", "choices": ["アンテナを作りました", "公園へ行きました", "アイスクリームを食べました"], "answer": 0},
 ],
 "talk": "Tell Blip what you did last weekend: where you went (～へ行きました), with whom (～と), how (～で), and what you ate.",
},
{
 "id": "n5-05", "level": "N5", "unit": 5,
 "title": {"ja": "ニューヨークはどんな町ですか", "en": "What kind of city is New York?"},
 "scene": "Yuki's cousin is visiting from Tokyo. Yuki asks Sam what New York is like.",
 "lines": [
  f"ゆき: サム=Sam|{SAN}|、|ニューヨーク=New York|^は=topic|どんな=what kind of|町{{まち}}=town, city|{DESU}|^か=?|。 >> Sam, what kind of city is New York?",
  f"サム: 大きい{{おおきい}}=big|町{{まち}}=city|{DESU}|。|とても=very|にぎやか=lively|{DESU}|。 >> It's a big city. Very lively.",
  f"ゆき: 東京{{とうきょう}}=Tokyo|^も=also|大きい{{おおきい}}=big|{DESU}|。|でも=but|、|静か{{しずか}}=quiet|な=(な-adjective + noun)|所{{ところ}}=place|^も=also|あります=there are|。 >> Tokyo is big too. But there are also quiet places.",
  f"サム: ニューヨーク=New York|^の=of|地下鉄{{ちかてつ}}=subway|^は=topic|古い{{ふるい}}=old|{DESU}|。 >> New York's subway is old.",
  f"ゆき: 東京{{とうきょう}}=Tokyo|^の=of|地下鉄{{ちかてつ}}=subway|^は=topic|新しい{{あたらしい}}=new|{DESU}|。|そして=and|、|きれい=clean, pretty|{DESU}|。 >> Tokyo's subway is new. And it's clean.",
  f"ゆき: ニューヨーク=New York|^の=of|ピザ=pizza|^は=topic|おいしい=tasty|{DESU}|^か=?|。 >> Is New York pizza good?",
  f"サム: はい=yes|、|とても=very|おいしい=tasty|{DESU}|！|そして=and|、|安い{{やすい}}=cheap|{DESU}|。 >> Yes, really good! And cheap.",
  f"ゆき: アパート=apartment|^は=topic|高い{{たかい}}=expensive|{DESU}|^か=?|。 >> Are apartments expensive?",
  f"サム: はい=yes|、|とても=very|高い{{たかい}}=expensive|{DESU}|。|私{{わたし}}=I|^の=my|アパート=apartment|^は=topic|広くない{{ひろくない}}=not spacious|{DESU}|。 >> Yes, very. My apartment isn't big.",
  f"ブリップ: でも=but|、|いい=good|アパート=apartment|{DESU}|！|ラジオ=radios|^が=(subject)|たくさん=a lot|あります=there are|。 >> But it's a great apartment! There are lots of radios.",
  f"ゆき: あはは=haha|。|ニューヨーク=New York|^は=topic|おもしろい=interesting, fun|町{{まち}}=city|{DESU}|ね=isn't it|。 >> Haha. New York is a fun city, isn't it.",
 ],
 "grammar": [
  {"id": "i-adj", "title": "い-adjectives: 大きい, 高い, おいしい",
   "explain": "Most adjectives end in い and work like verbs: 大きいです (it's big). Put them straight before a noun: 大きい町 (a big city).",
   "examples": [(f"大きい{{おおきい}}=big|町{{まち}}=city|{DESU}|。", "It's a big city.")],
   "quiz": [{"q": "ピザは＿＿＿＿です。", "hint": "The pizza is tasty.", "choices": ["おいしい", "おいしいな", "おいしの"], "answer": 0, "why": "い-adjectives go straight before です."}]},
  {"id": "na-adj", "title": "な-adjectives: 静か, きれい, にぎやか",
   "explain": "A second group of adjectives needs な before a noun: 静かな所 (a quiet place), but no な before です: 静かです. きれい ends in い but is a な-adjective!",
   "examples": [(f"静か{{しずか}}=quiet|な=(+ noun)|所{{ところ}}=place|{DESU}|。", "It's a quiet place.")],
   "quiz": [{"q": "きれい＿町です。", "hint": "It's a pretty town.", "choices": ["な", "い", "の"], "answer": 0, "why": "きれい is a な-adjective: な before a noun."}]},
  {"id": "kunai", "title": "～くないです: not (い-adjectives)",
   "explain": "To negate an い-adjective, swap the last い for くない: 高い → 高くないです (not expensive). The odd one: いい → よくないです.",
   "examples": [(f"広くない{{ひろくない}}=not spacious|{DESU}|。", "It's not spacious.")],
   "quiz": [{"q": "アパートは高＿＿＿です。", "hint": "The apartment isn't expensive.", "choices": ["くない", "いない", "じゃない"], "answer": 0, "why": "高い → 高くない."}]},
  {"id": "totemo", "title": "とても / あまり～ない: very / not very",
   "explain": "とても = very (with a positive): とてもおいしいです. あまり = not very, only with a negative: あまり高くないです.",
   "examples": [("とても=very|おいしい=tasty|です=is|。", "It's very tasty.")],
   "quiz": [{"q": "＿＿＿高くないです。", "hint": "It's not very expensive.", "choices": ["あまり", "とても", "たくさん"], "answer": 0, "why": "あまり pairs with a negative."}]},
 ],
 "kanji": [
  ("高", "コウ", "たか.い", "tall, expensive", [("高い", "たかい", "expensive, tall")]),
  ("東", "トウ", "ひがし", "east", [("東京", "とうきょう", "Tokyo")]),
  ("京", "キョウ", "", "capital", [("東京", "とうきょう", "Tokyo")]),
  ("安", "アン", "やす.い", "cheap, peaceful", [("安い", "やすい", "cheap")]),
  ("町", "チョウ", "まち", "town", [("町", "まち", "town, city")]),
 ],
 "build": [1, 6],
 "questions": [
  {"q": "ニューヨークはどんな町ですか。", "en": "What's New York like?", "choices": ["大きくて、にぎやかな町", "静かな町", "小さい町"], "answer": 0},
  {"q": "ニューヨークのピザはどうですか。", "en": "How's New York pizza?", "choices": ["おいしくて、安い", "高い", "あまりおいしくない"], "answer": 0},
  {"q": "サムさんのアパートは広いですか。", "en": "Is Sam's apartment spacious?", "choices": ["いいえ、広くないです", "はい、とても広いです", "はい、安いです"], "answer": 0},
 ],
 "talk": "Describe your town to Blip with adjectives: big or small, lively or quiet, expensive or cheap. Use とても and あまり.",
},
{
 "id": "n5-06", "level": "N5", "unit": 6,
 "title": {"ja": "部屋に何がありますか", "en": "What's in the room?"},
 "scene": "Yuki looks around Sam's radio room. Something is hiding under the bed.",
 "lines": [
  "ゆき: わあ=wow|、|部屋{へや}=room|^に=in|ラジオ=radios|^が=(subject)|たくさん=many|ありますね=there are, aren't there|。 >> Wow, there are so many radios in the room.",
  "サム: はい=yes|、|五つ{いつつ}=five (things)|あります=there are|。 >> Yes, there are five.",
  "ゆき: テーブル=table|^の=of|上{うえ}=top, on|^に=on|何{なに}=what|^が=(subject)|ありますか=is there?|。 >> What's on the table?",
  "サム: パソコン=computer|^と=and|アンテナ=antenna|^が=(subject)|あります=there are|。 >> A computer and an antenna.",
  "ゆき: ブリップ=Blip|さん=Mr.|^は=topic|どこ=where|^に=at|いますか=is (he)? (living things)|。 >> Where is Blip?",
  "サム: ベッド=bed|^の=of|下{した}=under|^に=at|います=is (living)|。 >> Under the bed.",
  "ブリップ: ここ=here|^に=at|います=am|！|ピピッ=(beep)|！ >> I'm here! Beep!",
  "ゆき: あ=oh|、|ねこ=cat|^も=also|いますね=there is, isn't there|。 >> Oh, there's a cat too.",
  "サム: はい=yes|、|一匹{いっぴき}=one (small animal)|います=there is|。|名前{なまえ}=name|^は=topic|ラジオ=Radio|です=is|。 >> Yes, one. Her name is Radio.",
  "ゆき: ねこ=cat|^の='s|名前{なまえ}=name|^も=also|ラジオ=Radio|！？ >> The cat is called Radio too?!",
  "サム: はい=yes|。|ラジオ=radio|^が=(subject)|大好き{だいすき}=love|です=is|^から=because|。 >> Yes. Because I love radio.",
 ],
 "grammar": [
  {"id": "aru-iru", "title": "あります / います: there is",
   "explain": "Both mean 'there is / to be (somewhere)'. あります for things and plants, います for people and animals (and robots that act alive!).",
   "examples": [("ねこ=cat|^が=(subject)|います=there is|。", "There's a cat."), ("本{ほん}=book|^が=(subject)|あります=there is|。", "There's a book.")],
   "quiz": [{"q": "ベッドの下にブリップが＿＿＿。", "hint": "Blip is under the bed.", "choices": ["います", "あります", "です"], "answer": 0, "why": "Blip moves like a living thing: います."},
            {"q": "テーブルの上に本が＿＿＿＿。", "hint": "There's a book on the table.", "choices": ["あります", "います", "します"], "answer": 0, "why": "A book is a thing: あります."}]},
  {"id": "ni-ga", "title": "Place に Thing が あります",
   "explain": "The place takes に, the thing takes が: 部屋にラジオがあります (in the room there is a radio). To ask where something is: ～はどこにありますか.",
   "examples": [("部屋{へや}=room|^に=in|ラジオ=radio|^が=(subject)|あります=there is|。", "There's a radio in the room.")],
   "quiz": [{"q": "部屋＿ねこがいます。", "hint": "There's a cat in the room.", "choices": ["に", "で", "を"], "answer": 0, "why": "Where something exists: に."}]},
  {"id": "position", "title": "上・下・中・となり: positions",
   "explain": "Position words follow the object with の: テーブルの上 (on the table), ベッドの下 (under the bed), かばんの中 (in the bag), 窓のとなり (next to the window).",
   "examples": [("ベッド=bed|^の=of|下{した}=under|^に=at|います=is|。", "It's under the bed.")],
   "quiz": [{"q": "テーブルの＿＿にパソコンがあります。", "hint": "There's a computer on the table.", "choices": ["上", "下", "中"], "answer": 0, "why": "上 = on top."}]},
  {"id": "counters", "title": "Counting: ～つ, ～人, ～匹",
   "explain": "Japanese counts with counters. General things: 一つ ひとつ, 二つ ふたつ, 三つ みっつ … 五つ いつつ. People: 一人 ひとり, 二人 ふたり, 三人 さんにん. Small animals: 一匹 いっぴき, 二匹 にひき.",
   "examples": [("ラジオ=radio|^が=(subject)|五つ{いつつ}=five|あります=there are|。", "There are five radios.")],
   "quiz": [{"q": "ねこが＿＿＿います。", "hint": "There is one cat.", "choices": ["一匹", "一つ", "一人"], "answer": 0, "why": "Cats are small animals: 匹."}]},
 ],
 "kanji": [
  ("上", "ジョウ", "うえ,あ.がる", "up, above", [("上", "うえ", "on top")]),
  ("下", "カ,ゲ", "した,さ.がる", "down, below", [("下", "した", "under")]),
  ("中", "チュウ", "なか", "inside, middle", [("中", "なか", "inside")]),
  ("五", "ゴ", "いつ.つ", "five", [("五つ", "いつつ", "five (things)")]),
  ("一", "イチ", "ひと.つ", "one", [("一つ", "ひとつ", "one (thing)"), ("一匹", "いっぴき", "one (animal)")]),
  ("名", "メイ,ミョウ", "な", "name", [("名前", "なまえ", "name")]),
 ],
 "build": [3, 5],
 "questions": [
  {"q": "部屋にラジオがいくつありますか。", "en": "How many radios are there?", "choices": ["五つ", "一つ", "三つ"], "answer": 0},
  {"q": "ブリップはどこにいましたか。", "en": "Where was Blip?", "choices": ["ベッドの下", "テーブルの上", "部屋の外"], "answer": 0},
  {"q": "ねこの名前は何ですか。", "en": "What's the cat's name?", "choices": ["ラジオ", "ブリップ", "ゆき"], "answer": 0},
 ],
 "talk": "Describe your room to Blip: what's on the desk, under the bed, how many of something there are, and whether there's a pet.",
},
{
 "id": "n5-07", "level": "N5", "unit": 7,
 "title": {"ja": "いっしょに見ませんか", "en": "Want to watch it together?"},
 "scene": "Sam works up the courage to invite Yuki to a movie.",
 "lines": [
  "サム: ゆき=Yuki|さん=Ms.|、|土曜日{どようび}=Saturday|^に=on|いっしょに=together|映画{えいが}=movie|^を=(object)|見ませんか{みませんか}=won't you watch? (invitation)|。 >> Yuki, would you like to see a movie with me on Saturday?",
  "ゆき: いいですね=sounds good|。|何{なん}=what|^の=kind of|映画{えいが}=movie|ですか=is it?|。 >> Sounds nice. What kind of movie?",
  "サム: 日本{にほん}=Japan|^の='s|アニメ=anime|です=is|。 >> A Japanese anime.",
  "ゆき: 私{わたし}=I|^も=also|アニメ=anime|^が=(object of liking)|好き{すき}=like|です=am|。|何時{なんじ}=what time|^に=at|会いましょうか{あいましょうか}=shall we meet?|。 >> I like anime too. What time shall we meet?",
  "サム: 三時{さんじ}=three o'clock|^は=topic|どうですか=how about?|。 >> How about three?",
  "ゆき: 三時{さんじ}=three o'clock|^は=topic|ちょっと=a little (difficult)…|…|。|四時{よじ}=four o'clock|^は=topic|どうですか=how about?|。 >> Three is a bit… How about four?",
  "サム: いいですよ=that's fine|。|じゃあ=well then|、|四時{よじ}=four o'clock|^に=at|会いましょう{あいましょう}=let's meet|。 >> Sure. Let's meet at four, then.",
  "ゆき: 映画{えいが}=movie|^の=of|後{あと}=after|^で=(after that)|、|ラーメン=ramen|^を=(object)|食べたいです{たべたいです}=want to eat|。 >> After the movie, I want to eat ramen.",
  "サム: いいですね=great|！|私{わたし}=I|^も=also|ラーメン=ramen|^が=(object of wanting)|食べたいです{たべたいです}=want to eat|。 >> Great! I want ramen too.",
  "ブリップ: ブリップ=Blip|^は=topic|電気{でんき}=electricity|^が=(object)|食べたいです{たべたいです}=want to eat|！ >> Blip wants to eat electricity!",
  "ゆき: あはは=haha|。|じゃあ=well then|、|土曜日{どようび}=Saturday|^に=on|！ >> Haha. See you Saturday!",
 ],
 "grammar": [
  {"id": "masenka", "title": "～ませんか: won't you…? (invitation)",
   "explain": "Turning ます into ませんか makes a polite invitation: 見ませんか (would you like to watch?). Literally 'won't you watch?', it leaves room to say no.",
   "examples": [("いっしょに=together|映画{えいが}=movie|^を=(object)|見ませんか{みませんか}=would you like to watch?|。", "Would you like to watch a movie together?")],
   "quiz": [{"q": "いっしょにラーメンを食べ＿＿＿＿。", "hint": "Would you like to eat ramen together?", "choices": ["ませんか", "ましょう", "たいです"], "answer": 0, "why": "ませんか = invitation."}]},
  {"id": "mashou", "title": "～ましょう: let's",
   "explain": "ましょう means 'let's (do it)': 会いましょう (let's meet). ましょうか asks 'shall we?': 何時に会いましょうか.",
   "examples": [("四時{よじ}=four o'clock|^に=at|会いましょう{あいましょう}=let's meet|。", "Let's meet at four.")],
   "quiz": [{"q": "じゃあ、四時に会い＿＿＿＿。", "hint": "Then let's meet at four.", "choices": ["ましょう", "ませんか", "ました"], "answer": 0, "why": "ましょう = let's."}]},
  {"id": "tai", "title": "～たいです: want to",
   "explain": "Swap ます for たい to say you want to do it: 食べます → 食べたいです. It works like an い-adjective (食べたくないです = don't want to). The object can take が or を.",
   "examples": [("ラーメン=ramen|^が=(object)|食べたいです{たべたいです}=want to eat|。", "I want to eat ramen.")],
   "quiz": [{"q": "日本へ行き＿＿＿＿。", "hint": "I want to go to Japan.", "choices": ["たいです", "ます", "ましょう"], "answer": 0, "why": "行きます → 行きたいです."}]},
  {"id": "chotto", "title": "～はちょっと…: saying no politely",
   "explain": "Japanese rarely says a flat 'no' to an invitation. ちょっと… (a little…) trailing off is enough: 三時はちょっと… = three doesn't really work for me.",
   "examples": [("三時{さんじ}=three o'clock|^は=topic|ちょっと=a bit…|…|。", "Three is a bit (difficult)…")],
   "quiz": [{"q": "Someone invites you on Sunday, but you're busy. You say: 日曜日は＿＿＿…", "hint": "Sunday is a bit…", "choices": ["ちょっと", "とても", "いっしょに"], "answer": 0, "why": "ちょっと… is the polite way to decline."}]},
 ],
 "kanji": [
  ("土", "ド,ト", "つち", "earth, soil (Saturday)", [("土曜日", "どようび", "Saturday")]),
  ("曜", "ヨウ", "", "weekday", [("土曜日", "どようび", "Saturday")]),
  ("見", "ケン", "み.る", "see, look", [("見ます", "みます", "see, watch")]),
  ("三", "サン", "み.つ", "three", [("三時", "さんじ", "three o'clock")]),
  ("四", "シ", "よ,よん", "four", [("四時", "よじ", "four o'clock")]),
  ("電", "デン", "", "electricity", [("電気", "でんき", "electricity, light"), ("電車", "でんしゃ", "train")]),
  ("後", "ゴ,コウ", "あと,うし.ろ", "after, behind", [("後で", "あとで", "later, after")]),
 ],
 "build": [0, 6],
 "questions": [
  {"q": "二人は何曜日に映画を見ますか。", "en": "On which day will they watch the movie?", "choices": ["土曜日", "日曜日", "月曜日"], "answer": 0},
  {"q": "何時に会いますか。", "en": "What time will they meet?", "choices": ["四時", "三時", "二時"], "answer": 0},
  {"q": "映画の後で、何を食べたいですか。", "en": "What do they want to eat after?", "choices": ["ラーメン", "ピザ", "電気"], "answer": 0},
 ],
 "talk": "Invite Blip to do something with you (～ませんか), agree on a time (～ましょう), and say what you want to do (～たいです).",
},
{
 "id": "n5-08", "level": "N5", "unit": 8,
 "title": {"ja": "今、何をしていますか", "en": "What are you doing right now?"},
 "scene": "Sunday evening. Yuki calls Sam; he sounds very excited.",
 "lines": [
  "ゆき: もしもし=hello (on the phone)|、|サム=Sam|さん=Mr.|。|今{いま}=now|、|何{なに}=what|^を=(object)|していますか=are (you) doing?|。 >> Hello, Sam. What are you doing right now?",
  "サム: 今{いま}=now|、|うちゅう=space|ステーション=station|^の=of|声{こえ}=voice|^を=(object)|聞いています{きいています}=am listening|！ >> Right now I'm listening to the space station's voice!",
  "ゆき: えっ=what?|、|本当{ほんとう}=true, real|ですか=is it?|！ >> What, really?!",
  "サム: はい=yes|。|ゆき=Yuki|さん=Ms.|、|ちょっと=a moment|待ってください{まってください}=please wait|。 >> Yes. Yuki, wait a moment, please.",
  "サム: あっ=ah!|、|今{いま}=now|、|写真{しゃしん}=picture|^が=(subject)|来ました{きました}=came|！|SSTV=SSTV (pictures over radio)|^の='s|写真{しゃしん}=picture|です=is|。 >> Oh! A picture just came in! An SSTV picture.",
  "ゆき: すごい=amazing|！|その=that|写真{しゃしん}=picture|^を=(object)|見せてください{みせてください}=please show (me)|。 >> Amazing! Please show me the picture.",
  "サム: いいですよ=sure|。|メール=email|^で=by|送ります{おくります}=will send|。 >> Sure. I'll send it by email.",
  "ブリップ: ブリップ=Blip|^は=topic|今{いま}=now|、|写真{しゃしん}=picture|^を=(object)|プリントしています=is printing|。 >> Blip is printing the picture right now.",
  "ゆき: ありがとう=thank you|！|明日{あした}=tomorrow|、|学校{がっこう}=school|^で=at|友{とも}だち=friends|^に=to|見せます{みせます}=will show|。 >> Thank you! Tomorrow I'll show it to my friends at school.",
  "サム: ゆき=Yuki|さん=Ms.|^も=also|、|いつか=someday|いっしょに=together|聞きませんか{ききませんか}=won't you listen?|。 >> Yuki, would you like to listen together sometime?",
  "ゆき: ぜひ=definitely|！|楽しみ{たのしみ}=looking forward to it|です=am|。 >> Definitely! I'm looking forward to it.",
 ],
 "grammar": [
  {"id": "te-form", "title": "The て-form: the Swiss army knife",
   "explain": "Many patterns are built on the て-form. Ru-verbs drop る and add て: 食べる → 食べて, 見る → 見て. U-verbs change by ending: 聞く → 聞いて, 待つ → 待って, 読む → 読んで, 送る → 送って. Irregular: する → して, 来る → 来て, and 行く → 行って.",
   "examples": [("ちょっと=a moment|待ってください{まってください}=please wait|。", "Please wait a moment.")],
   "quiz": [{"q": "聞く → ＿＿＿", "hint": "the て-form of 聞く (listen)", "choices": ["聞いて", "聞きて", "聞って"], "answer": 0, "why": "く → いて."},
            {"q": "読む → ＿＿＿", "hint": "the て-form of 読む (read)", "choices": ["読んで", "読みて", "読って"], "answer": 0, "why": "む → んで."}]},
  {"id": "teiru", "title": "～ています: is doing (right now)",
   "explain": "て-form + います = an action in progress: 聞いています (I'm listening). It also describes ongoing states: 東京に住んでいます (I live in Tokyo).",
   "examples": [("今{いま}=now|、|ラジオ=radio|^を=(object)|聞いています{きいています}=am listening|。", "I'm listening to the radio now.")],
   "quiz": [{"q": "ブリップは今、写真をプリント＿＿＿＿。", "hint": "Blip is printing the picture now.", "choices": ["しています", "します", "しました"], "answer": 0, "why": "In progress: ～ています."}]},
  {"id": "tekudasai", "title": "～てください: please do",
   "explain": "て-form + ください = a polite request: 待ってください (please wait), 見せてください (please show me).",
   "examples": [("写真{しゃしん}=picture|^を=(object)|見せてください{みせてください}=please show|。", "Please show me the picture.")],
   "quiz": [{"q": "ちょっと待＿＿ください。", "hint": "Please wait a moment.", "choices": ["って", "て", "んで"], "answer": 0, "why": "待つ → 待って."}]},
 ],
 "kanji": [
  ("今", "コン,キン", "いま", "now", [("今", "いま", "now")]),
  ("来", "ライ", "く.る,き.ます", "come", [("来ました", "きました", "came")]),
  ("校", "コウ", "", "school", [("学校", "がっこう", "school")]),
  ("写", "シャ", "うつ.す", "copy, photograph", [("写真", "しゃしん", "photo")]),
  ("明", "メイ", "あか.るい", "bright (tomorrow)", [("明日", "あした", "tomorrow")]),
 ],
 "build": [3, 5],
 "questions": [
  {"q": "サムさんは今、何をしていますか。", "en": "What is Sam doing?", "choices": ["うちゅうステーションの声を聞いています", "映画を見ています", "ラーメンを食べています"], "answer": 0},
  {"q": "写真は何で送りますか。", "en": "How will he send the picture?", "choices": ["メールで", "電車で", "ブリップで"], "answer": 0},
  {"q": "ゆきさんは明日、どこで写真を見せますか。", "en": "Where will Yuki show the picture?", "choices": ["学校で", "公園で", "家で"], "answer": 0},
 ],
 "talk": "Tell Blip what you're doing right now (～ています), then ask Blip politely to do something (～てください).",
},
]
