# More JLPT N5 units (9–12): the same New York weeks as n5.py. Notation: see build.py.
# Grammar ids match data/grammar.json, so each point links to its full lesson.

UNITS = [
{
 "id": "n5-09", "level": "N5", "unit": 9,
 "title": {"ja": "行ったことがありますか", "en": "Have you ever been?"},
 "scene": "Saturday. Sam and Yuki meet in front of the natural history museum.",
 "lines": [
  "ゆき: サムさん=Sam|^は=topic|この=this|博物館{はくぶつかん}=museum|^に=to|行った{いった}=went|ことがあります=have (done)|か=?|。 >> Sam, have you ever been to this museum?",
  "サム: はい=yes|、|子{こ}ども=child|^の=(of)|とき=time|^に=at|一回{いっかい}=once|行った{いった}=went|ことがあります=have (done)|。 >> Yes, I went once when I was a kid.",
  "ゆき: 私{わたし}=I|^は=topic|恐竜{きょうりゅう}=dinosaurs|^が=(object)|大好{だいす}き=love|です=(am)|。|東京{とうきょう}=Tokyo|^の=(of)|博物館{はくぶつかん}=museum|^より=than|大{おお}きい=big|です=is|ね=right|。 >> I love dinosaurs. It's bigger than the museum in Tokyo, isn't it?",
  "サム: ニューヨーク=New York|^の=(of)|博物館{はくぶつかん}=museums|^は=topic|大{おお}きすぎます=are too big|。|一日{いちにち}=one day|^で=in|^は=topic|全部{ぜんぶ}=all|見{み}ることができません=can't see|。 >> New York's museums are too big. You can't see everything in one day.",
  "ブリップ: ブリップ=Blip|^は=topic|恐竜{きょうりゅう}=dinosaurs|^より=than|小{ちい}さい=small|です=am|。|でも=but|、|恐竜{きょうりゅう}=dinosaurs|^より=than|若{わか}い=young|です=am|よ=you know|！ >> Blip is smaller than a dinosaur. But younger than the dinosaurs!",
  "ゆき: ふふ=heh|。|サムさん=Sam|、|宇宙{うちゅう}=space|^の=(of)|ショー=show|^を=(object)|見た{みた}=saw|ことがあります=have (done)|か=?|。 >> Heh. Sam, have you ever seen the space show?",
  "サム: いいえ=no|、|ありません=I haven't|。|見{み}たいです=want to see|！|チケット=tickets|^は=topic|高{たか}すぎますか=are they too expensive|？ >> No, I haven't. I want to see it! Are the tickets too expensive?",
  "ゆき: 大丈夫{だいじょうぶ}=fine|です=is|よ=you know|。|今日{きょう}=today|^は=topic|私{わたし}=I|^が=(subject)|買{か}います=will buy|。 >> It's fine. Today I'm buying.",
  "サム: ありがとう=thanks|。|じゃあ=then|、|ショー=show|^の=(of)|前{まえ}=before|^に=at|コーヒー=coffee|^を=(object)|飲{の}みましょう=let's drink|。|ぼく=I|^が=(subject)|買{か}います=will buy|。 >> Thanks. Then let's have coffee before the show. I'm buying that.",
 ],
 "grammar": [
  {"id": "koto-ga-aru", "title": "V-たことがある: have done (ever)",
   "explain": "Past plain form + ことがある = you've had the experience. Ask with ～たことがありますか (have you ever…?). Answer はい、あります or いいえ、ありません.",
   "examples": [("行った{いった}=went|ことがあります=have (done)|。", "I've been there."), ("見た{みた}=saw|ことがあります=have (done)|か=?|。", "Have you ever seen it?")],
   "quiz": [{"q": "日本へ行った＿＿があります。", "hint": "I've been to Japan.", "choices": ["こと", "もの", "とき"], "answer": 0, "why": "Experience: たことがある."},
            {"q": "すしを食べたことが＿＿＿か。", "hint": "Have you ever eaten sushi?", "choices": ["あります", "います", "します"], "answer": 0, "why": "ことがある uses ある."}]},
  {"id": "yori", "title": "A は B より: A is more … than B",
   "explain": "A は B より + adjective = A is more (adjective) than B. Japanese has no word for 'more' here: より does it all.",
   "examples": [("ブリップ=Blip|^は=topic|恐竜{きょうりゅう}=dinosaur|^より=than|小{ちい}さい=small|です=is|。", "Blip is smaller than a dinosaur.")],
   "quiz": [{"q": "電車はバス＿＿速いです。", "hint": "The train is faster than the bus.", "choices": ["より", "から", "まで"], "answer": 0, "why": "Comparing: より = than."}]},
  {"id": "sugiru", "title": "～すぎる: too (much)",
   "explain": "い-adjective minus い + すぎる: 高い → 高すぎる. な-adjective + すぎる: しずかすぎる. Verb stem + すぎる: 食べすぎる (eat too much). It changes like a ru-verb: すぎます, すぎました.",
   "examples": [("高{たか}すぎます=too expensive|。", "It's too expensive."), ("食{た}べすぎました=ate too much|。", "I ate too much.")],
   "quiz": [{"q": "このかばんは大き＿＿＿＿。", "hint": "This bag is too big.", "choices": ["すぎます", "ですぎ", "くすぎ"], "answer": 0, "why": "Drop the い and add すぎる."}]},
 ],
 "kanji": [
  ("子", "シ", "こ", "child", [("子ども", "こども", "child")]),
  ("小", "ショウ", "ちい.さい,こ", "small", [("小さい", "ちいさい", "small")]),
  ("前", "ゼン", "まえ", "before, front", [("前", "まえ", "before, in front"), ("名前", "なまえ", "name")]),
  ("見", "ケン", "み.る", "see", [("見る", "みる", "to see")]),
  ("全", "ゼン", "まった.く", "all", [("全部", "ぜんぶ", "all")]),
 ],
 "build": [1, 6],
 "questions": [
  {"q": "サムさんはこの博物館に行ったことがありますか。", "en": "Has Sam been to this museum before?", "choices": ["はい、子どものときに", "いいえ、ありません", "はい、毎週行きます"], "answer": 0},
  {"q": "ゆきさんは何が大好きですか。", "en": "What does Yuki love?", "choices": ["恐竜", "コーヒー", "ラジオ"], "answer": 0},
  {"q": "ショーの前に二人は何をしますか。", "en": "What will they do before the show?", "choices": ["コーヒーを飲みます", "ごはんを食べます", "写真をとります"], "answer": 0},
 ],
 "talk": "Ask Blip if it has ever done three things (～たことがありますか), and compare two places you know with より.",
},
{
 "id": "n5-10", "level": "N5", "unit": 10,
 "title": {"ja": "写真をとってもいいですか", "en": "May I take a photo?"},
 "scene": "Inside the museum. Sam wants a photo of everything; a guard is watching.",
 "lines": [
  "サム: すみません=excuse me|。|ここ=here|^で=at|写真{しゃしん}=photo|^を=(object)|とっても=even if (I) take|いいですか=is it okay|。 >> Excuse me. May I take a photo here?",
  "係{かかり}の人{ひと}: はい=yes|、|とってもいいです=you may take|。|でも=but|、|フラッシュ=flash|^は=topic|使{つか}ってはいけません=must not use|。 >> Yes, you may. But you must not use the flash.",
  "サム: わかりました=understood|。|あの=that|恐竜{きょうりゅう}=dinosaur|^に=(to)|さわっても=even if (I) touch|いいですか=is it okay|。 >> Got it. May I touch that dinosaur?",
  "係{かかり}の人{ひと}: いいえ=no|、|さわってはいけません=must not touch|。|とても=very|古{ふる}い=old|です=is|から=because|。 >> No, you must not touch it. It's very old.",
  "ゆき: サムさん=Sam|、|入{はい}る=go in|前{まえ}=before|^に=at|、|ルール=rules|^を=(object)|読{よ}みましょう=let's read|。 >> Sam, let's read the rules before we go in.",
  "サム: はい=okay|……|。|食べ物{たべもの}=food|^は=topic|だめ=not allowed|です=is|。|大{おお}きい=big|声{こえ}=voice|^で=in|話{はな}してはいけません=must not talk|。 >> Okay... No food. You must not talk loudly.",
  "ブリップ: ロボット=robots|^は=topic|入{はい}っても=even if (they) enter|いいですか=is it okay|？ >> Are robots allowed in?",
  "係{かかり}の人{ひと}: ……|小{ちい}さい=small|ロボット=robot|^は=topic|いいです=is fine|よ=you know|。|でも=but|、|走{はし}ってはいけません=must not run|。 >> ...Small robots are fine. But no running.",
  "サム: よかった=what a relief|。|じゃあ=then|、|帰{かえ}る=go home|前{まえ}=before|^に=at|、|みんな=everyone|^で=as|写真{しゃしん}=photo|^を=(object)|とりましょう=let's take|！ >> What a relief. Then before we go home, let's take a photo of all of us!",
 ],
 "grammar": [
  {"id": "te-mo-ii", "title": "V-てもいい: may I, it's okay to",
   "explain": "て-form + もいい = it's okay to do. Ask permission with ～てもいいですか. Yes: はい、いいです / どうぞ. No: すみません、ちょっと…",
   "examples": [("写真{しゃしん}=photo|^を=(object)|とっても=even if (I) take|いいですか=is it okay|。", "May I take a photo?")],
   "quiz": [{"q": "ここに座っ＿＿いいですか。", "hint": "May I sit here?", "choices": ["ても", "ては", "たら"], "answer": 0, "why": "Permission: てもいい."}]},
  {"id": "te-wa-ikenai", "title": "V-てはいけない: must not",
   "explain": "て-form + はいけない = you must not. It's the strong 'no' on signs and from staff. In speech ては often becomes ちゃ: さわっちゃだめ.",
   "examples": [("フラッシュ=flash|^は=topic|使{つか}ってはいけません=must not use|。", "You must not use the flash."), ("さわってはいけません=must not touch|。", "Don't touch it.")],
   "quiz": [{"q": "ここで食べ＿＿いけません。", "hint": "You must not eat here.", "choices": ["ては", "ても", "たり"], "answer": 0, "why": "Prohibition: てはいけない."}]},
  {"id": "mae-ni", "title": "V-る前に: before doing",
   "explain": "Dictionary form + 前に = before. Even when the sentence is in the past, the verb before 前に stays in dictionary form: 寝る前に読みました. With nouns: ショーの前に.",
   "examples": [("入{はい}る=go in|前{まえ}=before|^に=at|、|ルール=rules|^を=(object)|読{よ}みましょう=let's read|。", "Let's read the rules before we go in.")],
   "quiz": [{"q": "寝る＿＿＿、本を読みます。", "hint": "I read before I go to sleep.", "choices": ["前に", "後で", "ながら"], "answer": 0, "why": "Before: dictionary form + 前に."}]},
 ],
 "kanji": [
  ("入", "ニュウ", "はい.る,い.れる", "enter", [("入る", "はいる", "to enter"), ("入口", "いりぐち", "entrance")]),
  ("古", "コ", "ふる.い", "old", [("古い", "ふるい", "old")]),
  ("読", "ドク", "よ.む", "read", [("読む", "よむ", "to read")]),
  ("話", "ワ", "はな.す", "talk", [("話す", "はなす", "to speak")]),
  ("帰", "キ", "かえ.る", "return home", [("帰る", "かえる", "to go home")]),
 ],
 "build": [0, 4],
 "questions": [
  {"q": "博物館で写真をとってもいいですか。", "en": "May you take photos in the museum?", "choices": ["はい、でもフラッシュはだめです", "いいえ、だめです", "はい、何でもいいです"], "answer": 0},
  {"q": "どうして恐竜にさわってはいけませんか。", "en": "Why mustn't you touch the dinosaur?", "choices": ["とても古いから", "高いから", "こわいから"], "answer": 0},
  {"q": "ブリップは何をしてはいけませんか。", "en": "What mustn't Blip do?", "choices": ["走ること", "話すこと", "写真をとること"], "answer": 0},
 ],
 "talk": "Role-play: Blip is a museum guard. Ask permission for three things (～てもいいですか); Blip answers with いいです or ～てはいけません.",
},
{
 "id": "n5-11", "level": "N5", "unit": 11,
 "title": {"ja": "音楽を聞きながら", "en": "While listening to music"},
 "scene": "Sam's apartment in Queens. Yuki finds him studying kanji with the radio on.",
 "lines": [
  "ゆき: サムさん=Sam|、|何{なに}=what|^を=(object)|して=doing|いますか=are you|。 >> Sam, what are you doing?",
  "サム: ラジオ=radio|^を=(object)|聞{き}きながら=while listening|、|漢字{かんじ}=kanji|^を=(object)|勉強{べんきょう}しています=am studying|。 >> I'm studying kanji while listening to the radio.",
  "ゆき: 日本{にほん}=Japan|^の=(of)|ラジオ=radio|です=is|か=?|。 >> Is it Japanese radio?",
  "サム: はい=yes|。|週末{しゅうまつ}=weekends|^は=topic|、|日本{にほん}=Japan|^の=(of)|ニュース=news|^を=(object)|聞{き}いたり=listen and so on|、|歌{うた}=songs|^を=(object)|歌{うた}ったり=sing and so on|します=do|。 >> Yes. On weekends I listen to the Japanese news, sing songs, that kind of thing.",
  "ブリップ: サムさん=Sam|^の=(of)|歌{うた}=singing|^は=topic|ちょっと=a little|……|。 >> Sam's singing is a little...",
  "サム: ブリップ=Blip|！ >> Blip!",
  "ゆき: ふふ=heh|。|でも=but|、|毎日{まいにち}=every day|少{すこ}し=a little|ずつ=at a time|書{か}いたほうがいいです=had better write|よ=you know|。|漢字{かんじ}=kanji|^は=topic|書{か}くと=when you write|覚{おぼ}えます=remember|から=because|。 >> Heh. But you'd better write a little every day. You remember kanji when you write them.",
  "サム: そうですね=you're right|。|じゃあ=then|、|ラジオ=radio|^を=(object)|聞{き}きながら=while listening|書{か}きます=will write|。 >> You're right. Then I'll write while I listen to the radio.",
  "ゆき: 寝{ね}る=sleep|前{まえ}=before|^に=at|、|もう=again|一度{いちど}=once|見{み}たほうがいいです=had better look|よ=you know|。 >> And you'd better look at them once more before you go to sleep.",
 ],
 "grammar": [
  {"id": "nagara", "title": "V-stem ながら: while doing",
   "explain": "Verb stem (the ます-form without ます) + ながら = doing two things at once: 聞きながら書く. The main action is the second verb.",
   "examples": [("ラジオ=radio|^を=(object)|聞{き}きながら=while listening|、|勉強{べんきょう}します=study|。", "I study while listening to the radio.")],
   "quiz": [{"q": "音楽を聞き＿＿＿、走ります。", "hint": "I run while listening to music.", "choices": ["ながら", "たり", "から"], "answer": 0, "why": "Two things at once: stem + ながら."}]},
  {"id": "tari", "title": "V-たり V-たりする: things like … and …",
   "explain": "た-form + り, twice, then する = do things such as A and B (a sample, not a full list).",
   "examples": [("ニュース=news|^を=(object)|聞{き}いたり=listen, etc.|、|歌{うた}=songs|^を=(object)|歌{うた}ったり=sing, etc.|します=do|。", "I do things like listen to the news and sing.")],
   "quiz": [{"q": "週末は本を読んだり、テレビを見＿＿＿します。", "hint": "On weekends I read books, watch TV and so on.", "choices": ["たり", "ながら", "て"], "answer": 0, "why": "A sample of activities: たり…たりする."}]},
  {"id": "hou-ga-ii", "title": "V-たほうがいい: you'd better",
   "explain": "た-form + ほうがいい = it's better to, a friendly piece of advice. For 'better not': ないほうがいい.",
   "examples": [("毎日{まいにち}=every day|書{か}いたほうがいいです=had better write|。", "You'd better write every day.")],
   "quiz": [{"q": "早く寝＿＿＿＿がいいですよ。", "hint": "You'd better go to bed early.", "choices": ["たほう", "るほう", "てほう"], "answer": 0, "why": "Advice: た-form + ほうがいい."}]},
 ],
 "kanji": [
  ("書", "ショ", "か.く", "write", [("書く", "かく", "to write"), ("図書館", "としょかん", "library")]),
  ("歌", "カ", "うた,うた.う", "song, sing", [("歌", "うた", "song"), ("歌う", "うたう", "to sing")]),
  ("聞", "ブン", "き.く", "hear, ask", [("聞く", "きく", "to listen")]),
  ("週", "シュウ", "", "week", [("週末", "しゅうまつ", "weekend"), ("毎週", "まいしゅう", "every week")]),
  ("少", "ショウ", "すこ.し,すく.ない", "a little, few", [("少し", "すこし", "a little")]),
 ],
 "build": [1, 7],
 "questions": [
  {"q": "サムさんは何をしながら勉強していますか。", "en": "What is Sam doing while he studies?", "choices": ["ラジオを聞いています", "テレビを見ています", "ごはんを食べています"], "answer": 0},
  {"q": "ゆきさんによると、漢字はどうしたら覚えますか。", "en": "According to Yuki, how do you remember kanji?", "choices": ["書くと", "歌うと", "寝ると"], "answer": 0},
  {"q": "寝る前に、サムさんは何をしたほうがいいですか。", "en": "What should Sam do before bed?", "choices": ["漢字をもう一度見る", "ラジオを聞く", "歌を歌う"], "answer": 0},
 ],
 "talk": "Tell Blip two things you do while doing something else (～ながら), what you do on weekends (～たり～たりします), and give Blip one piece of advice (～たほうがいい).",
},
{
 "id": "n5-12", "level": "N5", "unit": 12,
 "title": {"ja": "週末は何をするつもりですか", "en": "What are your plans for the weekend?"},
 "scene": "Friday afternoon at the café. Yuki has a plan; Sam has to work.",
 "lines": [
  "ゆき: サムさん=Sam|、|週末{しゅうまつ}=weekend|^は=topic|何{なに}=what|^を=(object)|する=do|つもり=plan to|です=is|か=?|。 >> Sam, what are you planning to do this weekend?",
  "サム: 土曜日{どようび}=Saturday|^は=topic|仕事{しごと}=work|^に=to|行{い}かなければなりません=have to go|。 >> On Saturday I have to go to work.",
  "サム: 九時{くじ}=nine o'clock|^から=from|五時{ごじ}=five o'clock|^まで=until|です=is|。 >> From nine to five.",
  "ゆき: 大変{たいへん}=tough|です=is|ね=huh|。|日曜日{にちようび}=Sunday|^は=topic|？ >> That's tough. And Sunday?",
  "サム: 日曜日{にちようび}=Sunday|^は=topic|休{やす}み=day off|です=is|。|何{なに}も=nothing|しなくてもいいです=don't have to do|。 >> Sunday is my day off. I don't have to do anything.",
  "ゆき: じゃあ=then|、|いっしょに=together|川{かわ}=river|^の=(of)|近{ちか}く=near|^を=(object)|歩{ある}きませんか=won't you walk|。|私{わたし}=I|^は=topic|朝{あさ}=morning|^から=from|公園{こうえん}=park|^に=to|行{い}く=go|つもり=plan to|です=am|。 >> Then why don't we walk along the river together? I'm planning to go to the park in the morning.",
  "サム: いいですね=sounds good|。|でも=but|、|朝{あさ}=morning|^は=topic|早{はや}く=early|起{お}きなければなりませんか=do I have to get up|？ >> Sounds good. But do I have to get up early?",
  "ゆき: いいえ=no|、|早{はや}く=early|起{お}きなくてもいいです=don't have to get up|よ=you know|。|十一時{じゅういちじ}=eleven o'clock|^から=from|です=is|。 >> No, you don't have to get up early. It's from eleven.",
  "ブリップ: ブリップ=Blip|^は=topic|週末{しゅうまつ}=weekend|^も=also|充電{じゅうでん}=charging|^を=(object)|しなければなりません=have to do|……|。 >> Blip has to charge on the weekend too...",
 ],
 "grammar": [
  {"id": "tsumori", "title": "V-るつもり: plan to, intend to",
   "explain": "Dictionary form + つもりです = I intend to. Ask someone's plans with 何をするつもりですか. Not planning to: 行かないつもりです.",
   "examples": [("公園{こうえん}=park|^に=to|行{い}く=go|つもり=plan to|です=am|。", "I'm planning to go to the park.")],
   "quiz": [{"q": "来年、日本へ行く＿＿＿＿です。", "hint": "I plan to go to Japan next year.", "choices": ["つもり", "こと", "ほう"], "answer": 0, "why": "A plan: dictionary form + つもり."}]},
  {"id": "nakute-wa", "title": "V-なければならない: have to",
   "explain": "ない-form minus い + ければならない (polite: なければなりません) = must, have to. In speech it shortens to なきゃ.",
   "examples": [("仕事{しごと}=work|^に=to|行{い}かなければなりません=have to go|。", "I have to go to work.")],
   "quiz": [{"q": "明日は六時に起き＿＿＿＿＿なりません。", "hint": "Tomorrow I have to get up at six.", "choices": ["なければ", "なくても", "ないで"], "answer": 0, "why": "Have to: なければならない."}]},
  {"id": "nakute-mo-ii", "title": "V-なくてもいい: don't have to",
   "explain": "ない-form minus い + くてもいい = it's okay not to, you don't have to. It answers a なければなりませんか question.",
   "examples": [("早{はや}く=early|起{お}きなくてもいいです=don't have to get up|。", "You don't have to get up early.")],
   "quiz": [{"q": "明日は来＿＿＿＿いいです。", "hint": "You don't have to come tomorrow.", "choices": ["なくても", "なければ", "ては"], "answer": 0, "why": "No need: なくてもいい."}]},
 ],
 "kanji": [
  ("休", "キュウ", "やす.む", "rest", [("休み", "やすみ", "day off"), ("休む", "やすむ", "to rest")]),
  ("川", "セン", "かわ", "river", [("川", "かわ", "river")]),
  ("九", "キュウ,ク", "ここの", "nine", [("九時", "くじ", "nine o'clock")]),
  ("土", "ド", "つち", "earth, Saturday", [("土曜日", "どようび", "Saturday")]),
  ("仕", "シ", "つか.える", "serve, do", [("仕事", "しごと", "work, job")]),
 ],
 "build": [2, 4],
 "questions": [
  {"q": "サムさんは土曜日に何をしなければなりませんか。", "en": "What does Sam have to do on Saturday?", "choices": ["仕事に行く", "公園に行く", "早く寝る"], "answer": 0},
  {"q": "日曜日、二人はどこを歩きますか。", "en": "Where will they walk on Sunday?", "choices": ["川の近く", "博物館の中", "駅の前"], "answer": 0},
  {"q": "サムさんは日曜日に早く起きなければなりませんか。", "en": "Does Sam have to get up early on Sunday?", "choices": ["いいえ、起きなくてもいいです", "はい、六時に", "はい、九時に"], "answer": 0},
 ],
 "talk": "Tell Blip your plans for the weekend (～つもりです), one thing you have to do (～なければなりません) and one thing you don't (～なくてもいいです).",
},
]
