import { defineConfig } from "vite";

// The app, the overview explainer, the course chapters, and the license track.
export default defineConfig({
  base: "./", // relative, so the build works at / (LAN server.ts) and under /radio/ (ihor.sh)
  build: {
    rollupOptions: {
      input: { main: "index.html", course: "course/index.html", learn: "learn.html", build: "build.html", hello: "examples/hello-dongle.html", ch01: "course/01-spinning-arrows.html", ch02: "course/02-arrows-as-numbers.html", ch03: "course/03-taking-snapshots.html", ch04: "course/04-winding-machine.html", ch05: "course/05-moving-a-station.html", ch06: "course/06-averaging-is-filtering.html", ch07: "course/07-throwing-away-snapshots.html", ch08: "course/08-chunks-of-a-live-stream.html", ch09: "course/09-fm-listening-to-the-speed.html", ch10: "course/10-am-ssb-and-morse.html", ch11: "course/11-numbers-to-speakers.html", ch12: "course/12-inside-the-dongle.html", ch13: "course/13-usb-from-zero.html", ch14: "course/14-writing-the-driver.html", ch15: "course/15-the-network-source.html", ch16: "course/16-the-whole-receiver.html", ch17: "course/17-pictures-over-radio.html", ch18: "course/18-reading-the-band.html", ch19: "course/19-cleaner-sound.html", ch20: "course/20-analog-tv.html", ch21: "course/21-weather-satellites.html", ham: "ham/index.html", hamPractice: "ham/practice.html", hamL01: "ham/lessons/01-volts-amps-ohms.html", hamL02: "ham/lessons/02-decibels-and-prefixes.html", hamL03: "ham/lessons/03-capacitors-and-inductors.html", hamL04: "ham/lessons/04-resonance.html", hamL05: "ham/lessons/05-diodes-and-transistors.html", hamL06: "ham/lessons/06-waves-and-wavelength.html", hamL07: "ham/lessons/07-antennas.html", hamL08: "ham/lessons/08-feed-lines-and-swr.html", hamL09: "ham/lessons/09-propagation.html", hamL10: "ham/lessons/10-signals-and-modes.html", hamL11: "ham/lessons/11-receivers-and-transmitters.html", hamL12: "ham/lessons/12-rules-and-bands.html", hamL13: "ham/lessons/13-operating.html", hamL14: "ham/lessons/14-safety.html", hamL15: "ham/lessons/15-station-and-test-gear.html", hamL16: "ham/lessons/16-logic-and-op-amps.html", handbook: "ham/handbook/index.html", hbRf: "ham/handbook/rf-design.html", hbWs: "ham/handbook/workshop.html", sstv: "sstv.html", cw: "cw.html", aprs: "aprs/index.html", adsb: "adsb/index.html", mesh: "mesh/index.html", repeaters: "repeaters/index.html", stations: "stations/index.html" },
    },
  },
});
